del "%OSGEO4W_STARTMENU%\QGIS Desktop @version@.lnk"
del "%OSGEO4W_STARTMENU%\QGIS Browser @version@.lnk"
del "%OSGEO4W_STARTMENU%\Qt Designer with QGIS @version@ custom widgets.lnk"
rmdir "%OSGEO4W_STARTMENU%"
del "%OSGEO4W_DESKTOP%\QGIS Desktop @version@.lnk"
del "%OSGEO4W_DESKTOP%\QGIS Browser @version@.lnk"
del "%OSGEO4W_DESKTOP%\Qt Designer with QGIS @version@ custom widgets.lnk"
rmdir "%OSGEO4W_DESKTOP%"
del "%OSGEO4W_ROOT%\bin\@package@.bat"
del "%OSGEO4W_ROOT%\bin\@package@-browser.bat"
del "%OSGEO4W_ROOT%\bin\@package@-designer.bat"
del "%OSGEO4W_ROOT%\apps\@package@\python\qgis\qgisconfig.py"
del "%OSGEO4W_ROOT%\apps\@package@\bin\qgis.reg"
