"3D":
- changed-files:
  - any-glob-to-any-file: [
    'resources/3d/**/*',
    'src/3d/**/*',
    'src/app/3d/**/*',
  ]

"Annotations":
- changed-files:
  - any-glob-to-any-file: [
    'src/core/annotations/**/*',
    'src/gui/annotations/**/*',
  ]

"Chore":
- changed-files:
  - any-glob-to-any-file: [
    '.ci/**/*',
    '.docker/**/*',
    '.github/**/*',
  ]

"DB Manager":
- changed-files:
  - any-glob-to-any-file: ['python/plugins/db_manager/**/*']

"Expressions":
- changed-files:
  - any-glob-to-any-file: [
    'src/core/expression/**/*',
    'resources/function_help/**/*',
  ]

"Form":
- changed-files:
  - any-glob-to-any-file: [
    'src/core/editform/**/*',
    'src/gui/attributeformconfig/**/*',
  ]

"GRASS":
- changed-files:
  - any-glob-to-any-file: ['python/plugins/grassprovider/**/*']

"GUI/UX":
- changed-files:
  - any-glob-to-any-file: [
    'images/**/*',
    'resources/themes/**/*',
#    'src/gui/**/*', too broad
  ]

"HANA data provider":
- changed-files:
  - any-glob-to-any-file: [
    'src/providers/hana/**/*',
  ]

"Labeling":
- changed-files:
  - any-glob-to-any-file: [
    'src/app/labeling/**/*',
    'src/core/labeling/**/*',
  ]

"Locator":
- changed-files:
  - any-glob-to-any-file: [
    'src/core/locator/**/*',
    'src/gui/locator/**/*',
  ]

"Mesh":
- changed-files:
  - any-glob-to-any-file: [
    'external/mdal/**/*',
    'src/analysis/mesh/**/*',
    'src/core/mesh/**/*',
    'src/gui/mesh/**/*',
  ]

"Metasearch":
- changed-files:
  - any-glob-to-any-file: ['python/plugins/MetaSearch/**/*']

"Point Clouds":
- changed-files:
  - any-glob-to-any-file: [
    'src/app/pointcloud/**/*',
    'src/core/pointcloud/**/*',
    'src/gui/pointcloud/**/*',
  ]

"PostGIS data provider":
- changed-files:
  - any-glob-to-any-file: ['src/providers/postgres/**/*']

"Processing":
- changed-files:
  - any-glob-to-any-file: [
      'python/plugins/processing/**/*',
      'src/analysis/**/*',
      'src/core/processing/**/*',
      'src/process/**/*'
  ]

"Python Console":
- changed-files:
  - any-glob-to-any-file: [
    'python/console/**/*',
  ]

"Quick":
- changed-files:
  - any-glob-to-any-file: [
    'src/quickgui/**/*',
  ]

"Server":
- changed-files:
  - any-glob-to-any-file: [
      'src/server/**/*',
      'resources/server/**/*'
  ]

"Vector tiles":
- changed-files:
  - any-glob-to-any-file: [
    'src/core/vectortile/**/*',
    'src/gui/vectortile/**/*',
  ]
