QGTOP=../../

LDADD = $(QGIS_LIBS)

OBJECTS = qgis-main.o

all: libs objects qgis.exe

objects:
	$(MAKE) -f Makefile qgis-main.o

libs:
	$(MAKE) -f Makefile libqgis_gui.la
	
qgis.exe:
	$(CXX) -o $@ $(OBJECTS) $(LDADD)
	$(STRIP) $@

install: all
	$(INSTALL) -m 755 qgis.exe $(prefix)/bin/qgis.exe

include ../../Makefile.win.rules
