WINSUBDIRS = src src/providers/ogr src/providers/grass \
	src/plugins/grass

all: winsubdirs

install: all
	$(MAKE) -C i18n -f Makefile install
	$(MAKE) -C images -f Makefile install
	$(MAKE) -C resources -f Makefile install
	$(MAKE) -C src -f Makefile.win install


include ./Makefile.win.rules
