.TH QGIS 1 "May 23, 2011"
.SH NAME
qbrowser \- Quantum GIS Geographic Information System Browser
.SH SYNOPSIS
.B qbrowser
.SH DESCRIPTION
Quantum GIS (QGIS) is a cross platform, Free and Open Source Geographic
Information System (GIS). Supported platforms include Linux/Unix, Mac OS X and
Microsoft Windows. QGIS supports vector, raster, and database formats. QGIS is
licensed under the GNU General Public License.

This is the browser.
.SH BUGS
See the QGIS home page (http://qgis.org) for a list of known issues with the
latest release.
.SH AUTHOR
Juergen E. Fischer <jef at norbit dot de>
