.TH QGIS 1 "March 9, 2011"
.SH NAME
qgis \- QGIS Geographic Information System
.SH SYNOPSIS
.B qgis
.RI [options] "\ " [file]
.SH DESCRIPTION
QGIS is a cross platform, Free and Open Source Geographic
Information System (GIS). Supported platforms include Linux/Unix, Mac OS X and
Microsoft Windows. QGIS supports vector, raster, and database formats. QGIS is
licensed under the GNU General Public License.

Some of the major features include:

*Support for spatially enabled PostGIS tables
.br
*Support for shapefiles, ArcInfo coverages, Mapinfo, and other formats
  supported by OGR
.br
*Raster support for a large number of formats
.br
*Identify features
.br
*Display attribute tables
.br
*Select features
.br
*GRASS Digitizing
.br
*Feature labeling
.SH OPTIONS
For a list of command-line options supported by this build, see:
.B qgis --help

.SH FILES
.TP
.B ~/.config/QGIS/qgis.conf
QGIS preferences file. This file stores windows size/location, loaded plugins,
user options, and other application settings.
.SH BUGS
See the QGIS home page (http://qgis.org) for a list of known issues with the
latest release.
.SH AUTHOR
Gary Sherman <sherman at mrcc.com>

