.TH QGIS_HELP 1 "April 13, 2008"
.SH NAME
qgis_help \- help viewer for qgis, the geographic data viewer
.SH SYNOPSIS
.B qgis_help [helpfile]
.br
.SH DESCRIPTION
.B qgis_help
is internally used by
.B qgis
to view help files.
.SH SEE ALSO
qgis(1)
.SH AUTHOR
This manual page was written by J\[:u]rgen Fischer <jef@norbit.de>.
