# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/DlgDownloadOSM.ui'
#
# Created: Fri Jul 10 15:27:30 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DlgDownloadOSM(object):
    def setupUi(self, DlgDownloadOSM):
        DlgDownloadOSM.setObjectName("DlgDownloadOSM")
        DlgDownloadOSM.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgDownloadOSM.resize(595, 357)
        DlgDownloadOSM.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        DlgDownloadOSM.setModal(True)
        self.vboxlayout = QtGui.QVBoxLayout(DlgDownloadOSM)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupBox = QtGui.QGroupBox(DlgDownloadOSM)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.latFromLineEdit = QtGui.QLineEdit(self.groupBox)
        self.latFromLineEdit.setEnabled(True)
        self.latFromLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.latFromLineEdit.setObjectName("latFromLineEdit")
        self.gridlayout.addWidget(self.latFromLineEdit, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridlayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.latToLineEdit = QtGui.QLineEdit(self.groupBox)
        self.latToLineEdit.setEnabled(True)
        self.latToLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.latToLineEdit.setObjectName("latToLineEdit")
        self.gridlayout.addWidget(self.latToLineEdit, 0, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.lonFromLineEdit = QtGui.QLineEdit(self.groupBox)
        self.lonFromLineEdit.setEnabled(True)
        self.lonFromLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lonFromLineEdit.setObjectName("lonFromLineEdit")
        self.gridlayout.addWidget(self.lonFromLineEdit, 1, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridlayout.addWidget(self.label_7, 1, 4, 1, 1)
        self.lonToLineEdit = QtGui.QLineEdit(self.groupBox)
        self.lonToLineEdit.setEnabled(True)
        self.lonToLineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lonToLineEdit.setObjectName("lonToLineEdit")
        self.gridlayout.addWidget(self.lonToLineEdit, 1, 5, 1, 1)
        self.vboxlayout1.addLayout(self.gridlayout)
        spacerItem = QtGui.QSpacerItem(20, 8, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.vboxlayout1.addItem(spacerItem)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.extentInfoLabel = QtGui.QLabel(self.groupBox)
        self.extentInfoLabel.setMargin(0)
        self.extentInfoLabel.setObjectName("extentInfoLabel")
        self.hboxlayout.addWidget(self.extentInfoLabel)
        self.helpButton = QtGui.QToolButton(self.groupBox)
        self.helpButton.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButton.setObjectName("helpButton")
        self.hboxlayout.addWidget(self.helpButton)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.vboxlayout.addWidget(self.groupBox)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName("gridlayout1")
        self.label_9 = QtGui.QLabel(DlgDownloadOSM)
        self.label_9.setObjectName("label_9")
        self.gridlayout1.addWidget(self.label_9, 0, 0, 1, 2)
        self.destdirLineEdit = QtGui.QLineEdit(DlgDownloadOSM)
        self.destdirLineEdit.setEnabled(False)
        self.destdirLineEdit.setObjectName("destdirLineEdit")
        self.gridlayout1.addWidget(self.destdirLineEdit, 1, 0, 1, 1)
        self.choosedirButton = QtGui.QPushButton(DlgDownloadOSM)
        self.choosedirButton.setObjectName("choosedirButton")
        self.gridlayout1.addWidget(self.choosedirButton, 1, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout1)
        self.autoLoadCheckBox = QtGui.QCheckBox(DlgDownloadOSM)
        self.autoLoadCheckBox.setChecked(True)
        self.autoLoadCheckBox.setObjectName("autoLoadCheckBox")
        self.vboxlayout.addWidget(self.autoLoadCheckBox)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem2)
        self.chkReplaceData = QtGui.QCheckBox(DlgDownloadOSM)
        self.chkReplaceData.setChecked(False)
        self.chkReplaceData.setObjectName("chkReplaceData")
        self.hboxlayout1.addWidget(self.chkReplaceData)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setSpacing(0)
        self.hboxlayout2.setContentsMargins(-1, 0, -1, -1)
        self.hboxlayout2.setObjectName("hboxlayout2")
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem3)
        self.chkCustomRenderer = QtGui.QCheckBox(DlgDownloadOSM)
        self.chkCustomRenderer.setChecked(True)
        self.chkCustomRenderer.setObjectName("chkCustomRenderer")
        self.hboxlayout2.addWidget(self.chkCustomRenderer)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem4)
        self.styleCombo = QtGui.QComboBox(DlgDownloadOSM)
        self.styleCombo.setMinimumSize(QtCore.QSize(182, 0))
        self.styleCombo.setMaximumSize(QtCore.QSize(182, 16777215))
        self.styleCombo.setObjectName("styleCombo")
        self.hboxlayout2.addWidget(self.styleCombo)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem5)
        self.vboxlayout.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem6)
        self.downloadButton = QtGui.QPushButton(DlgDownloadOSM)
        self.downloadButton.setObjectName("downloadButton")
        self.hboxlayout3.addWidget(self.downloadButton)
        self.cancelButton = QtGui.QPushButton(DlgDownloadOSM)
        self.cancelButton.setObjectName("cancelButton")
        self.hboxlayout3.addWidget(self.cancelButton)
        self.vboxlayout.addLayout(self.hboxlayout3)

        self.retranslateUi(DlgDownloadOSM)
        QtCore.QMetaObject.connectSlotsByName(DlgDownloadOSM)

    def retranslateUi(self, DlgDownloadOSM):
        DlgDownloadOSM.setWindowTitle(QtGui.QApplication.translate("DlgDownloadOSM", "Download OSM data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DlgDownloadOSM", "Extent", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DlgDownloadOSM", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DlgDownloadOSM", "   From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("DlgDownloadOSM", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DlgDownloadOSM", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("DlgDownloadOSM", "   From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("DlgDownloadOSM", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.extentInfoLabel.setText(QtGui.QApplication.translate("DlgDownloadOSM", "<nothing>", None, QtGui.QApplication.UnicodeUTF8))
        self.helpButton.setText(QtGui.QApplication.translate("DlgDownloadOSM", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("DlgDownloadOSM", "Download to:", None, QtGui.QApplication.UnicodeUTF8))
        self.choosedirButton.setText(QtGui.QApplication.translate("DlgDownloadOSM", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.autoLoadCheckBox.setText(QtGui.QApplication.translate("DlgDownloadOSM", "Open data automatically after download", None, QtGui.QApplication.UnicodeUTF8))
        self.chkReplaceData.setText(QtGui.QApplication.translate("DlgDownloadOSM", "Replace current data (current layer will be removed)", None, QtGui.QApplication.UnicodeUTF8))
        self.chkCustomRenderer.setText(QtGui.QApplication.translate("DlgDownloadOSM", "Use custom renderer", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadButton.setText(QtGui.QApplication.translate("DlgDownloadOSM", "Download", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("DlgDownloadOSM", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

