# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/DlgSaveOSM.ui'
#
# Created: Tue Jul 14 14:44:25 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DlgSaveOSM(object):
    def setupUi(self, DlgSaveOSM):
        DlgSaveOSM.setObjectName("DlgSaveOSM")
        DlgSaveOSM.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgSaveOSM.resize(370, 206)
        DlgSaveOSM.setModal(True)
        self.vboxlayout = QtGui.QVBoxLayout(DlgSaveOSM)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtGui.QLabel(DlgSaveOSM)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 2)
        self.OSMFileEdit = QtGui.QLineEdit(DlgSaveOSM)
        self.OSMFileEdit.setObjectName("OSMFileEdit")
        self.gridlayout.addWidget(self.OSMFileEdit, 1, 0, 1, 1)
        self.browseOSMButton = QtGui.QPushButton(DlgSaveOSM)
        self.browseOSMButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.browseOSMButton.setObjectName("browseOSMButton")
        self.gridlayout.addWidget(self.browseOSMButton, 1, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.label_2 = QtGui.QLabel(DlgSaveOSM)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setContentsMargins(15, -1, 0, 10)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.chkPoints = QtGui.QCheckBox(DlgSaveOSM)
        self.chkPoints.setChecked(True)
        self.chkPoints.setObjectName("chkPoints")
        self.vboxlayout1.addWidget(self.chkPoints)
        self.chkLines = QtGui.QCheckBox(DlgSaveOSM)
        self.chkLines.setChecked(True)
        self.chkLines.setObjectName("chkLines")
        self.vboxlayout1.addWidget(self.chkLines)
        self.chkPolygons = QtGui.QCheckBox(DlgSaveOSM)
        self.chkPolygons.setChecked(True)
        self.chkPolygons.setObjectName("chkPolygons")
        self.vboxlayout1.addWidget(self.chkPolygons)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.chkRelations = QtGui.QCheckBox(DlgSaveOSM)
        self.chkRelations.setChecked(True)
        self.chkRelations.setObjectName("chkRelations")
        self.vboxlayout2.addWidget(self.chkRelations)
        self.chkTags = QtGui.QCheckBox(DlgSaveOSM)
        self.chkTags.setChecked(True)
        self.chkTags.setObjectName("chkTags")
        self.vboxlayout2.addWidget(self.chkTags)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout2.addItem(spacerItem)
        self.hboxlayout.addLayout(self.vboxlayout2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName("vboxlayout3")
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem2)
        self.buttonBox = QtGui.QDialogButtonBox(DlgSaveOSM)
        self.buttonBox.setMaximumSize(QtCore.QSize(110, 16777215))
        self.buttonBox.setBaseSize(QtCore.QSize(110, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.NoButton|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout3.addWidget(self.buttonBox)
        self.hboxlayout.addLayout(self.vboxlayout3)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.retranslateUi(DlgSaveOSM)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DlgSaveOSM.reject)
        QtCore.QMetaObject.connectSlotsByName(DlgSaveOSM)
        DlgSaveOSM.setTabOrder(self.OSMFileEdit, self.browseOSMButton)

    def retranslateUi(self, DlgSaveOSM):
        DlgSaveOSM.setWindowTitle(QtGui.QApplication.translate("DlgSaveOSM", "Save OSM", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DlgSaveOSM", "Where to save:", None, QtGui.QApplication.UnicodeUTF8))
        self.browseOSMButton.setText(QtGui.QApplication.translate("DlgSaveOSM", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DlgSaveOSM", "Features to save:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPoints.setText(QtGui.QApplication.translate("DlgSaveOSM", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.chkLines.setText(QtGui.QApplication.translate("DlgSaveOSM", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPolygons.setText(QtGui.QApplication.translate("DlgSaveOSM", "Polygons", None, QtGui.QApplication.UnicodeUTF8))
        self.chkRelations.setText(QtGui.QApplication.translate("DlgSaveOSM", "Relations", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTags.setText(QtGui.QApplication.translate("DlgSaveOSM", "Tags", None, QtGui.QApplication.UnicodeUTF8))

