# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/DlgUploadOSM.ui'
#
# Created: Tue Jul 14 14:44:26 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DlgUploadOSM(object):
    def setupUi(self, DlgUploadOSM):
        DlgUploadOSM.setObjectName("DlgUploadOSM")
        DlgUploadOSM.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgUploadOSM.resize(373, 468)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DlgUploadOSM.sizePolicy().hasHeightForWidth())
        DlgUploadOSM.setSizePolicy(sizePolicy)
        DlgUploadOSM.setModal(True)
        self.vboxlayout = QtGui.QVBoxLayout(DlgUploadOSM)
        self.vboxlayout.setObjectName("vboxlayout")
        self.groupBox = QtGui.QGroupBox(DlgUploadOSM)
        self.groupBox.setObjectName("groupBox")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.uploadChangesTable = QtGui.QTreeWidget(self.groupBox)
        self.uploadChangesTable.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadChangesTable.sizePolicy().hasHeightForWidth())
        self.uploadChangesTable.setSizePolicy(sizePolicy)
        self.uploadChangesTable.setMinimumSize(QtCore.QSize(330, 90))
        self.uploadChangesTable.setMaximumSize(QtCore.QSize(330, 90))
        self.uploadChangesTable.setAutoFillBackground(False)
        self.uploadChangesTable.setTextElideMode(QtCore.Qt.ElideLeft)
        self.uploadChangesTable.setRootIsDecorated(False)
        self.uploadChangesTable.setItemsExpandable(False)
        self.uploadChangesTable.setColumnCount(5)
        self.uploadChangesTable.setObjectName("uploadChangesTable")
        self.vboxlayout1.addWidget(self.uploadChangesTable)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.vboxlayout1.addWidget(self.label_4)
        self.commentTextEdit = QtGui.QTextEdit(self.groupBox)
        self.commentTextEdit.setEnabled(True)
        self.commentTextEdit.setMaximumSize(QtCore.QSize(16777215, 85))
        self.commentTextEdit.setObjectName("commentTextEdit")
        self.vboxlayout1.addWidget(self.commentTextEdit)
        self.vboxlayout.addWidget(self.groupBox)
        self.accountGroupBox = QtGui.QGroupBox(DlgUploadOSM)
        self.accountGroupBox.setEnabled(True)
        self.accountGroupBox.setObjectName("accountGroupBox")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.accountGroupBox)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtGui.QLabel(self.accountGroupBox)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.userLineEdit = QtGui.QLineEdit(self.accountGroupBox)
        self.userLineEdit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userLineEdit.sizePolicy().hasHeightForWidth())
        self.userLineEdit.setSizePolicy(sizePolicy)
        self.userLineEdit.setObjectName("userLineEdit")
        self.gridlayout.addWidget(self.userLineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.accountGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.passwdLineEdit = QtGui.QLineEdit(self.accountGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwdLineEdit.sizePolicy().hasHeightForWidth())
        self.passwdLineEdit.setSizePolicy(sizePolicy)
        self.passwdLineEdit.setObjectName("passwdLineEdit")
        self.gridlayout.addWidget(self.passwdLineEdit, 1, 1, 1, 1)
        self.chkShowPasswd = QtGui.QCheckBox(self.accountGroupBox)
        self.chkShowPasswd.setObjectName("chkShowPasswd")
        self.gridlayout.addWidget(self.chkShowPasswd, 2, 1, 1, 1)
        self.chkSavePasswd = QtGui.QCheckBox(self.accountGroupBox)
        self.chkSavePasswd.setObjectName("chkSavePasswd")
        self.gridlayout.addWidget(self.chkSavePasswd, 3, 1, 1, 1)
        self.vboxlayout2.addLayout(self.gridlayout)
        self.vboxlayout.addWidget(self.accountGroupBox)
        self.buttonBox = QtGui.QDialogButtonBox(DlgUploadOSM)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(DlgUploadOSM)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), DlgUploadOSM.reject)
        QtCore.QMetaObject.connectSlotsByName(DlgUploadOSM)
        DlgUploadOSM.setTabOrder(self.userLineEdit, self.passwdLineEdit)
        DlgUploadOSM.setTabOrder(self.passwdLineEdit, self.chkShowPasswd)
        DlgUploadOSM.setTabOrder(self.chkShowPasswd, self.buttonBox)

    def retranslateUi(self, DlgUploadOSM):
        DlgUploadOSM.setWindowTitle(QtGui.QApplication.translate("DlgUploadOSM", "Upload OSM data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("DlgUploadOSM", "Ready for upload", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadChangesTable.headerItem().setText(0, QtGui.QApplication.translate("DlgUploadOSM", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadChangesTable.headerItem().setText(1, QtGui.QApplication.translate("DlgUploadOSM", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadChangesTable.headerItem().setText(2, QtGui.QApplication.translate("DlgUploadOSM", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadChangesTable.headerItem().setText(3, QtGui.QApplication.translate("DlgUploadOSM", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadChangesTable.headerItem().setText(4, QtGui.QApplication.translate("DlgUploadOSM", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("DlgUploadOSM", "Comment on your changes:", None, QtGui.QApplication.UnicodeUTF8))
        self.accountGroupBox.setTitle(QtGui.QApplication.translate("DlgUploadOSM", "OSM account", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("DlgUploadOSM", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("DlgUploadOSM", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.chkShowPasswd.setText(QtGui.QApplication.translate("DlgUploadOSM", "Show password", None, QtGui.QApplication.UnicodeUTF8))
        self.chkSavePasswd.setText(QtGui.QApplication.translate("DlgUploadOSM", "Save password", None, QtGui.QApplication.UnicodeUTF8))

