# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/DockWidget.ui'
#
# Created: Thu Aug  6 16:37:44 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_OsmDockWidget(object):
    def setupUi(self, OsmDockWidget):
        OsmDockWidget.setObjectName("OsmDockWidget")
        OsmDockWidget.setWindowModality(QtCore.Qt.NonModal)
        OsmDockWidget.setEnabled(True)
        OsmDockWidget.resize(265, 776)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OsmDockWidget.sizePolicy().hasHeightForWidth())
        OsmDockWidget.setSizePolicy(sizePolicy)
        OsmDockWidget.setMinimumSize(QtCore.QSize(261, 357))
        OsmDockWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.vboxlayout = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(1)
        self.hboxlayout.setContentsMargins(-1, -1, 0, -1)
        self.hboxlayout.setObjectName("hboxlayout")
        self.dummyButton = QtGui.QToolButton(self.dockWidgetContents)
        self.dummyButton.setMinimumSize(QtCore.QSize(1, 25))
        self.dummyButton.setMaximumSize(QtCore.QSize(1, 27))
        self.dummyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dummyButton.setCheckable(True)
        self.dummyButton.setObjectName("dummyButton")
        self.hboxlayout.addWidget(self.dummyButton)
        self.identifyButton = QtGui.QToolButton(self.dockWidgetContents)
        self.identifyButton.setMinimumSize(QtCore.QSize(26, 25))
        self.identifyButton.setMaximumSize(QtCore.QSize(25, 26))
        self.identifyButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.identifyButton.setCheckable(True)
        self.identifyButton.setObjectName("identifyButton")
        self.hboxlayout.addWidget(self.identifyButton)
        self.moveButton = QtGui.QToolButton(self.dockWidgetContents)
        self.moveButton.setMinimumSize(QtCore.QSize(26, 25))
        self.moveButton.setMaximumSize(QtCore.QSize(25, 26))
        self.moveButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.moveButton.setCheckable(True)
        self.moveButton.setObjectName("moveButton")
        self.hboxlayout.addWidget(self.moveButton)
        self.createPointButton = QtGui.QToolButton(self.dockWidgetContents)
        self.createPointButton.setMinimumSize(QtCore.QSize(26, 25))
        self.createPointButton.setMaximumSize(QtCore.QSize(25, 26))
        self.createPointButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createPointButton.setCheckable(True)
        self.createPointButton.setObjectName("createPointButton")
        self.hboxlayout.addWidget(self.createPointButton)
        self.createLineButton = QtGui.QToolButton(self.dockWidgetContents)
        self.createLineButton.setMinimumSize(QtCore.QSize(26, 25))
        self.createLineButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createLineButton.setCheckable(True)
        self.createLineButton.setObjectName("createLineButton")
        self.hboxlayout.addWidget(self.createLineButton)
        self.createPolygonButton = QtGui.QToolButton(self.dockWidgetContents)
        self.createPolygonButton.setMinimumSize(QtCore.QSize(26, 25))
        self.createPolygonButton.setMaximumSize(QtCore.QSize(25, 26))
        self.createPolygonButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createPolygonButton.setCheckable(True)
        self.createPolygonButton.setObjectName("createPolygonButton")
        self.hboxlayout.addWidget(self.createPolygonButton)
        self.createRelationButton = QtGui.QToolButton(self.dockWidgetContents)
        self.createRelationButton.setMinimumSize(QtCore.QSize(26, 25))
        self.createRelationButton.setMaximumSize(QtCore.QSize(25, 26))
        self.createRelationButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.createRelationButton.setCheckable(True)
        self.createRelationButton.setObjectName("createRelationButton")
        self.hboxlayout.addWidget(self.createRelationButton)
        self.undoButton = QtGui.QToolButton(self.dockWidgetContents)
        self.undoButton.setMaximumSize(QtCore.QSize(25, 26))
        self.undoButton.setObjectName("undoButton")
        self.hboxlayout.addWidget(self.undoButton)
        self.redoButton = QtGui.QToolButton(self.dockWidgetContents)
        self.redoButton.setMaximumSize(QtCore.QSize(25, 26))
        self.redoButton.setObjectName("redoButton")
        self.hboxlayout.addWidget(self.redoButton)
        self.urDetailsButton = QtGui.QToolButton(self.dockWidgetContents)
        self.urDetailsButton.setMaximumSize(QtCore.QSize(25, 26))
        self.urDetailsButton.setCheckable(True)
        self.urDetailsButton.setObjectName("urDetailsButton")
        self.hboxlayout.addWidget(self.urDetailsButton)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.featInfoBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.featInfoBox.setEnabled(True)
        self.featInfoBox.setMinimumSize(QtCore.QSize(0, 95))
        self.featInfoBox.setMaximumSize(QtCore.QSize(16777215, 95))
        self.featInfoBox.setObjectName("featInfoBox")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.featInfoBox)
        self.vboxlayout1.setSpacing(0)
        self.vboxlayout1.setContentsMargins(18, 4, 3, 6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtGui.QLabel(self.featInfoBox)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.featInfoBox)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.featInfoBox)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.typeIdLabel = QtGui.QLabel(self.featInfoBox)
        self.typeIdLabel.setObjectName("typeIdLabel")
        self.gridlayout.addWidget(self.typeIdLabel, 0, 1, 1, 1)
        self.createdLabel = QtGui.QLabel(self.featInfoBox)
        self.createdLabel.setObjectName("createdLabel")
        self.gridlayout.addWidget(self.createdLabel, 1, 1, 1, 1)
        self.userLabel = QtGui.QLabel(self.featInfoBox)
        self.userLabel.setObjectName("userLabel")
        self.gridlayout.addWidget(self.userLabel, 2, 1, 1, 1)
        self.removeButton = QtGui.QToolButton(self.featInfoBox)
        self.removeButton.setMaximumSize(QtCore.QSize(25, 25))
        self.removeButton.setObjectName("removeButton")
        self.gridlayout.addWidget(self.removeButton, 2, 2, 1, 1)
        self.vboxlayout1.addLayout(self.gridlayout)
        self.vboxlayout.addWidget(self.featInfoBox)
        self.propRelBox = QtGui.QTabWidget(self.dockWidgetContents)
        self.propRelBox.setMinimumSize(QtCore.QSize(0, 175))
        self.propRelBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.propRelBox.setTabPosition(QtGui.QTabWidget.North)
        self.propRelBox.setTabShape(QtGui.QTabWidget.Rounded)
        self.propRelBox.setObjectName("propRelBox")
        self.Properties = QtGui.QWidget()
        self.Properties.setObjectName("Properties")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.Properties)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.tagTable = QtGui.QTableWidget(self.Properties)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagTable.sizePolicy().hasHeightForWidth())
        self.tagTable.setSizePolicy(sizePolicy)
        self.tagTable.setMinimumSize(QtCore.QSize(205, 100))
        self.tagTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tagTable.setFrameShape(QtGui.QFrame.Box)
        self.tagTable.setObjectName("tagTable")
        self.tagTable.setColumnCount(0)
        self.tagTable.setRowCount(0)
        self.vboxlayout2.addWidget(self.tagTable)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.deleteTagsButton = QtGui.QToolButton(self.Properties)
        self.deleteTagsButton.setObjectName("deleteTagsButton")
        self.hboxlayout1.addWidget(self.deleteTagsButton)
        self.vboxlayout2.addLayout(self.hboxlayout1)
        self.propRelBox.addTab(self.Properties, "")
        self.Relations = QtGui.QWidget()
        self.Relations.setObjectName("Relations")
        self.vboxlayout3 = QtGui.QVBoxLayout(self.Relations)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.relListWidget = QtGui.QListWidget(self.Relations)
        self.relListWidget.setEnabled(False)
        self.relListWidget.setMinimumSize(QtCore.QSize(0, 60))
        self.relListWidget.setMaximumSize(QtCore.QSize(16777215, 104))
        self.relListWidget.setFrameShape(QtGui.QFrame.Box)
        self.relListWidget.setObjectName("relListWidget")
        self.hboxlayout2.addWidget(self.relListWidget)
        self.vboxlayout4 = QtGui.QVBoxLayout()
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.addRelationButton = QtGui.QPushButton(self.Relations)
        self.addRelationButton.setEnabled(False)
        self.addRelationButton.setMinimumSize(QtCore.QSize(26, 25))
        self.addRelationButton.setMaximumSize(QtCore.QSize(26, 25))
        self.addRelationButton.setObjectName("addRelationButton")
        self.vboxlayout4.addWidget(self.addRelationButton)
        self.editRelationButton = QtGui.QPushButton(self.Relations)
        self.editRelationButton.setEnabled(False)
        self.editRelationButton.setMinimumSize(QtCore.QSize(26, 25))
        self.editRelationButton.setMaximumSize(QtCore.QSize(26, 25))
        self.editRelationButton.setObjectName("editRelationButton")
        self.vboxlayout4.addWidget(self.editRelationButton)
        self.removeRelationButton = QtGui.QPushButton(self.Relations)
        self.removeRelationButton.setEnabled(False)
        self.removeRelationButton.setMinimumSize(QtCore.QSize(26, 25))
        self.removeRelationButton.setMaximumSize(QtCore.QSize(26, 25))
        self.removeRelationButton.setObjectName("removeRelationButton")
        self.vboxlayout4.addWidget(self.removeRelationButton)
        spacerItem1 = QtGui.QSpacerItem(26, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.vboxlayout4.addItem(spacerItem1)
        self.hboxlayout2.addLayout(self.vboxlayout4)
        self.vboxlayout3.addLayout(self.hboxlayout2)
        self.label_2 = QtGui.QLabel(self.Relations)
        self.label_2.setObjectName("label_2")
        self.vboxlayout3.addWidget(self.label_2)
        self.relTagsTree = QtGui.QTreeWidget(self.Relations)
        self.relTagsTree.setEnabled(False)
        self.relTagsTree.setMinimumSize(QtCore.QSize(0, 115))
        self.relTagsTree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.relTagsTree.setProperty("cursor", QtCore.QVariant(QtCore.Qt.ForbiddenCursor))
        self.relTagsTree.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.relTagsTree.setFrameShape(QtGui.QFrame.Box)
        self.relTagsTree.setFrameShadow(QtGui.QFrame.Sunken)
        self.relTagsTree.setIndentation(0)
        self.relTagsTree.setRootIsDecorated(False)
        self.relTagsTree.setItemsExpandable(False)
        self.relTagsTree.setColumnCount(1)
        self.relTagsTree.setObjectName("relTagsTree")
        self.vboxlayout3.addWidget(self.relTagsTree)
        self.label_3 = QtGui.QLabel(self.Relations)
        self.label_3.setObjectName("label_3")
        self.vboxlayout3.addWidget(self.label_3)
        self.relMembersList = QtGui.QListWidget(self.Relations)
        self.relMembersList.setEnabled(False)
        self.relMembersList.setMinimumSize(QtCore.QSize(0, 115))
        self.relMembersList.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.relMembersList.setFrameShape(QtGui.QFrame.Box)
        self.relMembersList.setObjectName("relMembersList")
        self.vboxlayout3.addWidget(self.relMembersList)
        self.propRelBox.addTab(self.Relations, "")
        self.vboxlayout.addWidget(self.propRelBox)
        OsmDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(OsmDockWidget)
        self.propRelBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(OsmDockWidget)

    def retranslateUi(self, OsmDockWidget):
        OsmDockWidget.setWindowTitle(QtGui.QApplication.translate("OsmDockWidget", "OSM Feature", None, QtGui.QApplication.UnicodeUTF8))
        self.dummyButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.identifyButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Identify object", None, QtGui.QApplication.UnicodeUTF8))
        self.identifyButton.setStatusTip(QtGui.QApplication.translate("OsmDockWidget", "Identify object", None, QtGui.QApplication.UnicodeUTF8))
        self.identifyButton.setWhatsThis(QtGui.QApplication.translate("OsmDockWidget", "Identify object", None, QtGui.QApplication.UnicodeUTF8))
        self.identifyButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.moveButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Move object", None, QtGui.QApplication.UnicodeUTF8))
        self.moveButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.createPointButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Create point", None, QtGui.QApplication.UnicodeUTF8))
        self.createPointButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.createLineButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Create line", None, QtGui.QApplication.UnicodeUTF8))
        self.createLineButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.createPolygonButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Create polygon", None, QtGui.QApplication.UnicodeUTF8))
        self.createPolygonButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.createRelationButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Create relation", None, QtGui.QApplication.UnicodeUTF8))
        self.createRelationButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setStatusTip(QtGui.QApplication.translate("OsmDockWidget", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setWhatsThis(QtGui.QApplication.translate("OsmDockWidget", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.undoButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setStatusTip(QtGui.QApplication.translate("OsmDockWidget", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setWhatsThis(QtGui.QApplication.translate("OsmDockWidget", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.redoButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.urDetailsButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Show/Hide OSM Edit History", None, QtGui.QApplication.UnicodeUTF8))
        self.urDetailsButton.setStatusTip(QtGui.QApplication.translate("OsmDockWidget", "Show/Hide OSM Edit History", None, QtGui.QApplication.UnicodeUTF8))
        self.urDetailsButton.setWhatsThis(QtGui.QApplication.translate("OsmDockWidget", "Show/Hide OSM Edit History", None, QtGui.QApplication.UnicodeUTF8))
        self.urDetailsButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.featInfoBox.setTitle(QtGui.QApplication.translate("OsmDockWidget", "Feature:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OsmDockWidget", "TYPE, ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OsmDockWidget", "CREATED:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OsmDockWidget", "USER:", None, QtGui.QApplication.UnicodeUTF8))
        self.typeIdLabel.setText(QtGui.QApplication.translate("OsmDockWidget", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.createdLabel.setText(QtGui.QApplication.translate("OsmDockWidget", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.userLabel.setText(QtGui.QApplication.translate("OsmDockWidget", "unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteTagsButton.setText(QtGui.QApplication.translate("OsmDockWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.propRelBox.setTabText(self.propRelBox.indexOf(self.Properties), QtGui.QApplication.translate("OsmDockWidget", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.addRelationButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Add new relation", None, QtGui.QApplication.UnicodeUTF8))
        self.addRelationButton.setStatusTip(QtGui.QApplication.translate("OsmDockWidget", "Add new relation", None, QtGui.QApplication.UnicodeUTF8))
        self.addRelationButton.setWhatsThis(QtGui.QApplication.translate("OsmDockWidget", "Add new relation", None, QtGui.QApplication.UnicodeUTF8))
        self.addRelationButton.setText(QtGui.QApplication.translate("OsmDockWidget", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.editRelationButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Edit selected relation", None, QtGui.QApplication.UnicodeUTF8))
        self.editRelationButton.setStatusTip(QtGui.QApplication.translate("OsmDockWidget", "Edit selected relation", None, QtGui.QApplication.UnicodeUTF8))
        self.editRelationButton.setWhatsThis(QtGui.QApplication.translate("OsmDockWidget", "Edit selected relation", None, QtGui.QApplication.UnicodeUTF8))
        self.editRelationButton.setText(QtGui.QApplication.translate("OsmDockWidget", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.removeRelationButton.setToolTip(QtGui.QApplication.translate("OsmDockWidget", "Remove selected relation", None, QtGui.QApplication.UnicodeUTF8))
        self.removeRelationButton.setStatusTip(QtGui.QApplication.translate("OsmDockWidget", "Remove selected relation", None, QtGui.QApplication.UnicodeUTF8))
        self.removeRelationButton.setWhatsThis(QtGui.QApplication.translate("OsmDockWidget", "Remove selected relation", None, QtGui.QApplication.UnicodeUTF8))
        self.removeRelationButton.setText(QtGui.QApplication.translate("OsmDockWidget", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OsmDockWidget", "Relation tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.relTagsTree.headerItem().setText(0, QtGui.QApplication.translate("OsmDockWidget", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OsmDockWidget", "Relation members:", None, QtGui.QApplication.UnicodeUTF8))
        self.propRelBox.setTabText(self.propRelBox.indexOf(self.Relations), QtGui.QApplication.translate("OsmDockWidget", "Relations", None, QtGui.QApplication.UnicodeUTF8))

