# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/tkralidi/work/foss4g/MetaSearch/MetaSearch/plugin/MetaSearch/ui/maindialog.ui'
#
# Created: Thu Mar 20 21:56:34 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MetaSearchDialog(object):
    def setupUi(self, MetaSearchDialog):
        MetaSearchDialog.setObjectName(_fromUtf8("MetaSearchDialog"))
        MetaSearchDialog.resize(598, 650)
        self.verticalLayout = QtGui.QVBoxLayout(MetaSearchDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(MetaSearchDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabSearch)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tabSearch)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnGlobalBbox = QtGui.QPushButton(self.groupBox)
        self.btnGlobalBbox.setObjectName(_fromUtf8("btnGlobalBbox"))
        self.gridLayout_4.addWidget(self.btnGlobalBbox, 2, 6, 1, 1)
        self.cmbConnectionsSearch = QtGui.QComboBox(self.groupBox)
        self.cmbConnectionsSearch.setObjectName(_fromUtf8("cmbConnectionsSearch"))
        self.gridLayout_4.addWidget(self.cmbConnectionsSearch, 0, 5, 1, 2)
        self.btnCanvasBbox = QtGui.QPushButton(self.groupBox)
        self.btnCanvasBbox.setObjectName(_fromUtf8("btnCanvasBbox"))
        self.gridLayout_4.addWidget(self.btnCanvasBbox, 2, 5, 1, 1)
        self.leWest = QtGui.QLineEdit(self.groupBox)
        self.leWest.setObjectName(_fromUtf8("leWest"))
        self.gridLayout_4.addWidget(self.leWest, 2, 0, 1, 2)
        self.leNorth = QtGui.QLineEdit(self.groupBox)
        self.leNorth.setObjectName(_fromUtf8("leNorth"))
        self.gridLayout_4.addWidget(self.leNorth, 2, 4, 1, 1)
        self.spnRecords = QtGui.QSpinBox(self.groupBox)
        self.spnRecords.setObjectName(_fromUtf8("spnRecords"))
        self.gridLayout_4.addWidget(self.spnRecords, 3, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 3, 6, 1, 1)
        self.btnSearch = QtGui.QPushButton(self.groupBox)
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.gridLayout_4.addWidget(self.btnSearch, 3, 0, 1, 5)
        self.leSouth = QtGui.QLineEdit(self.groupBox)
        self.leSouth.setObjectName(_fromUtf8("leSouth"))
        self.gridLayout_4.addWidget(self.leSouth, 2, 2, 1, 1)
        self.leEast = QtGui.QLineEdit(self.groupBox)
        self.leEast.setObjectName(_fromUtf8("leEast"))
        self.gridLayout_4.addWidget(self.leEast, 2, 3, 1, 1)
        self.leKeywords = QtGui.QLineEdit(self.groupBox)
        self.leKeywords.setObjectName(_fromUtf8("leKeywords"))
        self.gridLayout_4.addWidget(self.leKeywords, 0, 2, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tabSearch)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnNext = QtGui.QPushButton(self.groupBox_2)
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.gridLayout_5.addWidget(self.btnNext, 2, 2, 1, 1)
        self.btnFirst = QtGui.QPushButton(self.groupBox_2)
        self.btnFirst.setObjectName(_fromUtf8("btnFirst"))
        self.gridLayout_5.addWidget(self.btnFirst, 2, 0, 1, 1)
        self.btnAddToWcs = QtGui.QPushButton(self.groupBox_2)
        self.btnAddToWcs.setObjectName(_fromUtf8("btnAddToWcs"))
        self.gridLayout_5.addWidget(self.btnAddToWcs, 6, 2, 1, 1)
        self.btnAddToWms = QtGui.QPushButton(self.groupBox_2)
        self.btnAddToWms.setObjectName(_fromUtf8("btnAddToWms"))
        self.gridLayout_5.addWidget(self.btnAddToWms, 6, 0, 1, 1)
        self.textAbstract = QtGui.QTextEdit(self.groupBox_2)
        self.textAbstract.setObjectName(_fromUtf8("textAbstract"))
        self.gridLayout_5.addWidget(self.textAbstract, 4, 0, 1, 5)
        self.btnPrev = QtGui.QPushButton(self.groupBox_2)
        self.btnPrev.setObjectName(_fromUtf8("btnPrev"))
        self.gridLayout_5.addWidget(self.btnPrev, 2, 1, 1, 1)
        self.btnAddToWfs = QtGui.QPushButton(self.groupBox_2)
        self.btnAddToWfs.setObjectName(_fromUtf8("btnAddToWfs"))
        self.gridLayout_5.addWidget(self.btnAddToWfs, 6, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 3, 0, 1, 2)
        self.lblResults = QtGui.QLabel(self.groupBox_2)
        self.lblResults.setText(_fromUtf8(""))
        self.lblResults.setObjectName(_fromUtf8("lblResults"))
        self.gridLayout_5.addWidget(self.lblResults, 0, 0, 1, 3)
        self.treeRecords = QtGui.QTreeWidget(self.groupBox_2)
        self.treeRecords.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeRecords.setAlternatingRowColors(True)
        self.treeRecords.setRootIsDecorated(False)
        self.treeRecords.setItemsExpandable(False)
        self.treeRecords.setAllColumnsShowFocus(True)
        self.treeRecords.setObjectName(_fromUtf8("treeRecords"))
        self.treeRecords.header().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.treeRecords, 1, 0, 1, 5)
        self.btnShowXml = QtGui.QPushButton(self.groupBox_2)
        self.btnShowXml.setObjectName(_fromUtf8("btnShowXml"))
        self.gridLayout_5.addWidget(self.btnShowXml, 0, 3, 1, 2)
        self.btnLast = QtGui.QPushButton(self.groupBox_2)
        self.btnLast.setObjectName(_fromUtf8("btnLast"))
        self.gridLayout_5.addWidget(self.btnLast, 2, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.tabServers = QtGui.QWidget()
        self.tabServers.setObjectName(_fromUtf8("tabServers"))
        self.gridLayout = QtGui.QGridLayout(self.tabServers)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbConnectionsServices = QtGui.QComboBox(self.tabServers)
        self.cmbConnectionsServices.setObjectName(_fromUtf8("cmbConnectionsServices"))
        self.gridLayout.addWidget(self.cmbConnectionsServices, 0, 0, 1, 5)
        self.btnServerInfo = QtGui.QPushButton(self.tabServers)
        self.btnServerInfo.setObjectName(_fromUtf8("btnServerInfo"))
        self.gridLayout.addWidget(self.btnServerInfo, 1, 0, 1, 1)
        self.btnCapabilities = QtGui.QPushButton(self.tabServers)
        self.btnCapabilities.setObjectName(_fromUtf8("btnCapabilities"))
        self.gridLayout.addWidget(self.btnCapabilities, 1, 1, 1, 2)
        self.btnNew = QtGui.QPushButton(self.tabServers)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.gridLayout.addWidget(self.btnNew, 2, 0, 1, 1)
        self.btnEdit = QtGui.QPushButton(self.tabServers)
        self.btnEdit.setObjectName(_fromUtf8("btnEdit"))
        self.gridLayout.addWidget(self.btnEdit, 2, 1, 1, 1)
        self.btnDelete = QtGui.QPushButton(self.tabServers)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.gridLayout.addWidget(self.btnDelete, 2, 2, 1, 1)
        self.btnSave = QtGui.QPushButton(self.tabServers)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.gridLayout.addWidget(self.btnSave, 2, 4, 1, 1)
        self.textMetadata = QtGui.QTextBrowser(self.tabServers)
        self.textMetadata.setOpenExternalLinks(True)
        self.textMetadata.setObjectName(_fromUtf8("textMetadata"))
        self.gridLayout.addWidget(self.textMetadata, 3, 0, 1, 5)
        self.btnAddDefault = QtGui.QPushButton(self.tabServers)
        self.btnAddDefault.setObjectName(_fromUtf8("btnAddDefault"))
        self.gridLayout.addWidget(self.btnAddDefault, 1, 3, 1, 2)
        self.btnLoad = QtGui.QPushButton(self.tabServers)
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.gridLayout.addWidget(self.btnLoad, 2, 3, 1, 1)
        self.tabWidget.addTab(self.tabServers, _fromUtf8(""))
        self.tabSettings = QtGui.QWidget()
        self.tabSettings.setObjectName(_fromUtf8("tabSettings"))
        self.saveStrategyGroup = QtGui.QGroupBox(self.tabSettings)
        self.saveStrategyGroup.setGeometry(QtCore.QRect(10, 10, 558, 548))
        self.saveStrategyGroup.setObjectName(_fromUtf8("saveStrategyGroup"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.saveStrategyGroup)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblSaveStrategy = QtGui.QLabel(self.saveStrategyGroup)
        self.lblSaveStrategy.setObjectName(_fromUtf8("lblSaveStrategy"))
        self.verticalLayout_3.addWidget(self.lblSaveStrategy)
        self.radioTitleAsk = QtGui.QRadioButton(self.saveStrategyGroup)
        self.radioTitleAsk.setChecked(True)
        self.radioTitleAsk.setObjectName(_fromUtf8("radioTitleAsk"))
        self.verticalLayout_3.addWidget(self.radioTitleAsk)
        self.radioTitleNoAsk = QtGui.QRadioButton(self.saveStrategyGroup)
        self.radioTitleNoAsk.setObjectName(_fromUtf8("radioTitleNoAsk"))
        self.verticalLayout_3.addWidget(self.radioTitleNoAsk)
        self.radioTempName = QtGui.QRadioButton(self.saveStrategyGroup)
        self.radioTempName.setObjectName(_fromUtf8("radioTempName"))
        self.verticalLayout_3.addWidget(self.radioTempName)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.tabSettings, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(MetaSearchDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MetaSearchDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MetaSearchDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MetaSearchDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MetaSearchDialog)

    def retranslateUi(self, MetaSearchDialog):
        MetaSearchDialog.setWindowTitle(QtGui.QApplication.translate("MetaSearchDialog", "MetaSearch", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MetaSearchDialog", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.btnGlobalBbox.setText(QtGui.QApplication.translate("MetaSearchDialog", "Set global", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCanvasBbox.setText(QtGui.QApplication.translate("MetaSearchDialog", "Map extent", None, QtGui.QApplication.UnicodeUTF8))
        self.leWest.setText(QtGui.QApplication.translate("MetaSearchDialog", "-180", None, QtGui.QApplication.UnicodeUTF8))
        self.leNorth.setText(QtGui.QApplication.translate("MetaSearchDialog", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MetaSearchDialog", "Records", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSearch.setText(QtGui.QApplication.translate("MetaSearchDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.leSouth.setText(QtGui.QApplication.translate("MetaSearchDialog", "-90", None, QtGui.QApplication.UnicodeUTF8))
        self.leEast.setText(QtGui.QApplication.translate("MetaSearchDialog", "180", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MetaSearchDialog", "        From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MetaSearchDialog", "Keywords", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MetaSearchDialog", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNext.setText(QtGui.QApplication.translate("MetaSearchDialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFirst.setText(QtGui.QApplication.translate("MetaSearchDialog", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddToWcs.setText(QtGui.QApplication.translate("MetaSearchDialog", "Add WCS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddToWms.setText(QtGui.QApplication.translate("MetaSearchDialog", "Add WMS/WMTS", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPrev.setText(QtGui.QApplication.translate("MetaSearchDialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddToWfs.setText(QtGui.QApplication.translate("MetaSearchDialog", "Add WFS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MetaSearchDialog", "Abstract", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRecords.setToolTip(QtGui.QApplication.translate("MetaSearchDialog", "Double click to see full record information", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRecords.setSortingEnabled(True)
        self.treeRecords.headerItem().setText(0, QtGui.QApplication.translate("MetaSearchDialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRecords.headerItem().setText(1, QtGui.QApplication.translate("MetaSearchDialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowXml.setText(QtGui.QApplication.translate("MetaSearchDialog", "View search results as XML", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLast.setText(QtGui.QApplication.translate("MetaSearchDialog", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), QtGui.QApplication.translate("MetaSearchDialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.btnServerInfo.setText(QtGui.QApplication.translate("MetaSearchDialog", "Service info", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCapabilities.setText(QtGui.QApplication.translate("MetaSearchDialog", "GetCapabilities response", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNew.setText(QtGui.QApplication.translate("MetaSearchDialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEdit.setText(QtGui.QApplication.translate("MetaSearchDialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("MetaSearchDialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("MetaSearchDialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddDefault.setText(QtGui.QApplication.translate("MetaSearchDialog", "Add default services", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("MetaSearchDialog", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabServers), QtGui.QApplication.translate("MetaSearchDialog", "Services", None, QtGui.QApplication.UnicodeUTF8))
        self.saveStrategyGroup.setTitle(QtGui.QApplication.translate("MetaSearchDialog", "Connection naming", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSaveStrategy.setText(QtGui.QApplication.translate("MetaSearchDialog", "When saving the connection of an OWS service", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTitleAsk.setText(QtGui.QApplication.translate("MetaSearchDialog", "Use the OWS Service Title and ask before overwriting", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTitleNoAsk.setText(QtGui.QApplication.translate("MetaSearchDialog", "Use the OWS Service Title and always overwrite if already available", None, QtGui.QApplication.UnicodeUTF8))
        self.radioTempName.setText(QtGui.QApplication.translate("MetaSearchDialog", "Use a temporary name, which you can change later", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), QtGui.QApplication.translate("MetaSearchDialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))

