# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmVisual.ui'
#
# Created: Tue May 26 18:55:54 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(404, 485)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.vboxlayout.addWidget(self.label_3)
        self.inShape = QtGui.QComboBox(Dialog)
        self.inShape.setObjectName("inShape")
        self.vboxlayout.addWidget(self.inShape)
        self.gridLayout.addLayout(self.vboxlayout, 0, 0, 1, 2)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.vboxlayout1.addWidget(self.label)
        self.cmbField = QtGui.QComboBox(Dialog)
        self.cmbField.setObjectName("cmbField")
        self.vboxlayout1.addWidget(self.cmbField)
        self.gridLayout.addLayout(self.vboxlayout1, 4, 0, 1, 2)
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.vboxlayout2.addWidget(self.label_2)
        self.lstUnique = QtGui.QListWidget(Dialog)
        self.lstUnique.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lstUnique.setProperty("showDropIndicator", QtCore.QVariant(False))
        self.lstUnique.setAlternatingRowColors(True)
        self.lstUnique.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lstUnique.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lstUnique.setSelectionRectVisible(True)
        self.lstUnique.setObjectName("lstUnique")
        self.vboxlayout2.addWidget(self.lstUnique)
        self.gridLayout.addLayout(self.vboxlayout2, 5, 0, 1, 2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.hboxlayout.addWidget(self.label_4)
        self.lstCount = QtGui.QLineEdit(Dialog)
        self.lstCount.setReadOnly(True)
        self.lstCount.setObjectName("lstCount")
        self.hboxlayout.addWidget(self.lstCount)
        self.gridLayout.addLayout(self.hboxlayout, 6, 0, 1, 2)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", QtCore.QVariant(24))
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 7, 0, 1, 1)
        self.buttonBox_2 = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.gridLayout.addWidget(self.buttonBox_2, 7, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.useSelected = QtGui.QCheckBox(Dialog)
        self.useSelected.setObjectName("useSelected")
        self.verticalLayout.addWidget(self.useSelected)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL("rejected()"), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "List Unique Values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Input Vector Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Target field", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Unique values list", None, QtGui.QApplication.UnicodeUTF8))
        self.lstUnique.setSortingEnabled(True)
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Unique value count", None, QtGui.QApplication.UnicodeUTF8))
        self.useSelected.setText(QtGui.QApplication.translate("Dialog", "Use only selected features", None, QtGui.QApplication.UnicodeUTF8))

