# The following has been generated automatically from src/analysis/raster/qgskde.h
QgsKernelDensityEstimation.KernelQuartic = QgsKernelDensityEstimation.KernelShape.KernelQuartic
QgsKernelDensityEstimation.KernelTriangular = QgsKernelDensityEstimation.KernelShape.KernelTriangular
QgsKernelDensityEstimation.KernelUniform = QgsKernelDensityEstimation.KernelShape.KernelUniform
QgsKernelDensityEstimation.KernelTriweight = QgsKernelDensityEstimation.KernelShape.KernelTriweight
QgsKernelDensityEstimation.KernelEpanechnikov = QgsKernelDensityEstimation.KernelShape.KernelEpanechnikov
QgsKernelDensityEstimation.OutputRaw = QgsKernelDensityEstimation.OutputValues.OutputRaw
QgsKernelDensityEstimation.OutputScaled = QgsKernelDensityEstimation.OutputValues.OutputScaled
QgsKernelDensityEstimation.Success = QgsKernelDensityEstimation.Result.Success
QgsKernelDensityEstimation.DriverError = QgsKernelDensityEstimation.Result.DriverError
QgsKernelDensityEstimation.InvalidParameters = QgsKernelDensityEstimation.Result.InvalidParameters
QgsKernelDensityEstimation.FileCreationError = QgsKernelDensityEstimation.Result.FileCreationError
QgsKernelDensityEstimation.RasterIoError = QgsKernelDensityEstimation.Result.RasterIoError
