/***************************************************************************
  qgsbabelformatregistry.cpp
   -------------------
  begin                : July 2021
  copyright            : (C) 2021 by Nyall Dawson
  email                : nyall dot dawson at gmail dot com
***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#include "qgsbabelformatregistry.h"

#include "qgsbabelformat.h"
#include "qgsbabelgpsdevice.h"
#include "qgsexception.h"
#include "qgslogger.h"

#include <QRegularExpression>
#include <QString>

const QgsSettingsEntryString *QgsBabelFormatRegistry::settingsBabelWptDownload = new QgsSettingsEntryString( u"wptdownload"_s, sTreeBabelDevices );

const QgsSettingsEntryString *QgsBabelFormatRegistry::settingsBabelWptUpload = new QgsSettingsEntryString( u"wptupload"_s, sTreeBabelDevices );

const QgsSettingsEntryString *QgsBabelFormatRegistry::settingsBabelRteDownload = new QgsSettingsEntryString( u"rtedownload"_s, sTreeBabelDevices );

const QgsSettingsEntryString *QgsBabelFormatRegistry::settingsBabelRteUpload = new QgsSettingsEntryString( u"rteupload"_s, sTreeBabelDevices );

const QgsSettingsEntryString *QgsBabelFormatRegistry::settingsBabelTrkDownload = new QgsSettingsEntryString( u"trkdownload"_s, sTreeBabelDevices );

const QgsSettingsEntryString *QgsBabelFormatRegistry::settingsBabelTrkUpload = new QgsSettingsEntryString( u"trkupload"_s, sTreeBabelDevices );

QgsBabelFormatRegistry::QgsBabelFormatRegistry()
{
  //
  // this list is automatically generated by scripts/dump_babel_formats.py
  //
  mImporters[u"alantrl"_s] = new QgsBabelSimpleImportFormat( u"alantrl"_s, u"Alan Map500 tracklogs (.trl)"_s, Qgis::BabelFormatCapability::Tracks, {u"trl"_s} );
  mImporters[u"alanwpr"_s] = new QgsBabelSimpleImportFormat( u"alanwpr"_s, u"Alan Map500 waypoints and routes (.wpr)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes, {u"wpr"_s} );
  mImporters[u"an1"_s] = new QgsBabelSimpleImportFormat( u"an1"_s, u"DeLorme .an1 (drawing) file"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes, {u"an1"_s} );
  mImporters[u"arc"_s] = new QgsBabelSimpleImportFormat( u"arc"_s, u"GPSBabel arc filter file"_s, Qgis::BabelFormatCapability::Waypoints, {u"txt"_s} );
  mImporters[u"bcr"_s] = new QgsBabelSimpleImportFormat( u"bcr"_s, u"Motorrad Routenplaner (Map&Guide) .bcr files"_s, Qgis::BabelFormatCapability::Routes, {u"bcr"_s} );
  mImporters[u"bushnell"_s] = new QgsBabelSimpleImportFormat( u"bushnell"_s, u"Bushnell GPS Waypoint file"_s, Qgis::BabelFormatCapability::Waypoints, {u"wpt"_s} );
  mImporters[u"bushnell_trl"_s] = new QgsBabelSimpleImportFormat( u"bushnell_trl"_s, u"Bushnell GPS Trail file"_s, Qgis::BabelFormatCapability::Tracks, {u"trl"_s} );
  mImporters[u"cambridge"_s] = new QgsBabelSimpleImportFormat( u"cambridge"_s, u"Cambridge/Winpilot glider software"_s, Qgis::BabelFormatCapability::Waypoints, {u"dat"_s} );
  mImporters[u"compegps"_s] = new QgsBabelSimpleImportFormat( u"compegps"_s, u"CompeGPS data files (.wpt/.trk/.rte)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"cst"_s] = new QgsBabelSimpleImportFormat( u"cst"_s, u"CarteSurTable data file"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"cst"_s} );
  mImporters[u"csv"_s] = new QgsBabelSimpleImportFormat( u"csv"_s, u"Comma separated values"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"cup"_s] = new QgsBabelSimpleImportFormat( u"cup"_s, u"See You flight analysis data"_s, Qgis::BabelFormatCapability::Waypoints, {u"cup"_s} );
  mImporters[u"destinator_itn"_s] = new QgsBabelSimpleImportFormat( u"destinator_itn"_s, u"Destinator Itineraries (.dat)"_s, Qgis::BabelFormatCapability::Routes, {u"dat"_s} );
  mImporters[u"destinator_poi"_s] = new QgsBabelSimpleImportFormat( u"destinator_poi"_s, u"Destinator Points of Interest (.dat)"_s, Qgis::BabelFormatCapability::Waypoints, {u"dat"_s} );
  mImporters[u"destinator_trl"_s] = new QgsBabelSimpleImportFormat( u"destinator_trl"_s, u"Destinator TrackLogs (.dat)"_s, Qgis::BabelFormatCapability::Tracks, {u"dat"_s} );
  mImporters[u"dmtlog"_s] = new QgsBabelSimpleImportFormat( u"dmtlog"_s, u"TrackLogs digital mapping (.trl)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"trl"_s} );
  mImporters[u"dna"_s] = new QgsBabelSimpleImportFormat( u"dna"_s, u"Navitrak DNA marker format"_s, Qgis::BabelFormatCapability::Waypoints, {u"dna"_s} );
  mImporters[u"easygps"_s] = new QgsBabelSimpleImportFormat( u"easygps"_s, u"EasyGPS binary format"_s, Qgis::BabelFormatCapability::Waypoints, {u"loc"_s} );
  mImporters[u"energympro"_s] = new QgsBabelSimpleImportFormat( u"energympro"_s, u"Energympro GPS training watch"_s, Qgis::BabelFormatCapability::Tracks, {u"cpo"_s} );
  mImporters[u"enigma"_s] = new QgsBabelSimpleImportFormat( u"enigma"_s, u"Enigma binary waypoint file (.ert)"_s, Qgis::BabelFormatCapability::Routes, {u"ert"_s} );
  mImporters[u"exif"_s] = new QgsBabelSimpleImportFormat( u"exif"_s, u"Embedded Exif-GPS data (.jpg)"_s, Qgis::BabelFormatCapability::Waypoints, {u"jpg"_s} );
  mImporters[u"f90g"_s] = new QgsBabelSimpleImportFormat( u"f90g"_s, u"F90G Automobile DVR GPS log file"_s, Qgis::BabelFormatCapability::Tracks, {u"map"_s} );
  mImporters[u"flysight"_s] = new QgsBabelSimpleImportFormat( u"flysight"_s, u"FlySight GPS File"_s, Qgis::BabelFormatCapability::Waypoints, {u"csv"_s} );
  mImporters[u"fugawi"_s] = new QgsBabelSimpleImportFormat( u"fugawi"_s, u"Fugawi"_s, Qgis::BabelFormatCapability::Waypoints, {u"txt"_s} );
  mImporters[u"g7towin"_s] = new QgsBabelSimpleImportFormat( u"g7towin"_s, u"G7ToWin data files (.g7t)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"g7t"_s} );
  mImporters[u"garmin301"_s] = new QgsBabelSimpleImportFormat( u"garmin301"_s, u"Garmin 301 Custom position and heartrate"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"garmin_fit"_s] = new QgsBabelSimpleImportFormat( u"garmin_fit"_s, u"Flexible and Interoperable Data Transfer (FIT) Activity file"_s, Qgis::BabelFormatCapability::Tracks, {u"fit"_s} );
  mImporters[u"garmin_g1000"_s] = new QgsBabelSimpleImportFormat( u"garmin_g1000"_s, u"Garmin G1000 datalog input filter file"_s, Qgis::BabelFormatCapability::Tracks, {u"csv"_s} );
  mImporters[u"garmin_gpi"_s] = new QgsBabelSimpleImportFormat( u"garmin_gpi"_s, u"Garmin Points of Interest (.gpi)"_s, Qgis::BabelFormatCapability::Waypoints, {u"gpi"_s} );
  mImporters[u"garmin_poi"_s] = new QgsBabelSimpleImportFormat( u"garmin_poi"_s, u"Garmin POI database"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"garmin_txt"_s] = new QgsBabelSimpleImportFormat( u"garmin_txt"_s, u"Garmin MapSource - txt (tab delimited)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"txt"_s} );
  mImporters[u"garmin_xt"_s] = new QgsBabelSimpleImportFormat( u"garmin_xt"_s, u"Mobile Garmin XT Track files"_s, Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"gdb"_s] = new QgsBabelSimpleImportFormat( u"gdb"_s, u"Garmin MapSource - gdb"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"gdb"_s} );
  mImporters[u"geo"_s] = new QgsBabelSimpleImportFormat( u"geo"_s, u"Geocaching.com .loc"_s, Qgis::BabelFormatCapability::Waypoints, {u"loc"_s} );
  mImporters[u"geojson"_s] = new QgsBabelSimpleImportFormat( u"geojson"_s, u"GeoJson"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"json"_s} );
  mImporters[u"geonet"_s] = new QgsBabelSimpleImportFormat( u"geonet"_s, u"GEOnet Names Server (GNS)"_s, Qgis::BabelFormatCapability::Waypoints, {u"txt"_s} );
  mImporters[u"ggv_bin"_s] = new QgsBabelSimpleImportFormat( u"ggv_bin"_s, u"Geogrid-Viewer binary overlay file (.ovl)"_s, Qgis::BabelFormatCapability::Tracks, {u"ovl"_s} );
  mImporters[u"ggv_log"_s] = new QgsBabelSimpleImportFormat( u"ggv_log"_s, u"Geogrid-Viewer tracklogs (.log)"_s, Qgis::BabelFormatCapability::Tracks, {u"log"_s} );
  mImporters[u"ggv_ovl"_s] = new QgsBabelSimpleImportFormat( u"ggv_ovl"_s, u"Geogrid-Viewer ascii overlay file (.ovl)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"ovl"_s} );
  mImporters[u"glogbook"_s] = new QgsBabelSimpleImportFormat( u"glogbook"_s, u"Garmin Logbook XML"_s, Qgis::BabelFormatCapability::Tracks, {u"xml"_s} );
  mImporters[u"gnav_trl"_s] = new QgsBabelSimpleImportFormat( u"gnav_trl"_s, u"Google Navigator Tracklines (.trl)"_s, Qgis::BabelFormatCapability::Tracks, {u"trl"_s} );
  mImporters[u"googledir"_s] = new QgsBabelSimpleImportFormat( u"googledir"_s, u"Google Directions XML"_s, Qgis::BabelFormatCapability::Tracks, {u"xml"_s} );
  mImporters[u"gopal"_s] = new QgsBabelSimpleImportFormat( u"gopal"_s, u"GoPal GPS track log (.trk)"_s, Qgis::BabelFormatCapability::Tracks, {u"trk"_s} );
  mImporters[u"gpl"_s] = new QgsBabelSimpleImportFormat( u"gpl"_s, u"DeLorme GPL"_s, Qgis::BabelFormatCapability::Tracks, {u"gpl"_s} );
  mImporters[u"gpsdrive"_s] = new QgsBabelSimpleImportFormat( u"gpsdrive"_s, u"GpsDrive Format"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"gpsdrivetrack"_s] = new QgsBabelSimpleImportFormat( u"gpsdrivetrack"_s, u"GpsDrive Format for Tracks"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"gpsman"_s] = new QgsBabelSimpleImportFormat( u"gpsman"_s, u"GPSman"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"gpsutil"_s] = new QgsBabelSimpleImportFormat( u"gpsutil"_s, u"gpsutil"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"gpx"_s] = new QgsBabelSimpleImportFormat( u"gpx"_s, u"GPX XML"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"gpx"_s} );
  mImporters[u"gtm"_s] = new QgsBabelSimpleImportFormat( u"gtm"_s, u"GPS TrackMaker"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"gtm"_s} );
  mImporters[u"gtrnctr"_s] = new QgsBabelSimpleImportFormat( u"gtrnctr"_s, u"Garmin Training Center (.tcx/.crs/.hst/.xml)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"tcx"_s, u"crs"_s, u"hst"_s, u"xml"_s} );
  mImporters[u"hiketech"_s] = new QgsBabelSimpleImportFormat( u"hiketech"_s, u"HikeTech"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"gps"_s} );
  mImporters[u"holux"_s] = new QgsBabelSimpleImportFormat( u"holux"_s, u"Holux (gm-100) .wpo Format"_s, Qgis::BabelFormatCapability::Waypoints, {u"wpo"_s} );
  mImporters[u"humminbird"_s] = new QgsBabelSimpleImportFormat( u"humminbird"_s, u"Humminbird waypoints and routes (.hwr)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"hwr"_s} );
  mImporters[u"humminbird_ht"_s] = new QgsBabelSimpleImportFormat( u"humminbird_ht"_s, u"Humminbird tracks (.ht)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"ht"_s} );
  mImporters[u"iblue747"_s] = new QgsBabelSimpleImportFormat( u"iblue747"_s, u"Data Logger iBlue747 csv"_s, Qgis::BabelFormatCapability::Tracks, {u"csv"_s} );
  mImporters[u"iblue757"_s] = new QgsBabelSimpleImportFormat( u"iblue757"_s, u"Data Logger iBlue757 csv"_s, Qgis::BabelFormatCapability::Tracks, {u"csv"_s} );
  mImporters[u"igc"_s] = new QgsBabelSimpleImportFormat( u"igc"_s, u"FAI/IGC Flight Recorder Data Format"_s, Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"ignrando"_s] = new QgsBabelSimpleImportFormat( u"ignrando"_s, u"IGN Rando track files"_s, Qgis::BabelFormatCapability::Tracks, {u"rdn"_s} );
  mImporters[u"igo2008_poi"_s] = new QgsBabelSimpleImportFormat( u"igo2008_poi"_s, u"iGO2008 points of interest (.upoi)"_s, Qgis::BabelFormatCapability::Waypoints, {u"upoi"_s} );
  mImporters[u"igo8"_s] = new QgsBabelSimpleImportFormat( u"igo8"_s, u"IGO8 .trk"_s, Qgis::BabelFormatCapability::Tracks, {u"trk"_s} );
  mImporters[u"igoprimo_poi"_s] = new QgsBabelSimpleImportFormat( u"igoprimo_poi"_s, u"iGo Primo points of interest (.upoi)"_s, Qgis::BabelFormatCapability::Waypoints, {u"upoi"_s} );
  mImporters[u"ik3d"_s] = new QgsBabelSimpleImportFormat( u"ik3d"_s, u"MagicMaps IK3D project file (.ikt)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"ikt"_s} );
  mImporters[u"itracku-bin"_s] = new QgsBabelSimpleImportFormat( u"itracku-bin"_s, u"XAiOX iTrackU Logger Binary File Format"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"bin"_s} );
  mImporters[u"jogmap"_s] = new QgsBabelSimpleImportFormat( u"jogmap"_s, u"Jogmap.de XML format"_s, Qgis::BabelFormatCapability::Tracks, {u"xml"_s} );
  mImporters[u"jtr"_s] = new QgsBabelSimpleImportFormat( u"jtr"_s, u"Jelbert GeoTagger data file"_s, Qgis::BabelFormatCapability::Tracks, {u"jtr"_s} );
  mImporters[u"kml"_s] = new QgsBabelSimpleImportFormat( u"kml"_s, u"Google Earth (Keyhole) Markup Language"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"kml"_s} );
  mImporters[u"kompass_tk"_s] = new QgsBabelSimpleImportFormat( u"kompass_tk"_s, u"Kompass (DAV) Track (.tk)"_s, Qgis::BabelFormatCapability::Tracks, {u"wp"_s} );
  mImporters[u"kompass_wp"_s] = new QgsBabelSimpleImportFormat( u"kompass_wp"_s, u"Kompass (DAV) Waypoints (.wp)"_s, Qgis::BabelFormatCapability::Waypoints, {u"wp"_s} );
  mImporters[u"land_air_sea"_s] = new QgsBabelSimpleImportFormat( u"land_air_sea"_s, u"GPS Tracking Key Pro text"_s, Qgis::BabelFormatCapability::Tracks, {u"txt"_s} );
  mImporters[u"lmx"_s] = new QgsBabelSimpleImportFormat( u"lmx"_s, u"Nokia Landmark Exchange"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"lowranceusr"_s] = new QgsBabelSimpleImportFormat( u"lowranceusr"_s, u"Lowrance USR"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"usr"_s} );
  mImporters[u"m241-bin"_s] = new QgsBabelSimpleImportFormat( u"m241-bin"_s, u"Holux M-241 (MTK based) Binary File Format"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"bin"_s} );
  mImporters[u"magellan"_s] = new QgsBabelSimpleImportFormat( u"magellan"_s, u"Magellan SD files (as for Meridian)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"magellanx"_s] = new QgsBabelSimpleImportFormat( u"magellanx"_s, u"Magellan SD files (as for eXplorist)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"upt"_s} );
  mImporters[u"maggeo"_s] = new QgsBabelSimpleImportFormat( u"maggeo"_s, u"Magellan Explorist Geocaching"_s, Qgis::BabelFormatCapability::Waypoints, {u"gs"_s} );
  mImporters[u"mainnav"_s] = new QgsBabelSimpleImportFormat( u"mainnav"_s, u"Mainnav"_s, Qgis::BabelFormatCapability::Tracks, {u"nav"_s} );
  mImporters[u"mapasia_tr7"_s] = new QgsBabelSimpleImportFormat( u"mapasia_tr7"_s, u"MapAsia track file (.tr7)"_s, Qgis::BabelFormatCapability::Tracks, {u"tr7"_s} );
  mImporters[u"mapbar"_s] = new QgsBabelSimpleImportFormat( u"mapbar"_s, u"Mapbar (China) navigation track for Sonim Xp3300"_s, Qgis::BabelFormatCapability::Tracks, {u"trk"_s} );
  mImporters[u"mapconverter"_s] = new QgsBabelSimpleImportFormat( u"mapconverter"_s, u"Mapopolis.com Mapconverter CSV"_s, Qgis::BabelFormatCapability::Waypoints, {u"txt"_s} );
  mImporters[u"mapfactor"_s] = new QgsBabelSimpleImportFormat( u"mapfactor"_s, u"Mapfactor Navigator"_s, Qgis::BabelFormatCapability::Waypoints, {u"xml"_s} );
  mImporters[u"mapsend"_s] = new QgsBabelSimpleImportFormat( u"mapsend"_s, u"Magellan Mapsend"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"mmo"_s] = new QgsBabelSimpleImportFormat( u"mmo"_s, u"Memory-Map Navigator overlay files (.mmo)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"mmo"_s} );
  mImporters[u"motoactv"_s] = new QgsBabelSimpleImportFormat( u"motoactv"_s, u"Motoactiv CSV"_s, Qgis::BabelFormatCapability::Waypoints, {u"csv"_s} );
  mImporters[u"mtk-bin"_s] = new QgsBabelSimpleImportFormat( u"mtk-bin"_s, u"MTK Logger (iBlue 747,...) Binary File Format"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"bin"_s} );
  mImporters[u"mtk_locus"_s] = new QgsBabelSimpleImportFormat( u"mtk_locus"_s, u"MediaTek Locus"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"mxf"_s] = new QgsBabelSimpleImportFormat( u"mxf"_s, u"MapTech Exchange Format"_s, Qgis::BabelFormatCapability::Waypoints, {u"mxf"_s} );
  mImporters[u"mynav"_s] = new QgsBabelSimpleImportFormat( u"mynav"_s, u"MyNav TRC format"_s, Qgis::BabelFormatCapability::Tracks, {u"trc"_s} );
  mImporters[u"navicache"_s] = new QgsBabelSimpleImportFormat( u"navicache"_s, u"Navicache.com XML"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"navigonwpt"_s] = new QgsBabelSimpleImportFormat( u"navigonwpt"_s, u"Navigon Waypoints"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"naviguide"_s] = new QgsBabelSimpleImportFormat( u"naviguide"_s, u"Naviguide binary route file (.twl)"_s, Qgis::BabelFormatCapability::Waypoints, {u"twl"_s} );
  mImporters[u"navitel_trk"_s] = new QgsBabelSimpleImportFormat( u"navitel_trk"_s, u"Navitel binary track (.bin)"_s, Qgis::BabelFormatCapability::Tracks, {u"bin"_s} );
  mImporters[u"netstumbler"_s] = new QgsBabelSimpleImportFormat( u"netstumbler"_s, u"NetStumbler Summary File (text)"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"nima"_s] = new QgsBabelSimpleImportFormat( u"nima"_s, u"NIMA/GNIS Geographic Names File"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"nmea"_s] = new QgsBabelSimpleImportFormat( u"nmea"_s, u"NMEA 0183 sentences"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"nmn4"_s] = new QgsBabelSimpleImportFormat( u"nmn4"_s, u"Navigon Mobile Navigator .rte files"_s, Qgis::BabelFormatCapability::Routes, {u"rte"_s} );
  mImporters[u"openoffice"_s] = new QgsBabelSimpleImportFormat( u"openoffice"_s, u"Tab delimited fields useful for OpenOffice"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"osm"_s] = new QgsBabelSimpleImportFormat( u"osm"_s, u"OpenStreetMap data files"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes, {u"osm"_s} );
  mImporters[u"ozi"_s] = new QgsBabelSimpleImportFormat( u"ozi"_s, u"OziExplorer"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"pcx"_s] = new QgsBabelSimpleImportFormat( u"pcx"_s, u"Garmin PCX5"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"pcx"_s} );
  mImporters[u"pocketfms_bc"_s] = new QgsBabelSimpleImportFormat( u"pocketfms_bc"_s, u"PocketFMS breadcrumbs"_s, Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"pocketfms_fp"_s] = new QgsBabelSimpleImportFormat( u"pocketfms_fp"_s, u"PocketFMS flightplan (.xml)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes, {u"xml"_s} );
  mImporters[u"pocketfms_wp"_s] = new QgsBabelSimpleImportFormat( u"pocketfms_wp"_s, u"PocketFMS waypoints (.txt)"_s, Qgis::BabelFormatCapability::Waypoints, {u"txt"_s} );
  mImporters[u"qstarz_bl-1000"_s] = new QgsBabelSimpleImportFormat( u"qstarz_bl-1000"_s, u"Qstarz BL-1000"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"raymarine"_s] = new QgsBabelSimpleImportFormat( u"raymarine"_s, u"Raymarine Waypoint File (.rwf)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes, {u"rwf"_s} );
  mImporters[u"ricoh"_s] = new QgsBabelSimpleImportFormat( u"ricoh"_s, u"Ricoh GPS Log File"_s, Qgis::BabelFormatCapability::Tracks, {u"log"_s} );
  mImporters[u"s_and_t"_s] = new QgsBabelSimpleImportFormat( u"s_and_t"_s, u"Microsoft Streets and Trips 2002-2007"_s, Qgis::BabelFormatCapability::Waypoints, {u"txt"_s} );
  mImporters[u"saplus"_s] = new QgsBabelSimpleImportFormat( u"saplus"_s, u"DeLorme Street Atlas Plus"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"saroute"_s] = new QgsBabelSimpleImportFormat( u"saroute"_s, u"DeLorme Street Atlas Route"_s, Qgis::BabelFormatCapability::Tracks, {u"anr"_s} );
  mImporters[u"sbn"_s] = new QgsBabelSimpleImportFormat( u"sbn"_s, u"NaviGPS GT-31/BGT-31 SiRF binary logfile (.sbn)"_s, Qgis::BabelFormatCapability::Tracks, {u"sbn"_s} );
  mImporters[u"sbp"_s] = new QgsBabelSimpleImportFormat( u"sbp"_s, u"NaviGPS GT-31/BGT-31 datalogger (.sbp)"_s, Qgis::BabelFormatCapability::Tracks, {u"sbp"_s} );
  mImporters[u"shape"_s] = new QgsBabelSimpleImportFormat( u"shape"_s, u"ESRI shapefile"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"shp"_s} );
  mImporters[u"skyforce"_s] = new QgsBabelSimpleImportFormat( u"skyforce"_s, u"Skymap / KMD150 ascii files"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"skytraq-bin"_s] = new QgsBabelSimpleImportFormat( u"skytraq-bin"_s, u"SkyTraq Venus based loggers Binary File Format"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"bin"_s} );
  mImporters[u"stmsdf"_s] = new QgsBabelSimpleImportFormat( u"stmsdf"_s, u"Suunto Trek Manager (STM) .sdf files"_s, Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"sdf"_s} );
  mImporters[u"stmwpp"_s] = new QgsBabelSimpleImportFormat( u"stmwpp"_s, u"Suunto Trek Manager (STM) WaypointPlus files"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"txt"_s} );
  mImporters[u"tef"_s] = new QgsBabelSimpleImportFormat( u"tef"_s, u"Map&Guide 'TourExchangeFormat' XML"_s, Qgis::BabelFormatCapability::Routes, {u"xml"_s} );
  mImporters[u"teletype"_s] = new QgsBabelSimpleImportFormat( u"teletype"_s, u"Teletype"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"tiger"_s] = new QgsBabelSimpleImportFormat( u"tiger"_s, u"U.S. Census Bureau Tiger Mapping Service"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"tmpro"_s] = new QgsBabelSimpleImportFormat( u"tmpro"_s, u"TopoMapPro Places File"_s, Qgis::BabelFormatCapability::Waypoints, {u"tmpro"_s} );
  mImporters[u"tomtom"_s] = new QgsBabelSimpleImportFormat( u"tomtom"_s, u"TomTom POI file (.ov2)"_s, Qgis::BabelFormatCapability::Waypoints, {u"ov2"_s} );
  mImporters[u"tomtom_asc"_s] = new QgsBabelSimpleImportFormat( u"tomtom_asc"_s, u"TomTom POI file (.asc)"_s, Qgis::BabelFormatCapability::Waypoints, {u"asc"_s} );
  mImporters[u"tomtom_itn"_s] = new QgsBabelSimpleImportFormat( u"tomtom_itn"_s, u"TomTom Itineraries (.itn)"_s, Qgis::BabelFormatCapability::Routes, {u"itn"_s} );
  mImporters[u"tomtom_itn_places"_s] = new QgsBabelSimpleImportFormat( u"tomtom_itn_places"_s, u"TomTom Places Itineraries (.itn)"_s, Qgis::BabelFormatCapability::Routes, {u"itn"_s} );
  mImporters[u"tpg"_s] = new QgsBabelSimpleImportFormat( u"tpg"_s, u"National Geographic Topo .tpg (waypoints)"_s, Qgis::BabelFormatCapability::Waypoints, {u"tpg"_s} );
  mImporters[u"tpo2"_s] = new QgsBabelSimpleImportFormat( u"tpo2"_s, u"National Geographic Topo 2.x .tpo"_s, Qgis::BabelFormatCapability::Tracks, {u"tpo"_s} );
  mImporters[u"tpo3"_s] = new QgsBabelSimpleImportFormat( u"tpo3"_s, u"National Geographic Topo 3.x/4.x .tpo"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"tpo"_s} );
  mImporters[u"unicsv"_s] = new QgsBabelSimpleImportFormat( u"unicsv"_s, u"Universal csv with field structure in first line"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"v900"_s] = new QgsBabelSimpleImportFormat( u"v900"_s, u"Columbus/Visiontac V900 files (.csv)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"vidaone"_s] = new QgsBabelSimpleImportFormat( u"vidaone"_s, u"VidaOne GPS for Pocket PC (.gpb)"_s, Qgis::BabelFormatCapability::Tracks, {u"gpb"_s} );
  mImporters[u"vitosmt"_s] = new QgsBabelSimpleImportFormat( u"vitosmt"_s, u"Vito Navigator II tracks"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Routes | Qgis::BabelFormatCapability::Tracks, {u"smt"_s} );
  mImporters[u"vitovtt"_s] = new QgsBabelSimpleImportFormat( u"vitovtt"_s, u"Vito SmartMap tracks (.vtt)"_s, Qgis::BabelFormatCapability::Tracks, {u"vtt"_s} );
  mImporters[u"vpl"_s] = new QgsBabelSimpleImportFormat( u"vpl"_s, u"Honda/Acura Navigation System VP Log File Format"_s, Qgis::BabelFormatCapability::Tracks, {} );
  mImporters[u"wbt-bin"_s] = new QgsBabelSimpleImportFormat( u"wbt-bin"_s, u"Wintec WBT-100/200 Binary File Format"_s, Qgis::BabelFormatCapability::Tracks, {u"bin"_s} );
  mImporters[u"wbt-tk1"_s] = new QgsBabelSimpleImportFormat( u"wbt-tk1"_s, u"Wintec WBT-201/G-Rays 2 Binary File Format"_s, Qgis::BabelFormatCapability::Tracks, {u"tk1"_s} );
  mImporters[u"wfff"_s] = new QgsBabelSimpleImportFormat( u"wfff"_s, u"WiFiFoFum 2.0 for PocketPC XML"_s, Qgis::BabelFormatCapability::Waypoints, {u"xml"_s} );
  mImporters[u"wintec_tes"_s] = new QgsBabelSimpleImportFormat( u"wintec_tes"_s, u"Wintec TES file"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"tes"_s} );
  mImporters[u"xmap"_s] = new QgsBabelSimpleImportFormat( u"xmap"_s, u"DeLorme XMap HH Native .WPT"_s, Qgis::BabelFormatCapability::Waypoints, {u"wpt"_s} );
  mImporters[u"xmap2006"_s] = new QgsBabelSimpleImportFormat( u"xmap2006"_s, u"DeLorme XMap/SAHH 2006 Native .TXT"_s, Qgis::BabelFormatCapability::Waypoints, {u"txt"_s} );
  mImporters[u"xmapwpt"_s] = new QgsBabelSimpleImportFormat( u"xmapwpt"_s, u"DeLorme XMat HH Street Atlas USA .WPT (PPC)"_s, Qgis::BabelFormatCapability::Waypoints, {} );
  mImporters[u"xol"_s] = new QgsBabelSimpleImportFormat( u"xol"_s, u"Swiss Map 25/50/100 (.xol)"_s, Qgis::BabelFormatCapability::Waypoints | Qgis::BabelFormatCapability::Tracks, {u"xol"_s} );
  mImporters[u"yahoo"_s] = new QgsBabelSimpleImportFormat( u"yahoo"_s, u"Yahoo Geocode API data"_s, Qgis::BabelFormatCapability::Waypoints, {} );

  reloadFromSettings();
}

QgsBabelFormatRegistry::~QgsBabelFormatRegistry()
{
  qDeleteAll( mImporters );
  qDeleteAll( mDevices );
}

QStringList QgsBabelFormatRegistry::importFormatNames() const
{
  return mImporters.keys();
}

QgsBabelSimpleImportFormat *QgsBabelFormatRegistry::importFormat( const QString &name )
{
  return mImporters.value( name );
}

QgsBabelSimpleImportFormat *QgsBabelFormatRegistry::importFormatByDescription( const QString &description )
{
  for ( auto it = mImporters.constBegin(); it != mImporters.constEnd(); ++it )
  {
    if ( it.value()->description().compare( description, Qt::CaseInsensitive ) == 0 )
      return it.value();

    // also need to test square bracket variant, see logic in importFileFilter()
    const QString descriptionSquareBrackets = it.value()->description().replace( '(', '[' ).replace( ')', ']' );
    if ( descriptionSquareBrackets.compare( description, Qt::CaseInsensitive ) == 0 )
      return it.value();
  }
  return nullptr;
}

QString QgsBabelFormatRegistry::importFileFilter() const
{
  QStringList res;
  QMap< QString, QString > descriptionToString;
  for ( auto it = mImporters.constBegin(); it != mImporters.constEnd(); ++it )
  {
    const QStringList extensions = it.value()->extensions();
    QString fileFilter;
    if ( !extensions.empty() )
    {
      fileFilter = '(';
      for ( const QString &extension : extensions )
        fileFilter.append( u"*.%1"_s.arg( extension ) );
      fileFilter.append( ')' );
    }
    else
    {
      fileFilter = u"(*.*)"_s;
    }

    // we have to replace round brackets from the format description, or they are treated as the filter component!
    const QString description = it.value()->description().replace( '(', '[' ).replace( ')', ']' );

    descriptionToString.insert( description.toLower(), u"%1 %2"_s.arg( description, fileFilter ) );
  }

  // build the list in a sorted order of lowercase description
  for ( auto it = descriptionToString.constBegin(); it != descriptionToString.constEnd(); ++it )
    res << it.value();

  return res.join( ";;"_L1 );
}

QStringList QgsBabelFormatRegistry::deviceNames() const
{
  return mDevices.keys();
}

QgsBabelGpsDeviceFormat *QgsBabelFormatRegistry::deviceFormat( const QString &name )
{
  return mDevices.value( name );
}

QMap<QString, QgsBabelGpsDeviceFormat *> QgsBabelFormatRegistry::devices() const
{
  return mDevices;
}

void QgsBabelFormatRegistry::reloadFromSettings()
{
  qDeleteAll( mDevices );
  mDevices.clear();

  mDevices[u"Garmin serial"_s] =
    new QgsBabelGpsDeviceFormat( u"%babel -w -i garmin -o gpx %in %out"_s,
                                 u"%babel -w -i gpx -o garmin %in %out"_s,
                                 u"%babel -r -i garmin -o gpx %in %out"_s,
                                 u"%babel -r -i gpx -o garmin %in %out"_s,
                                 u"%babel -t -i garmin -o gpx %in %out"_s,
                                 u"%babel -t -i gpx -o garmin %in %out"_s );

  try
  {
    for ( const QString &device : sTreeBabelDevices->items() )
    {
      // don't leak memory if there's already a device with this name...
      delete mDevices.value( device );

      mDevices[device] = new QgsBabelGpsDeviceFormat( settingsBabelWptDownload->value( device ), settingsBabelWptUpload->value( device ),
          settingsBabelRteDownload->value( device ), settingsBabelRteUpload->value( device ),
          settingsBabelTrkDownload->value( device ), settingsBabelTrkUpload->value( device ) );
    }
  }
  catch ( QgsSettingsException &e )
  {
    QgsDebugError( e.what() );
  }
}

