# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgModeler.ui'
#
# Created: Fri Nov 21 13:25:48 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DlgModeler(object):
    def setupUi(self, DlgModeler):
        DlgModeler.setObjectName(_fromUtf8("DlgModeler"))
        DlgModeler.resize(1000, 600)
        self.verticalLayout = QtGui.QVBoxLayout(DlgModeler)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setMargin(9)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnOpen = QtGui.QToolButton(DlgModeler)
        self.btnOpen.setAutoRaise(True)
        self.btnOpen.setObjectName(_fromUtf8("btnOpen"))
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnSave = QtGui.QToolButton(DlgModeler)
        self.btnSave.setAutoRaise(True)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnSaveAs = QtGui.QToolButton(DlgModeler)
        self.btnSaveAs.setAutoRaise(True)
        self.btnSaveAs.setObjectName(_fromUtf8("btnSaveAs"))
        self.horizontalLayout.addWidget(self.btnSaveAs)
        self.line = QtGui.QFrame(DlgModeler)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.btnExportImage = QtGui.QToolButton(DlgModeler)
        self.btnExportImage.setAutoRaise(True)
        self.btnExportImage.setObjectName(_fromUtf8("btnExportImage"))
        self.horizontalLayout.addWidget(self.btnExportImage)
        self.line_2 = QtGui.QFrame(DlgModeler)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.btnEditHelp = QtGui.QToolButton(DlgModeler)
        self.btnEditHelp.setAutoRaise(True)
        self.btnEditHelp.setObjectName(_fromUtf8("btnEditHelp"))
        self.horizontalLayout.addWidget(self.btnEditHelp)
        self.line_3 = QtGui.QFrame(DlgModeler)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.btnRun = QtGui.QToolButton(DlgModeler)
        self.btnRun.setAutoRaise(True)
        self.btnRun.setObjectName(_fromUtf8("btnRun"))
        self.horizontalLayout.addWidget(self.btnRun)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtGui.QSplitter(DlgModeler)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.inputsTree = QtGui.QTreeWidget(self.tab)
        self.inputsTree.setAlternatingRowColors(True)
        self.inputsTree.setObjectName(_fromUtf8("inputsTree"))
        self.inputsTree.headerItem().setText(0, _fromUtf8("1"))
        self.inputsTree.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.inputsTree)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.searchBox = QgsFilterLineEdit(self.tab_2)
        self.searchBox.setObjectName(_fromUtf8("searchBox"))
        self.verticalLayout_3.addWidget(self.searchBox)
        self.algorithmTree = QtGui.QTreeWidget(self.tab_2)
        self.algorithmTree.setAlternatingRowColors(True)
        self.algorithmTree.setObjectName(_fromUtf8("algorithmTree"))
        self.algorithmTree.headerItem().setText(0, _fromUtf8("1"))
        self.algorithmTree.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.algorithmTree)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textName = QtGui.QLineEdit(self.layoutWidget)
        self.textName.setObjectName(_fromUtf8("textName"))
        self.gridLayout.addWidget(self.textName, 0, 0, 1, 1)
        self.textGroup = QtGui.QLineEdit(self.layoutWidget)
        self.textGroup.setObjectName(_fromUtf8("textGroup"))
        self.gridLayout.addWidget(self.textGroup, 0, 1, 1, 1)
        self.view = QtGui.QGraphicsView(self.layoutWidget)
        self.view.setObjectName(_fromUtf8("view"))
        self.gridLayout.addWidget(self.view, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(DlgModeler)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DlgModeler)

    def retranslateUi(self, DlgModeler):
        DlgModeler.setWindowTitle(_translate("DlgModeler", "Processing modeler", None))
        self.btnOpen.setToolTip(_translate("DlgModeler", "Open model", None))
        self.btnOpen.setText(_translate("DlgModeler", "...", None))
        self.btnOpen.setShortcut(_translate("DlgModeler", "Ctrl+O", None))
        self.btnSave.setToolTip(_translate("DlgModeler", "Save", None))
        self.btnSave.setText(_translate("DlgModeler", "...", None))
        self.btnSave.setShortcut(_translate("DlgModeler", "Ctrl+S", None))
        self.btnSaveAs.setToolTip(_translate("DlgModeler", "Save as...", None))
        self.btnSaveAs.setText(_translate("DlgModeler", "...", None))
        self.btnSaveAs.setShortcut(_translate("DlgModeler", "Ctrl+Shift+S", None))
        self.btnExportImage.setToolTip(_translate("DlgModeler", "Export as image", None))
        self.btnExportImage.setText(_translate("DlgModeler", "...", None))
        self.btnEditHelp.setToolTip(_translate("DlgModeler", "Edit model help", None))
        self.btnEditHelp.setText(_translate("DlgModeler", "...", None))
        self.btnRun.setToolTip(_translate("DlgModeler", "Run model", None))
        self.btnRun.setText(_translate("DlgModeler", "...", None))
        self.btnRun.setShortcut(_translate("DlgModeler", "F5", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DlgModeler", "Inputs", None))
        self.searchBox.setToolTip(_translate("DlgModeler", "Enter algorithm name to filter list", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DlgModeler", "Algorithms", None))
        self.textName.setToolTip(_translate("DlgModeler", "Enter model name here", None))
        self.textGroup.setToolTip(_translate("DlgModeler", "Enter group name here", None))

from qgis.gui import QgsFilterLineEdit
