events {}

http {

    # Port 4442 → OK, to recover the CA from testing docker
    server {
        listen 4442;
        location /ca.crt {
            alias /certs/ca.crt;
            default_type application/x-x509-ca-cert;
        }
    }

    # Port 4443 → self-signed
    server {
        listen 4443 ssl;
        ssl_certificate     /certs/selfsigned.crt;
        ssl_certificate_key /certs/selfsigned.key;
        location / { return 200 "self-signed\n"; }
    }

    # Port 4444 → expired (signed with CA)
    server {
        listen 4444 ssl;
        ssl_certificate     /certs/expired.crt;
        ssl_certificate_key /certs/expired.key;
        location / { return 200 "expired\n"; }
    }
}
