######################################################################
# Automatically generated by qmake (1.07a) Fri Jan 14 13:01:49 2005
######################################################################

TEMPLATE = app
TARGET = testproj
# get gdal inludes
GDAL_INC = $$system(gdal-config --cflags)
INCLUDEPATH += . $$GDAL_INC

CONFIG += debug
# get gdal info
GDAL_LIBS = $$system(gdal-config --libs)
GDAL_DEPS = $$system(gdal-config --dep-libs)
LIBS = $$GDAL_LIBS $$GDAL_DEPS -lcppunit -ldl 
# Input
HEADERS += projectioncshandlingtest.h
SOURCES += main.cpp 
