.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH QGIS 1 "Januray 6, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
qgis \- geographic data viewer
.SH SYNOPSIS
.B qgis [project-file.qgs] | [shapefile.shp] [raster-file.tif] ...
.br
.SH DESCRIPTION
This manual page documents briefly the
.B qgis
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBqgis\fP displays shapefiles, georeferenced raster files, and digital elevation models. You can specify a QGIS project file on the command line to be displayed at startup. Or you can specify a combination of multiple shapefiles and/or raster files to be displayed at startup. 
.SH SEE ALSO
HTML and PDF documentation in /usr/share/doc/qgis and at http://qgis.sourceforge.net/docs/
.SH AUTHOR
This manual page was written by Steve Halasz <debian@adkgis.org>,
for the Debian project (but may be used by others).
