usr/bin/qgis_help
usr/lib/qgis/libcopyrightlabelplugin.so
usr/lib/qgis/libdelimitedtextplugin.so
usr/lib/qgis/libdelimitedtextprovider.so
usr/lib/qgis/libgeorefplugin.so
usr/lib/qgis/libgpsimporterplugin.so
usr/lib/qgis/libgpxprovider.so
usr/lib/qgis/libnortharrowplugin.so
usr/lib/qgis/libogrprovider.so
usr/lib/qgis/libpostgresprovider.so
usr/lib/qgis/libquickprintplugin.so
usr/lib/qgis/libscalebarplugin.so
usr/lib/qgis/libspitplugin.so
usr/lib/qgis/libwfsplugin.so
usr/lib/qgis/libwfsprovider.so
usr/lib/qgis/libwmsprovider.so
usr/lib/qgis/libmemoryprovider.so
usr/lib/qgis/libdxf2shpconverterplugin.so
usr/lib/qgis/libinterpolationplugin.so 
usr/lib/qgis/libogrconverterplugin.so
usr/lib/qgis/libcoordinatecaptureplugin.so
usr/lib/qgis/libspatialiteprovider.so
usr/lib/qgis/liboracleplugin.so
usr/lib/qgis/libdiagramoverlay.so 
usr/lib/qgis/libevis.so 
usr/lib/qgis/libosmprovider.so 
usr/lib/qgis/librasterterrainplugin.so
usr/share/pixmaps/qgis-icon.xpm
usr/share/pixmaps/qgis-mime-icon.png
usr/share/pixmaps/qgis-mime-icon.png usr/share/icons/crystalsvg/128x128/mimetypes
../qgis.desktop usr/share/applications
../qgis.xml usr/share/mime/packages
../mime/application/x-esri-shape.desktop usr/share/mimelnk/application
../mime/application/x-mapinfo-mif.desktop usr/share/mimelnk/application
../mime/application/x-esri-crs.desktop usr/share/mimelnk/application
../mime/application/x-raster-ecw.desktop usr/share/mimelnk/application
../mime/application/x-adobe-mif.desktop usr/share/mimelnk/application
../mime/application/x-raster-aig.desktop usr/share/mimelnk/application
../mime/application/x-qgis-project.desktop usr/share/mimelnk/application
../mime/application/x-raster-mrsid.desktop usr/share/mimelnk/application
../mime/application/x-qgis-layer-settings.desktop usr/share/mimelnk/application
