######################################################################
# Automatically generated by qmake (1.06c) Sat Jun 12 13:28:41 2004
######################################################################

TEMPLATE = lib
INCLUDEPATH += . \
        $(GEOS)\include
LIBS += ..\..\src\libqgis.lib \
        $(GEOS)\lib\geos.lib

CONFIG += qt dll thread
DLLDESTDIR= ..\..\win_build\lib\qgis

# Input
HEADERS += gpsdata.h qgsgpxprovider.h
SOURCES += gpsdata.cpp \
           qgsgpxprovider.cpp 
