# The following has been generated automatically from src/core/editform/qgsattributeeditorrelation.h
QgsAttributeEditorRelation.Link = QgsAttributeEditorRelation.Button.Link
QgsAttributeEditorRelation.Unlink = QgsAttributeEditorRelation.Button.Unlink
QgsAttributeEditorRelation.SaveChildEdits = QgsAttributeEditorRelation.Button.SaveChildEdits
QgsAttributeEditorRelation.AddChildFeature = QgsAttributeEditorRelation.Button.AddChildFeature
QgsAttributeEditorRelation.DuplicateChildFeature = QgsAttributeEditorRelation.Button.DuplicateChildFeature
QgsAttributeEditorRelation.DeleteChildFeature = QgsAttributeEditorRelation.Button.DeleteChildFeature
QgsAttributeEditorRelation.ZoomToChildFeature = QgsAttributeEditorRelation.Button.ZoomToChildFeature
QgsAttributeEditorRelation.AllButtons = QgsAttributeEditorRelation.Button.AllButtons
QgsAttributeEditorRelation.Button.baseClass = QgsAttributeEditorRelation
QgsAttributeEditorRelation.Buttons = lambda flags=0: QgsAttributeEditorRelation.Button(flags)
QgsAttributeEditorRelation.Buttons.baseClass = QgsAttributeEditorRelation
Buttons = QgsAttributeEditorRelation  # dirty hack since SIP seems to introduce the flags in module
