# The following has been generated automatically from src/core/numericformats/qgsbasicnumericformat.h
QgsBasicNumericFormat.DecimalPlaces = QgsBasicNumericFormat.RoundingType.DecimalPlaces
QgsBasicNumericFormat.SignificantFigures = QgsBasicNumericFormat.RoundingType.SignificantFigures
