# The following has been generated automatically from src/core/proj/qgscoordinatereferencesystem.h
QgsCoordinateReferenceSystem.InternalCrsId = QgsCoordinateReferenceSystem.CrsType.InternalCrsId
QgsCoordinateReferenceSystem.PostgisCrsId = QgsCoordinateReferenceSystem.CrsType.PostgisCrsId
QgsCoordinateReferenceSystem.EpsgCrsId = QgsCoordinateReferenceSystem.CrsType.EpsgCrsId
QgsCoordinateReferenceSystem.ShortString = QgsCoordinateReferenceSystem.IdentifierType.ShortString
QgsCoordinateReferenceSystem.MediumString = QgsCoordinateReferenceSystem.IdentifierType.MediumString
QgsCoordinateReferenceSystem.FullString = QgsCoordinateReferenceSystem.IdentifierType.FullString
QgsCoordinateReferenceSystem.WKT1_GDAL = QgsCoordinateReferenceSystem.WktVariant.WKT1_GDAL
QgsCoordinateReferenceSystem.WKT1_ESRI = QgsCoordinateReferenceSystem.WktVariant.WKT1_ESRI
QgsCoordinateReferenceSystem.WKT2_2015 = QgsCoordinateReferenceSystem.WktVariant.WKT2_2015
QgsCoordinateReferenceSystem.WKT2_2015_SIMPLIFIED = QgsCoordinateReferenceSystem.WktVariant.WKT2_2015_SIMPLIFIED
QgsCoordinateReferenceSystem.WKT2_2018 = QgsCoordinateReferenceSystem.WktVariant.WKT2_2018
QgsCoordinateReferenceSystem.WKT2_2018_SIMPLIFIED = QgsCoordinateReferenceSystem.WktVariant.WKT2_2018_SIMPLIFIED
QgsCoordinateReferenceSystem.WKT2_2019 = QgsCoordinateReferenceSystem.WktVariant.WKT2_2019
QgsCoordinateReferenceSystem.WKT2_2019_SIMPLIFIED = QgsCoordinateReferenceSystem.WktVariant.WKT2_2019_SIMPLIFIED
QgsCoordinateReferenceSystem.WKT_PREFERRED = QgsCoordinateReferenceSystem.WktVariant.WKT_PREFERRED
QgsCoordinateReferenceSystem.WKT_PREFERRED_SIMPLIFIED = QgsCoordinateReferenceSystem.WktVariant.WKT_PREFERRED_SIMPLIFIED
QgsCoordinateReferenceSystem.WKT_PREFERRED_GDAL = QgsCoordinateReferenceSystem.WktVariant.WKT_PREFERRED_GDAL
