# The following has been generated automatically from src/core/fieldformatter/qgscheckboxfieldformatter.h
QgsCheckBoxFieldFormatter.ShowTrueFalse = QgsCheckBoxFieldFormatter.TextDisplayMethod.ShowTrueFalse
QgsCheckBoxFieldFormatter.ShowStoredValues = QgsCheckBoxFieldFormatter.TextDisplayMethod.ShowStoredValues
