# The following has been generated automatically from src/core/symbology/qgsinterpolatedlinerenderer.h
QgsInterpolatedLineColor.SingleColor = QgsInterpolatedLineColor.ColoringMethod.SingleColor
QgsInterpolatedLineColor.ColorRamp = QgsInterpolatedLineColor.ColoringMethod.ColorRamp
