# The following has been generated automatically from src/core/layertree/qgslayertreelayer.h
QgsLayerTreeLayer.UseDefaultLegendSetting = QgsLayerTreeLayer.LegendNodesSplitBehavior.UseDefaultLegendSetting
QgsLayerTreeLayer.AllowSplittingLegendNodesOverMultipleColumns = QgsLayerTreeLayer.LegendNodesSplitBehavior.AllowSplittingLegendNodesOverMultipleColumns
QgsLayerTreeLayer.PreventSplittingLegendNodesOverMultipleColumns = QgsLayerTreeLayer.LegendNodesSplitBehavior.PreventSplittingLegendNodesOverMultipleColumns
