# The following has been generated automatically from src/core/locator/qgslocatormodel.h
QgsLocatorModel.ResultDataRole = QgsLocatorModel.Role.ResultDataRole
QgsLocatorModel.ResultTypeRole = QgsLocatorModel.Role.ResultTypeRole
QgsLocatorModel.ResultFilterPriorityRole = QgsLocatorModel.Role.ResultFilterPriorityRole
QgsLocatorModel.ResultScoreRole = QgsLocatorModel.Role.ResultScoreRole
QgsLocatorModel.ResultFilterNameRole = QgsLocatorModel.Role.ResultFilterNameRole
QgsLocatorModel.ResultFilterGroupSortingRole = QgsLocatorModel.Role.ResultFilterGroupSortingRole
QgsLocatorModel.ResultActionsRole = QgsLocatorModel.Role.ResultActionsRole
