# The following has been generated automatically from src/core/layout/qgslayoutrendercontext.h
QgsLayoutRenderContext.FlagDebug = QgsLayoutRenderContext.Flag.FlagDebug
QgsLayoutRenderContext.FlagOutlineOnly = QgsLayoutRenderContext.Flag.FlagOutlineOnly
QgsLayoutRenderContext.FlagAntialiasing = QgsLayoutRenderContext.Flag.FlagAntialiasing
QgsLayoutRenderContext.FlagUseAdvancedEffects = QgsLayoutRenderContext.Flag.FlagUseAdvancedEffects
QgsLayoutRenderContext.FlagForceVectorOutput = QgsLayoutRenderContext.Flag.FlagForceVectorOutput
QgsLayoutRenderContext.FlagHideCoverageLayer = QgsLayoutRenderContext.Flag.FlagHideCoverageLayer
QgsLayoutRenderContext.FlagDrawSelection = QgsLayoutRenderContext.Flag.FlagDrawSelection
QgsLayoutRenderContext.FlagDisableTiledRasterLayerRenders = QgsLayoutRenderContext.Flag.FlagDisableTiledRasterLayerRenders
QgsLayoutRenderContext.FlagRenderLabelsByMapLayer = QgsLayoutRenderContext.Flag.FlagRenderLabelsByMapLayer
QgsLayoutRenderContext.FlagLosslessImageRendering = QgsLayoutRenderContext.Flag.FlagLosslessImageRendering
QgsLayoutRenderContext.FlagSynchronousLegendGraphics = QgsLayoutRenderContext.Flag.FlagSynchronousLegendGraphics
QgsLayoutRenderContext.Flags = lambda flags=0: QgsLayoutRenderContext.Flag(flags)
