# The following has been generated automatically from src/core/qgsmaptopixelgeometrysimplifier.h
QgsMapToPixelSimplifier.NoFlags = QgsMapToPixelSimplifier.SimplifyFlag.NoFlags
QgsMapToPixelSimplifier.SimplifyGeometry = QgsMapToPixelSimplifier.SimplifyFlag.SimplifyGeometry
QgsMapToPixelSimplifier.SimplifyEnvelope = QgsMapToPixelSimplifier.SimplifyFlag.SimplifyEnvelope
