# The following has been generated automatically from src/core/qgsmaptopixelgeometrysimplifier.h
QgsMapToPixelSimplifier.Distance = QgsMapToPixelSimplifier.SimplifyAlgorithm.Distance
QgsMapToPixelSimplifier.SnapToGrid = QgsMapToPixelSimplifier.SimplifyAlgorithm.SnapToGrid
QgsMapToPixelSimplifier.Visvalingam = QgsMapToPixelSimplifier.SimplifyAlgorithm.Visvalingam
QgsMapToPixelSimplifier.SnappedToGridGlobal = QgsMapToPixelSimplifier.SimplifyAlgorithm.SnappedToGridGlobal
QgsMapToPixelSimplifier.NoFlags = QgsMapToPixelSimplifier.SimplifyFlag.NoFlags
QgsMapToPixelSimplifier.SimplifyGeometry = QgsMapToPixelSimplifier.SimplifyFlag.SimplifyGeometry
QgsMapToPixelSimplifier.SimplifyEnvelope = QgsMapToPixelSimplifier.SimplifyFlag.SimplifyEnvelope
