# The following has been generated automatically from src/core/maprenderer/qgsmaprenderertask.h
QgsMapRendererTask.ImageAllocationFail = QgsMapRendererTask.ErrorType.ImageAllocationFail
QgsMapRendererTask.ImageSaveFail = QgsMapRendererTask.ErrorType.ImageSaveFail
QgsMapRendererTask.ImageUnsupportedFormat = QgsMapRendererTask.ErrorType.ImageUnsupportedFormat
