# The following has been generated automatically from src/core/symbology/qgsmergedfeaturerenderer.h
QgsMergedFeatureRenderer.Merge = QgsMergedFeatureRenderer.GeometryOperation.Merge
QgsMergedFeatureRenderer.InvertOnly = QgsMergedFeatureRenderer.GeometryOperation.InvertOnly
QgsMergedFeatureRenderer.MergeAndInvert = QgsMergedFeatureRenderer.GeometryOperation.MergeAndInvert
QgsMergedFeatureRenderer.create = staticmethod(QgsMergedFeatureRenderer.create)
QgsMergedFeatureRenderer.convertFromRenderer = staticmethod(QgsMergedFeatureRenderer.convertFromRenderer)
