# The following has been generated automatically from src/core/processing/qgsprocessingparameters.h
QgsProcessingFeatureSourceDefinition.FlagOverrideDefaultGeometryCheck = QgsProcessingFeatureSourceDefinition.Flag.FlagOverrideDefaultGeometryCheck
QgsProcessingFeatureSourceDefinition.FlagCreateIndividualOutputPerInputFeature = QgsProcessingFeatureSourceDefinition.Flag.FlagCreateIndividualOutputPerInputFeature
QgsProcessingFeatureSourceDefinition.Flags = lambda flags=0: QgsProcessingFeatureSourceDefinition.Flag(flags)
QgsProcessingParameterDefinition.FlagAdvanced = QgsProcessingParameterDefinition.Flag.FlagAdvanced
QgsProcessingParameterDefinition.FlagHidden = QgsProcessingParameterDefinition.Flag.FlagHidden
QgsProcessingParameterDefinition.FlagOptional = QgsProcessingParameterDefinition.Flag.FlagOptional
QgsProcessingParameterDefinition.FlagIsModelOutput = QgsProcessingParameterDefinition.Flag.FlagIsModelOutput
QgsProcessingParameterDefinition.Flags = lambda flags=0: QgsProcessingParameterDefinition.Flag(flags)
QgsProcessingParameterFile.File = QgsProcessingParameterFile.Behavior.File
QgsProcessingParameterFile.Folder = QgsProcessingParameterFile.Behavior.Folder
QgsProcessingParameterNumber.Integer = QgsProcessingParameterNumber.Type.Integer
QgsProcessingParameterNumber.Double = QgsProcessingParameterNumber.Type.Double
QgsProcessingParameterField.Any = QgsProcessingParameterField.DataType.Any
QgsProcessingParameterField.Numeric = QgsProcessingParameterField.DataType.Numeric
QgsProcessingParameterField.String = QgsProcessingParameterField.DataType.String
QgsProcessingParameterField.DateTime = QgsProcessingParameterField.DataType.DateTime
QgsProcessingParameterField.Binary = QgsProcessingParameterField.DataType.Binary
QgsProcessingParameterField.Boolean = QgsProcessingParameterField.DataType.Boolean
QgsProcessingParameterDateTime.DateTime = QgsProcessingParameterDateTime.Type.DateTime
QgsProcessingParameterDateTime.Date = QgsProcessingParameterDateTime.Type.Date
QgsProcessingParameterDateTime.Time = QgsProcessingParameterDateTime.Type.Time
