# The following has been generated automatically from src/core/processing/qgsprocessingalgorithm.h
QgsProcessingAlgorithm.FlagHideFromToolbox = QgsProcessingAlgorithm.Flag.FlagHideFromToolbox
QgsProcessingAlgorithm.FlagHideFromModeler = QgsProcessingAlgorithm.Flag.FlagHideFromModeler
QgsProcessingAlgorithm.FlagSupportsBatch = QgsProcessingAlgorithm.Flag.FlagSupportsBatch
QgsProcessingAlgorithm.FlagCanCancel = QgsProcessingAlgorithm.Flag.FlagCanCancel
QgsProcessingAlgorithm.FlagRequiresMatchingCrs = QgsProcessingAlgorithm.Flag.FlagRequiresMatchingCrs
QgsProcessingAlgorithm.FlagNoThreading = QgsProcessingAlgorithm.Flag.FlagNoThreading
QgsProcessingAlgorithm.FlagDisplayNameIsLiteral = QgsProcessingAlgorithm.Flag.FlagDisplayNameIsLiteral
QgsProcessingAlgorithm.FlagSupportsInPlaceEdits = QgsProcessingAlgorithm.Flag.FlagSupportsInPlaceEdits
QgsProcessingAlgorithm.FlagKnownIssues = QgsProcessingAlgorithm.Flag.FlagKnownIssues
QgsProcessingAlgorithm.FlagCustomException = QgsProcessingAlgorithm.Flag.FlagCustomException
QgsProcessingAlgorithm.FlagPruneModelBranchesBasedOnAlgorithmResults = QgsProcessingAlgorithm.Flag.FlagPruneModelBranchesBasedOnAlgorithmResults
QgsProcessingAlgorithm.FlagSkipGenericModelLogging = QgsProcessingAlgorithm.Flag.FlagSkipGenericModelLogging
QgsProcessingAlgorithm.FlagNotAvailableInStandaloneTool = QgsProcessingAlgorithm.Flag.FlagNotAvailableInStandaloneTool
QgsProcessingAlgorithm.FlagRequiresProject = QgsProcessingAlgorithm.Flag.FlagRequiresProject
QgsProcessingAlgorithm.FlagDeprecated = QgsProcessingAlgorithm.Flag.FlagDeprecated
QgsProcessingAlgorithm.Flags = lambda flags=0: QgsProcessingAlgorithm.Flag(flags)
QgsProcessingAlgorithm.NotAvailable = QgsProcessingAlgorithm.PropertyAvailability.NotAvailable
QgsProcessingAlgorithm.Available = QgsProcessingAlgorithm.PropertyAvailability.Available
