# The following has been generated automatically from src/core/processing/qgsprocessingparameteralignrasterlayers.h
QgsProcessingParameterAlignRasterLayers.typeName = staticmethod(QgsProcessingParameterAlignRasterLayers.typeName)
QgsProcessingParameterAlignRasterLayers.parameterAsItems = staticmethod(QgsProcessingParameterAlignRasterLayers.parameterAsItems)
QgsProcessingParameterAlignRasterLayers.variantMapAsItem = staticmethod(QgsProcessingParameterAlignRasterLayers.variantMapAsItem)
QgsProcessingParameterAlignRasterLayers.itemAsVariantMap = staticmethod(QgsProcessingParameterAlignRasterLayers.itemAsVariantMap)
