# The following has been generated automatically from src/core/processing/qgsprocessingfeedback.h
try:
    QgsProcessingFeedback.__attribute_docs__ = {'progressTextChanged': 'Emitted when the progress ``text`` is changed.\n\n.. seealso:: :py:func:`setProgressText`\n\n.. versionadded:: 4.2\n', 'errorReported': 'Emitted when an error is reported.\n\n.. seealso:: :py:func:`reportError`\n\n.. versionadded:: 4.2\n', 'warningPushed': 'Emitted when an warning is pushed.\n\n.. seealso:: :py:func:`pushWarning`\n\n.. versionadded:: 4.2\n', 'infoPushed': 'Emitted when information ``text`` is pushed.\n\n.. seealso:: :py:func:`pushInfo`\n\n.. versionadded:: 4.2\n', 'commandInfoPushed': 'Emitted when command information ``text`` is pushed.\n\n.. seealso:: :py:func:`pushCommandInfo`\n\n.. versionadded:: 4.2\n', 'debugInfoPushed': 'Emitted when debug information ``text`` is pushed.\n\n.. seealso:: :py:func:`pushDebugInfo`\n\n.. versionadded:: 4.2\n', 'consoleInfoPushed': 'Emitted when console information ``text`` is pushed.\n\n.. seealso:: :py:func:`pushConsoleInfo`\n\n.. versionadded:: 4.2\n', 'formattedMessagePushed': 'Emitted when a formatted ``html`` message is pushed.\n\n.. seealso:: :py:func:`pushFormattedMessage`\n\n.. versionadded:: 4.2\n', 'sinkFeatureCountChanged': 'Emitted when the count of features pushed to a sink has changed.\n\nThe ``output`` argument specifies the associated algorithm output name.\n\n.. note::\n\n   For performance, this signal is not emitted for every individual feature\n   added to the sink. It is instead emitted only once for every 100 features added.\n\n.. seealso:: :py:func:`featureAddedToSink`\n\n.. seealso:: :py:func:`featureSinkFinalized`\n\n.. versionadded:: 4.2\n', 'sourceLoaded': 'Emitted when a feature source was retrieved for the specified algorithm\ninput parameter.\n\n.. seealso:: :py:func:`reportSourceLoaded`\n\n.. versionadded:: 4.2\n'}
    QgsProcessingFeedback.__virtual_methods__ = ['setProgressText', 'reportError', 'pushWarning', 'pushInfo', 'pushFormattedMessage', 'pushCommandInfo', 'pushDebugInfo', 'pushConsoleInfo', 'htmlLog', 'textLog']
    QgsProcessingFeedback.__signal_arguments__ = {'progressTextChanged': ['text: str'], 'errorReported': ['text: str', 'fatalError: bool'], 'warningPushed': ['text: str'], 'infoPushed': ['text: str'], 'commandInfoPushed': ['text: str'], 'debugInfoPushed': ['text: str'], 'consoleInfoPushed': ['text: str'], 'formattedMessagePushed': ['html: str'], 'sinkFeatureCountChanged': ['output: str', 'featureCount: int'], 'sourceLoaded': ['parameterName: str', 'featureCount: int']}
    QgsProcessingFeedback.__group__ = ['processing']
except (NameError, AttributeError):
    pass
try:
    QgsProcessingMultiStepFeedback.__overridden_methods__ = ['setProgressText', 'reportError', 'pushWarning', 'pushInfo', 'pushCommandInfo', 'pushDebugInfo', 'pushConsoleInfo', 'pushFormattedMessage', 'htmlLog', 'textLog']
    QgsProcessingMultiStepFeedback.__group__ = ['processing']
except (NameError, AttributeError):
    pass
