# The following has been generated automatically from src/core/numericformats/qgspercentagenumericformat.h
QgsPercentageNumericFormat.ValuesArePercentage = QgsPercentageNumericFormat.InputValues.ValuesArePercentage
QgsPercentageNumericFormat.ValuesAreFractions = QgsPercentageNumericFormat.InputValues.ValuesAreFractions
