# The following has been generated automatically from src/core/processing/models/qgsprocessingmodelchildparametersource.h
QgsProcessingModelChildParameterSource.fromStaticValue = staticmethod(QgsProcessingModelChildParameterSource.fromStaticValue)
QgsProcessingModelChildParameterSource.fromModelParameter = staticmethod(QgsProcessingModelChildParameterSource.fromModelParameter)
QgsProcessingModelChildParameterSource.fromChildOutput = staticmethod(QgsProcessingModelChildParameterSource.fromChildOutput)
QgsProcessingModelChildParameterSource.fromExpression = staticmethod(QgsProcessingModelChildParameterSource.fromExpression)
QgsProcessingModelChildParameterSource.fromExpressionText = staticmethod(QgsProcessingModelChildParameterSource.fromExpressionText)
