# The following has been generated automatically from src/core/processing/qgsprocessingparametertininputlayers.h
QgsProcessingParameterTinInputLayers.typeName = staticmethod(QgsProcessingParameterTinInputLayers.typeName)
