# The following has been generated automatically from src/core/processing/qgsprocessingparametervectortilewriterlayers.h
QgsProcessingParameterVectorTileWriterLayers.typeName = staticmethod(QgsProcessingParameterVectorTileWriterLayers.typeName)
QgsProcessingParameterVectorTileWriterLayers.parameterAsLayers = staticmethod(QgsProcessingParameterVectorTileWriterLayers.parameterAsLayers)
QgsProcessingParameterVectorTileWriterLayers.variantMapAsLayer = staticmethod(QgsProcessingParameterVectorTileWriterLayers.variantMapAsLayer)
QgsProcessingParameterVectorTileWriterLayers.layerAsVariantMap = staticmethod(QgsProcessingParameterVectorTileWriterLayers.layerAsVariantMap)
try:
    QgsProcessingParameterVectorTileWriterLayers.__group__ = ['processing']
except NameError:
    pass
