# The following has been generated automatically from src/core/raster/qgsrasterlayerutils.h
QgsRasterLayerUtils.renderedBandForElevationAndTemporalRange = staticmethod(QgsRasterLayerUtils.renderedBandForElevationAndTemporalRange)
