# The following has been generated automatically from src/core/symbology/qgssymbollayer.h
# monkey patching scoped based enum
QgsSymbolLayer.PropertySize = QgsSymbolLayer.Property.Size
QgsSymbolLayer.Property.PropertySize = QgsSymbolLayer.Property.Size
QgsSymbolLayer.PropertySize.is_monkey_patched = True
QgsSymbolLayer.PropertySize.__doc__ = "Symbol size"
QgsSymbolLayer.PropertyAngle = QgsSymbolLayer.Property.Angle
QgsSymbolLayer.Property.PropertyAngle = QgsSymbolLayer.Property.Angle
QgsSymbolLayer.PropertyAngle.is_monkey_patched = True
QgsSymbolLayer.PropertyAngle.__doc__ = "Symbol angle"
QgsSymbolLayer.PropertyName = QgsSymbolLayer.Property.Name
QgsSymbolLayer.Property.PropertyName = QgsSymbolLayer.Property.Name
QgsSymbolLayer.PropertyName.is_monkey_patched = True
QgsSymbolLayer.PropertyName.__doc__ = "Name, eg shape name for simple markers"
QgsSymbolLayer.PropertyFillColor = QgsSymbolLayer.Property.FillColor
QgsSymbolLayer.Property.PropertyFillColor = QgsSymbolLayer.Property.FillColor
QgsSymbolLayer.PropertyFillColor.is_monkey_patched = True
QgsSymbolLayer.PropertyFillColor.__doc__ = "Fill color"
QgsSymbolLayer.PropertyStrokeColor = QgsSymbolLayer.Property.StrokeColor
QgsSymbolLayer.Property.PropertyStrokeColor = QgsSymbolLayer.Property.StrokeColor
QgsSymbolLayer.PropertyStrokeColor.is_monkey_patched = True
QgsSymbolLayer.PropertyStrokeColor.__doc__ = "Stroke color"
QgsSymbolLayer.PropertyStrokeWidth = QgsSymbolLayer.Property.StrokeWidth
QgsSymbolLayer.Property.PropertyStrokeWidth = QgsSymbolLayer.Property.StrokeWidth
QgsSymbolLayer.PropertyStrokeWidth.is_monkey_patched = True
QgsSymbolLayer.PropertyStrokeWidth.__doc__ = "Stroke width"
QgsSymbolLayer.PropertyStrokeStyle = QgsSymbolLayer.Property.StrokeStyle
QgsSymbolLayer.Property.PropertyStrokeStyle = QgsSymbolLayer.Property.StrokeStyle
QgsSymbolLayer.PropertyStrokeStyle.is_monkey_patched = True
QgsSymbolLayer.PropertyStrokeStyle.__doc__ = "Stroke style (eg solid, dashed)"
QgsSymbolLayer.PropertyOffset = QgsSymbolLayer.Property.Offset
QgsSymbolLayer.Property.PropertyOffset = QgsSymbolLayer.Property.Offset
QgsSymbolLayer.PropertyOffset.is_monkey_patched = True
QgsSymbolLayer.PropertyOffset.__doc__ = "Symbol offset"
QgsSymbolLayer.PropertyCharacter = QgsSymbolLayer.Property.Character
QgsSymbolLayer.Property.PropertyCharacter = QgsSymbolLayer.Property.Character
QgsSymbolLayer.PropertyCharacter.is_monkey_patched = True
QgsSymbolLayer.PropertyCharacter.__doc__ = "Character, eg for font marker symbol layers"
QgsSymbolLayer.PropertyWidth = QgsSymbolLayer.Property.Width
QgsSymbolLayer.Property.PropertyWidth = QgsSymbolLayer.Property.Width
QgsSymbolLayer.PropertyWidth.is_monkey_patched = True
QgsSymbolLayer.PropertyWidth.__doc__ = "Symbol width"
QgsSymbolLayer.PropertyHeight = QgsSymbolLayer.Property.Height
QgsSymbolLayer.Property.PropertyHeight = QgsSymbolLayer.Property.Height
QgsSymbolLayer.PropertyHeight.is_monkey_patched = True
QgsSymbolLayer.PropertyHeight.__doc__ = "Symbol height"
QgsSymbolLayer.PropertyPreserveAspectRatio = QgsSymbolLayer.Property.PreserveAspectRatio
QgsSymbolLayer.Property.PropertyPreserveAspectRatio = QgsSymbolLayer.Property.PreserveAspectRatio
QgsSymbolLayer.PropertyPreserveAspectRatio.is_monkey_patched = True
QgsSymbolLayer.PropertyPreserveAspectRatio.__doc__ = "Preserve aspect ratio between width and height"
QgsSymbolLayer.PropertyFillStyle = QgsSymbolLayer.Property.FillStyle
QgsSymbolLayer.Property.PropertyFillStyle = QgsSymbolLayer.Property.FillStyle
QgsSymbolLayer.PropertyFillStyle.is_monkey_patched = True
QgsSymbolLayer.PropertyFillStyle.__doc__ = "Fill style (eg solid, dots)"
QgsSymbolLayer.PropertyJoinStyle = QgsSymbolLayer.Property.JoinStyle
QgsSymbolLayer.Property.PropertyJoinStyle = QgsSymbolLayer.Property.JoinStyle
QgsSymbolLayer.PropertyJoinStyle.is_monkey_patched = True
QgsSymbolLayer.PropertyJoinStyle.__doc__ = "Line join style"
QgsSymbolLayer.PropertySecondaryColor = QgsSymbolLayer.Property.SecondaryColor
QgsSymbolLayer.Property.PropertySecondaryColor = QgsSymbolLayer.Property.SecondaryColor
QgsSymbolLayer.PropertySecondaryColor.is_monkey_patched = True
QgsSymbolLayer.PropertySecondaryColor.__doc__ = "Secondary color (eg for gradient fills)"
QgsSymbolLayer.PropertyLineAngle = QgsSymbolLayer.Property.LineAngle
QgsSymbolLayer.Property.PropertyLineAngle = QgsSymbolLayer.Property.LineAngle
QgsSymbolLayer.PropertyLineAngle.is_monkey_patched = True
QgsSymbolLayer.PropertyLineAngle.__doc__ = "Line angle, or angle of hash lines for hash line symbols"
QgsSymbolLayer.PropertyLineDistance = QgsSymbolLayer.Property.LineDistance
QgsSymbolLayer.Property.PropertyLineDistance = QgsSymbolLayer.Property.LineDistance
QgsSymbolLayer.PropertyLineDistance.is_monkey_patched = True
QgsSymbolLayer.PropertyLineDistance.__doc__ = "Distance between lines, or length of lines for hash line symbols"
QgsSymbolLayer.PropertyGradientType = QgsSymbolLayer.Property.GradientType
QgsSymbolLayer.Property.PropertyGradientType = QgsSymbolLayer.Property.GradientType
QgsSymbolLayer.PropertyGradientType.is_monkey_patched = True
QgsSymbolLayer.PropertyGradientType.__doc__ = "Gradient fill type"
QgsSymbolLayer.PropertyCoordinateMode = QgsSymbolLayer.Property.CoordinateMode
QgsSymbolLayer.Property.PropertyCoordinateMode = QgsSymbolLayer.Property.CoordinateMode
QgsSymbolLayer.PropertyCoordinateMode.is_monkey_patched = True
QgsSymbolLayer.PropertyCoordinateMode.__doc__ = "Gradient coordinate mode"
QgsSymbolLayer.PropertyGradientSpread = QgsSymbolLayer.Property.GradientSpread
QgsSymbolLayer.Property.PropertyGradientSpread = QgsSymbolLayer.Property.GradientSpread
QgsSymbolLayer.PropertyGradientSpread.is_monkey_patched = True
QgsSymbolLayer.PropertyGradientSpread.__doc__ = "Gradient spread mode"
QgsSymbolLayer.PropertyGradientReference1X = QgsSymbolLayer.Property.GradientReference1X
QgsSymbolLayer.Property.PropertyGradientReference1X = QgsSymbolLayer.Property.GradientReference1X
QgsSymbolLayer.PropertyGradientReference1X.is_monkey_patched = True
QgsSymbolLayer.PropertyGradientReference1X.__doc__ = "Gradient reference point 1 x"
QgsSymbolLayer.PropertyGradientReference1Y = QgsSymbolLayer.Property.GradientReference1Y
QgsSymbolLayer.Property.PropertyGradientReference1Y = QgsSymbolLayer.Property.GradientReference1Y
QgsSymbolLayer.PropertyGradientReference1Y.is_monkey_patched = True
QgsSymbolLayer.PropertyGradientReference1Y.__doc__ = "Gradient reference point 1 y"
QgsSymbolLayer.PropertyGradientReference2X = QgsSymbolLayer.Property.GradientReference2X
QgsSymbolLayer.Property.PropertyGradientReference2X = QgsSymbolLayer.Property.GradientReference2X
QgsSymbolLayer.PropertyGradientReference2X.is_monkey_patched = True
QgsSymbolLayer.PropertyGradientReference2X.__doc__ = "Gradient reference point 2 x"
QgsSymbolLayer.PropertyGradientReference2Y = QgsSymbolLayer.Property.GradientReference2Y
QgsSymbolLayer.Property.PropertyGradientReference2Y = QgsSymbolLayer.Property.GradientReference2Y
QgsSymbolLayer.PropertyGradientReference2Y.is_monkey_patched = True
QgsSymbolLayer.PropertyGradientReference2Y.__doc__ = "Gradient reference point 2 y"
QgsSymbolLayer.PropertyGradientReference1IsCentroid = QgsSymbolLayer.Property.GradientReference1IsCentroid
QgsSymbolLayer.Property.PropertyGradientReference1IsCentroid = QgsSymbolLayer.Property.GradientReference1IsCentroid
QgsSymbolLayer.PropertyGradientReference1IsCentroid.is_monkey_patched = True
QgsSymbolLayer.PropertyGradientReference1IsCentroid.__doc__ = "Gradient reference point 1 is centroid"
QgsSymbolLayer.PropertyGradientReference2IsCentroid = QgsSymbolLayer.Property.GradientReference2IsCentroid
QgsSymbolLayer.Property.PropertyGradientReference2IsCentroid = QgsSymbolLayer.Property.GradientReference2IsCentroid
QgsSymbolLayer.PropertyGradientReference2IsCentroid.is_monkey_patched = True
QgsSymbolLayer.PropertyGradientReference2IsCentroid.__doc__ = "Gradient reference point 2 is centroid"
QgsSymbolLayer.PropertyBlurRadius = QgsSymbolLayer.Property.BlurRadius
QgsSymbolLayer.Property.PropertyBlurRadius = QgsSymbolLayer.Property.BlurRadius
QgsSymbolLayer.PropertyBlurRadius.is_monkey_patched = True
QgsSymbolLayer.PropertyBlurRadius.__doc__ = "Shapeburst blur radius"
QgsSymbolLayer.PropertyShapeburstUseWholeShape = QgsSymbolLayer.Property.ShapeburstUseWholeShape
QgsSymbolLayer.Property.PropertyShapeburstUseWholeShape = QgsSymbolLayer.Property.ShapeburstUseWholeShape
QgsSymbolLayer.PropertyShapeburstUseWholeShape.is_monkey_patched = True
QgsSymbolLayer.PropertyShapeburstUseWholeShape.__doc__ = "Shapeburst use whole shape"
QgsSymbolLayer.PropertyShapeburstMaxDistance = QgsSymbolLayer.Property.ShapeburstMaxDistance
QgsSymbolLayer.Property.PropertyShapeburstMaxDistance = QgsSymbolLayer.Property.ShapeburstMaxDistance
QgsSymbolLayer.PropertyShapeburstMaxDistance.is_monkey_patched = True
QgsSymbolLayer.PropertyShapeburstMaxDistance.__doc__ = "Shapeburst fill from edge distance"
QgsSymbolLayer.PropertyShapeburstIgnoreRings = QgsSymbolLayer.Property.ShapeburstIgnoreRings
QgsSymbolLayer.Property.PropertyShapeburstIgnoreRings = QgsSymbolLayer.Property.ShapeburstIgnoreRings
QgsSymbolLayer.PropertyShapeburstIgnoreRings.is_monkey_patched = True
QgsSymbolLayer.PropertyShapeburstIgnoreRings.__doc__ = "Shapeburst ignore rings"
QgsSymbolLayer.PropertyFile = QgsSymbolLayer.Property.File
QgsSymbolLayer.Property.PropertyFile = QgsSymbolLayer.Property.File
QgsSymbolLayer.PropertyFile.is_monkey_patched = True
QgsSymbolLayer.PropertyFile.__doc__ = "Filename, eg for svg files"
QgsSymbolLayer.PropertyDistanceX = QgsSymbolLayer.Property.DistanceX
QgsSymbolLayer.Property.PropertyDistanceX = QgsSymbolLayer.Property.DistanceX
QgsSymbolLayer.PropertyDistanceX.is_monkey_patched = True
QgsSymbolLayer.PropertyDistanceX.__doc__ = "Horizontal distance between points"
QgsSymbolLayer.PropertyDistanceY = QgsSymbolLayer.Property.DistanceY
QgsSymbolLayer.Property.PropertyDistanceY = QgsSymbolLayer.Property.DistanceY
QgsSymbolLayer.PropertyDistanceY.is_monkey_patched = True
QgsSymbolLayer.PropertyDistanceY.__doc__ = "Vertical distance between points"
QgsSymbolLayer.PropertyDisplacementX = QgsSymbolLayer.Property.DisplacementX
QgsSymbolLayer.Property.PropertyDisplacementX = QgsSymbolLayer.Property.DisplacementX
QgsSymbolLayer.PropertyDisplacementX.is_monkey_patched = True
QgsSymbolLayer.PropertyDisplacementX.__doc__ = "Horizontal displacement"
QgsSymbolLayer.PropertyDisplacementY = QgsSymbolLayer.Property.DisplacementY
QgsSymbolLayer.Property.PropertyDisplacementY = QgsSymbolLayer.Property.DisplacementY
QgsSymbolLayer.PropertyDisplacementY.is_monkey_patched = True
QgsSymbolLayer.PropertyDisplacementY.__doc__ = "Vertical displacement"
QgsSymbolLayer.PropertyOpacity = QgsSymbolLayer.Property.Opacity
QgsSymbolLayer.Property.PropertyOpacity = QgsSymbolLayer.Property.Opacity
QgsSymbolLayer.PropertyOpacity.is_monkey_patched = True
QgsSymbolLayer.PropertyOpacity.__doc__ = "Opacity"
QgsSymbolLayer.PropertyCustomDash = QgsSymbolLayer.Property.CustomDash
QgsSymbolLayer.Property.PropertyCustomDash = QgsSymbolLayer.Property.CustomDash
QgsSymbolLayer.PropertyCustomDash.is_monkey_patched = True
QgsSymbolLayer.PropertyCustomDash.__doc__ = "Custom dash pattern"
QgsSymbolLayer.PropertyCapStyle = QgsSymbolLayer.Property.CapStyle
QgsSymbolLayer.Property.PropertyCapStyle = QgsSymbolLayer.Property.CapStyle
QgsSymbolLayer.PropertyCapStyle.is_monkey_patched = True
QgsSymbolLayer.PropertyCapStyle.__doc__ = "Line cap style"
QgsSymbolLayer.PropertyPlacement = QgsSymbolLayer.Property.Placement
QgsSymbolLayer.Property.PropertyPlacement = QgsSymbolLayer.Property.Placement
QgsSymbolLayer.PropertyPlacement.is_monkey_patched = True
QgsSymbolLayer.PropertyPlacement.__doc__ = "Line marker placement"
QgsSymbolLayer.PropertyInterval = QgsSymbolLayer.Property.Interval
QgsSymbolLayer.Property.PropertyInterval = QgsSymbolLayer.Property.Interval
QgsSymbolLayer.PropertyInterval.is_monkey_patched = True
QgsSymbolLayer.PropertyInterval.__doc__ = "Line marker interval"
QgsSymbolLayer.PropertyOffsetAlongLine = QgsSymbolLayer.Property.OffsetAlongLine
QgsSymbolLayer.Property.PropertyOffsetAlongLine = QgsSymbolLayer.Property.OffsetAlongLine
QgsSymbolLayer.PropertyOffsetAlongLine.is_monkey_patched = True
QgsSymbolLayer.PropertyOffsetAlongLine.__doc__ = "Offset along line"
QgsSymbolLayer.PropertyAverageAngleLength = QgsSymbolLayer.Property.AverageAngleLength
QgsSymbolLayer.Property.PropertyAverageAngleLength = QgsSymbolLayer.Property.AverageAngleLength
QgsSymbolLayer.PropertyAverageAngleLength.is_monkey_patched = True
QgsSymbolLayer.PropertyAverageAngleLength.__doc__ = "Length to average symbol angles over"
QgsSymbolLayer.PropertyHorizontalAnchor = QgsSymbolLayer.Property.HorizontalAnchor
QgsSymbolLayer.Property.PropertyHorizontalAnchor = QgsSymbolLayer.Property.HorizontalAnchor
QgsSymbolLayer.PropertyHorizontalAnchor.is_monkey_patched = True
QgsSymbolLayer.PropertyHorizontalAnchor.__doc__ = "Horizontal anchor point"
QgsSymbolLayer.PropertyVerticalAnchor = QgsSymbolLayer.Property.VerticalAnchor
QgsSymbolLayer.Property.PropertyVerticalAnchor = QgsSymbolLayer.Property.VerticalAnchor
QgsSymbolLayer.PropertyVerticalAnchor.is_monkey_patched = True
QgsSymbolLayer.PropertyVerticalAnchor.__doc__ = "Vertical anchor point"
QgsSymbolLayer.PropertyLayerEnabled = QgsSymbolLayer.Property.LayerEnabled
QgsSymbolLayer.Property.PropertyLayerEnabled = QgsSymbolLayer.Property.LayerEnabled
QgsSymbolLayer.PropertyLayerEnabled.is_monkey_patched = True
QgsSymbolLayer.PropertyLayerEnabled.__doc__ = "Whether symbol layer is enabled"
QgsSymbolLayer.PropertyArrowWidth = QgsSymbolLayer.Property.ArrowWidth
QgsSymbolLayer.Property.PropertyArrowWidth = QgsSymbolLayer.Property.ArrowWidth
QgsSymbolLayer.PropertyArrowWidth.is_monkey_patched = True
QgsSymbolLayer.PropertyArrowWidth.__doc__ = "Arrow tail width"
QgsSymbolLayer.PropertyArrowStartWidth = QgsSymbolLayer.Property.ArrowStartWidth
QgsSymbolLayer.Property.PropertyArrowStartWidth = QgsSymbolLayer.Property.ArrowStartWidth
QgsSymbolLayer.PropertyArrowStartWidth.is_monkey_patched = True
QgsSymbolLayer.PropertyArrowStartWidth.__doc__ = "Arrow tail start width"
QgsSymbolLayer.PropertyArrowHeadLength = QgsSymbolLayer.Property.ArrowHeadLength
QgsSymbolLayer.Property.PropertyArrowHeadLength = QgsSymbolLayer.Property.ArrowHeadLength
QgsSymbolLayer.PropertyArrowHeadLength.is_monkey_patched = True
QgsSymbolLayer.PropertyArrowHeadLength.__doc__ = "Arrow head length"
QgsSymbolLayer.PropertyArrowHeadThickness = QgsSymbolLayer.Property.ArrowHeadThickness
QgsSymbolLayer.Property.PropertyArrowHeadThickness = QgsSymbolLayer.Property.ArrowHeadThickness
QgsSymbolLayer.PropertyArrowHeadThickness.is_monkey_patched = True
QgsSymbolLayer.PropertyArrowHeadThickness.__doc__ = "Arrow head thickness"
QgsSymbolLayer.PropertyArrowHeadType = QgsSymbolLayer.Property.ArrowHeadType
QgsSymbolLayer.Property.PropertyArrowHeadType = QgsSymbolLayer.Property.ArrowHeadType
QgsSymbolLayer.PropertyArrowHeadType.is_monkey_patched = True
QgsSymbolLayer.PropertyArrowHeadType.__doc__ = "Arrow head type"
QgsSymbolLayer.PropertyArrowType = QgsSymbolLayer.Property.ArrowType
QgsSymbolLayer.Property.PropertyArrowType = QgsSymbolLayer.Property.ArrowType
QgsSymbolLayer.PropertyArrowType.is_monkey_patched = True
QgsSymbolLayer.PropertyArrowType.__doc__ = "Arrow type"
QgsSymbolLayer.PropertyOffsetX = QgsSymbolLayer.Property.OffsetX
QgsSymbolLayer.Property.PropertyOffsetX = QgsSymbolLayer.Property.OffsetX
QgsSymbolLayer.PropertyOffsetX.is_monkey_patched = True
QgsSymbolLayer.PropertyOffsetX.__doc__ = "Horizontal offset"
QgsSymbolLayer.PropertyOffsetY = QgsSymbolLayer.Property.OffsetY
QgsSymbolLayer.Property.PropertyOffsetY = QgsSymbolLayer.Property.OffsetY
QgsSymbolLayer.PropertyOffsetY.is_monkey_patched = True
QgsSymbolLayer.PropertyOffsetY.__doc__ = "Vertical offset"
QgsSymbolLayer.PropertyPointCount = QgsSymbolLayer.Property.PointCount
QgsSymbolLayer.Property.PropertyPointCount = QgsSymbolLayer.Property.PointCount
QgsSymbolLayer.PropertyPointCount.is_monkey_patched = True
QgsSymbolLayer.PropertyPointCount.__doc__ = "Point count"
QgsSymbolLayer.PropertyRandomSeed = QgsSymbolLayer.Property.RandomSeed
QgsSymbolLayer.Property.PropertyRandomSeed = QgsSymbolLayer.Property.RandomSeed
QgsSymbolLayer.PropertyRandomSeed.is_monkey_patched = True
QgsSymbolLayer.PropertyRandomSeed.__doc__ = "Random number seed"
QgsSymbolLayer.PropertyClipPoints = QgsSymbolLayer.Property.ClipPoints
QgsSymbolLayer.Property.PropertyClipPoints = QgsSymbolLayer.Property.ClipPoints
QgsSymbolLayer.PropertyClipPoints.is_monkey_patched = True
QgsSymbolLayer.PropertyClipPoints.__doc__ = "Whether markers should be clipped to polygon boundaries"
QgsSymbolLayer.PropertyDensityArea = QgsSymbolLayer.Property.DensityArea
QgsSymbolLayer.Property.PropertyDensityArea = QgsSymbolLayer.Property.DensityArea
QgsSymbolLayer.PropertyDensityArea.is_monkey_patched = True
QgsSymbolLayer.PropertyDensityArea.__doc__ = "Density area"
QgsSymbolLayer.PropertyFontFamily = QgsSymbolLayer.Property.FontFamily
QgsSymbolLayer.Property.PropertyFontFamily = QgsSymbolLayer.Property.FontFamily
QgsSymbolLayer.PropertyFontFamily.is_monkey_patched = True
QgsSymbolLayer.PropertyFontFamily.__doc__ = "Font family"
QgsSymbolLayer.PropertyFontStyle = QgsSymbolLayer.Property.FontStyle
QgsSymbolLayer.Property.PropertyFontStyle = QgsSymbolLayer.Property.FontStyle
QgsSymbolLayer.PropertyFontStyle.is_monkey_patched = True
QgsSymbolLayer.PropertyFontStyle.__doc__ = "Font style"
QgsSymbolLayer.PropertyDashPatternOffset = QgsSymbolLayer.Property.DashPatternOffset
QgsSymbolLayer.Property.PropertyDashPatternOffset = QgsSymbolLayer.Property.DashPatternOffset
QgsSymbolLayer.PropertyDashPatternOffset.is_monkey_patched = True
QgsSymbolLayer.PropertyDashPatternOffset.__doc__ = "Dash pattern offset,"
QgsSymbolLayer.PropertyTrimStart = QgsSymbolLayer.Property.TrimStart
QgsSymbolLayer.Property.PropertyTrimStart = QgsSymbolLayer.Property.TrimStart
QgsSymbolLayer.PropertyTrimStart.is_monkey_patched = True
QgsSymbolLayer.PropertyTrimStart.__doc__ = "Trim distance from start of line (since QGIS 3.20)"
QgsSymbolLayer.PropertyTrimEnd = QgsSymbolLayer.Property.TrimEnd
QgsSymbolLayer.Property.PropertyTrimEnd = QgsSymbolLayer.Property.TrimEnd
QgsSymbolLayer.PropertyTrimEnd.is_monkey_patched = True
QgsSymbolLayer.PropertyTrimEnd.__doc__ = "Trim distance from end of line (since QGIS 3.20)"
QgsSymbolLayer.PropertyLineStartWidthValue = QgsSymbolLayer.Property.LineStartWidthValue
QgsSymbolLayer.Property.PropertyLineStartWidthValue = QgsSymbolLayer.Property.LineStartWidthValue
QgsSymbolLayer.PropertyLineStartWidthValue.is_monkey_patched = True
QgsSymbolLayer.PropertyLineStartWidthValue.__doc__ = "Start line width for interpolated line renderer (since QGIS 3.22)"
QgsSymbolLayer.PropertyLineEndWidthValue = QgsSymbolLayer.Property.LineEndWidthValue
QgsSymbolLayer.Property.PropertyLineEndWidthValue = QgsSymbolLayer.Property.LineEndWidthValue
QgsSymbolLayer.PropertyLineEndWidthValue.is_monkey_patched = True
QgsSymbolLayer.PropertyLineEndWidthValue.__doc__ = "End line width for interpolated line renderer (since QGIS 3.22)"
QgsSymbolLayer.PropertyLineStartColorValue = QgsSymbolLayer.Property.LineStartColorValue
QgsSymbolLayer.Property.PropertyLineStartColorValue = QgsSymbolLayer.Property.LineStartColorValue
QgsSymbolLayer.PropertyLineStartColorValue.is_monkey_patched = True
QgsSymbolLayer.PropertyLineStartColorValue.__doc__ = "Start line color for interpolated line renderer (since QGIS 3.22)"
QgsSymbolLayer.PropertyLineEndColorValue = QgsSymbolLayer.Property.LineEndColorValue
QgsSymbolLayer.Property.PropertyLineEndColorValue = QgsSymbolLayer.Property.LineEndColorValue
QgsSymbolLayer.PropertyLineEndColorValue.is_monkey_patched = True
QgsSymbolLayer.PropertyLineEndColorValue.__doc__ = "End line color for interpolated line renderer (since QGIS 3.22)"
QgsSymbolLayer.PropertyMarkerClipping = QgsSymbolLayer.Property.MarkerClipping
QgsSymbolLayer.Property.PropertyMarkerClipping = QgsSymbolLayer.Property.MarkerClipping
QgsSymbolLayer.PropertyMarkerClipping.is_monkey_patched = True
QgsSymbolLayer.PropertyMarkerClipping.__doc__ = "Marker clipping mode (since QGIS 3.24)"
QgsSymbolLayer.PropertyRandomOffsetX = QgsSymbolLayer.Property.RandomOffsetX
QgsSymbolLayer.Property.PropertyRandomOffsetX = QgsSymbolLayer.Property.RandomOffsetX
QgsSymbolLayer.PropertyRandomOffsetX.is_monkey_patched = True
QgsSymbolLayer.PropertyRandomOffsetX.__doc__ = "Random offset X (since QGIS 3.24)"
QgsSymbolLayer.PropertyRandomOffsetY = QgsSymbolLayer.Property.RandomOffsetY
QgsSymbolLayer.Property.PropertyRandomOffsetY = QgsSymbolLayer.Property.RandomOffsetY
QgsSymbolLayer.PropertyRandomOffsetY.is_monkey_patched = True
QgsSymbolLayer.PropertyRandomOffsetY.__doc__ = "Random offset Y (since QGIS 3.24)"
QgsSymbolLayer.PropertyLineClipping = QgsSymbolLayer.Property.LineClipping
QgsSymbolLayer.Property.PropertyLineClipping = QgsSymbolLayer.Property.LineClipping
QgsSymbolLayer.PropertyLineClipping.is_monkey_patched = True
QgsSymbolLayer.PropertyLineClipping.__doc__ = "Line clipping mode (since QGIS 3.24)"
QgsSymbolLayer.Property.__doc__ = "Data definable properties.\n\n" + '* ``PropertySize``: ' + QgsSymbolLayer.Property.Size.__doc__ + '\n' + '* ``PropertyAngle``: ' + QgsSymbolLayer.Property.Angle.__doc__ + '\n' + '* ``PropertyName``: ' + QgsSymbolLayer.Property.Name.__doc__ + '\n' + '* ``PropertyFillColor``: ' + QgsSymbolLayer.Property.FillColor.__doc__ + '\n' + '* ``PropertyStrokeColor``: ' + QgsSymbolLayer.Property.StrokeColor.__doc__ + '\n' + '* ``PropertyStrokeWidth``: ' + QgsSymbolLayer.Property.StrokeWidth.__doc__ + '\n' + '* ``PropertyStrokeStyle``: ' + QgsSymbolLayer.Property.StrokeStyle.__doc__ + '\n' + '* ``PropertyOffset``: ' + QgsSymbolLayer.Property.Offset.__doc__ + '\n' + '* ``PropertyCharacter``: ' + QgsSymbolLayer.Property.Character.__doc__ + '\n' + '* ``PropertyWidth``: ' + QgsSymbolLayer.Property.Width.__doc__ + '\n' + '* ``PropertyHeight``: ' + QgsSymbolLayer.Property.Height.__doc__ + '\n' + '* ``PropertyPreserveAspectRatio``: ' + QgsSymbolLayer.Property.PreserveAspectRatio.__doc__ + '\n' + '* ``PropertyFillStyle``: ' + QgsSymbolLayer.Property.FillStyle.__doc__ + '\n' + '* ``PropertyJoinStyle``: ' + QgsSymbolLayer.Property.JoinStyle.__doc__ + '\n' + '* ``PropertySecondaryColor``: ' + QgsSymbolLayer.Property.SecondaryColor.__doc__ + '\n' + '* ``PropertyLineAngle``: ' + QgsSymbolLayer.Property.LineAngle.__doc__ + '\n' + '* ``PropertyLineDistance``: ' + QgsSymbolLayer.Property.LineDistance.__doc__ + '\n' + '* ``PropertyGradientType``: ' + QgsSymbolLayer.Property.GradientType.__doc__ + '\n' + '* ``PropertyCoordinateMode``: ' + QgsSymbolLayer.Property.CoordinateMode.__doc__ + '\n' + '* ``PropertyGradientSpread``: ' + QgsSymbolLayer.Property.GradientSpread.__doc__ + '\n' + '* ``PropertyGradientReference1X``: ' + QgsSymbolLayer.Property.GradientReference1X.__doc__ + '\n' + '* ``PropertyGradientReference1Y``: ' + QgsSymbolLayer.Property.GradientReference1Y.__doc__ + '\n' + '* ``PropertyGradientReference2X``: ' + QgsSymbolLayer.Property.GradientReference2X.__doc__ + '\n' + '* ``PropertyGradientReference2Y``: ' + QgsSymbolLayer.Property.GradientReference2Y.__doc__ + '\n' + '* ``PropertyGradientReference1IsCentroid``: ' + QgsSymbolLayer.Property.GradientReference1IsCentroid.__doc__ + '\n' + '* ``PropertyGradientReference2IsCentroid``: ' + QgsSymbolLayer.Property.GradientReference2IsCentroid.__doc__ + '\n' + '* ``PropertyBlurRadius``: ' + QgsSymbolLayer.Property.BlurRadius.__doc__ + '\n' + '* ``PropertyShapeburstUseWholeShape``: ' + QgsSymbolLayer.Property.ShapeburstUseWholeShape.__doc__ + '\n' + '* ``PropertyShapeburstMaxDistance``: ' + QgsSymbolLayer.Property.ShapeburstMaxDistance.__doc__ + '\n' + '* ``PropertyShapeburstIgnoreRings``: ' + QgsSymbolLayer.Property.ShapeburstIgnoreRings.__doc__ + '\n' + '* ``PropertyFile``: ' + QgsSymbolLayer.Property.File.__doc__ + '\n' + '* ``PropertyDistanceX``: ' + QgsSymbolLayer.Property.DistanceX.__doc__ + '\n' + '* ``PropertyDistanceY``: ' + QgsSymbolLayer.Property.DistanceY.__doc__ + '\n' + '* ``PropertyDisplacementX``: ' + QgsSymbolLayer.Property.DisplacementX.__doc__ + '\n' + '* ``PropertyDisplacementY``: ' + QgsSymbolLayer.Property.DisplacementY.__doc__ + '\n' + '* ``PropertyOpacity``: ' + QgsSymbolLayer.Property.Opacity.__doc__ + '\n' + '* ``PropertyCustomDash``: ' + QgsSymbolLayer.Property.CustomDash.__doc__ + '\n' + '* ``PropertyCapStyle``: ' + QgsSymbolLayer.Property.CapStyle.__doc__ + '\n' + '* ``PropertyPlacement``: ' + QgsSymbolLayer.Property.Placement.__doc__ + '\n' + '* ``PropertyInterval``: ' + QgsSymbolLayer.Property.Interval.__doc__ + '\n' + '* ``PropertyOffsetAlongLine``: ' + QgsSymbolLayer.Property.OffsetAlongLine.__doc__ + '\n' + '* ``PropertyAverageAngleLength``: ' + QgsSymbolLayer.Property.AverageAngleLength.__doc__ + '\n' + '* ``PropertyHorizontalAnchor``: ' + QgsSymbolLayer.Property.HorizontalAnchor.__doc__ + '\n' + '* ``PropertyVerticalAnchor``: ' + QgsSymbolLayer.Property.VerticalAnchor.__doc__ + '\n' + '* ``PropertyLayerEnabled``: ' + QgsSymbolLayer.Property.LayerEnabled.__doc__ + '\n' + '* ``PropertyArrowWidth``: ' + QgsSymbolLayer.Property.ArrowWidth.__doc__ + '\n' + '* ``PropertyArrowStartWidth``: ' + QgsSymbolLayer.Property.ArrowStartWidth.__doc__ + '\n' + '* ``PropertyArrowHeadLength``: ' + QgsSymbolLayer.Property.ArrowHeadLength.__doc__ + '\n' + '* ``PropertyArrowHeadThickness``: ' + QgsSymbolLayer.Property.ArrowHeadThickness.__doc__ + '\n' + '* ``PropertyArrowHeadType``: ' + QgsSymbolLayer.Property.ArrowHeadType.__doc__ + '\n' + '* ``PropertyArrowType``: ' + QgsSymbolLayer.Property.ArrowType.__doc__ + '\n' + '* ``PropertyOffsetX``: ' + QgsSymbolLayer.Property.OffsetX.__doc__ + '\n' + '* ``PropertyOffsetY``: ' + QgsSymbolLayer.Property.OffsetY.__doc__ + '\n' + '* ``PropertyPointCount``: ' + QgsSymbolLayer.Property.PointCount.__doc__ + '\n' + '* ``PropertyRandomSeed``: ' + QgsSymbolLayer.Property.RandomSeed.__doc__ + '\n' + '* ``PropertyClipPoints``: ' + QgsSymbolLayer.Property.ClipPoints.__doc__ + '\n' + '* ``PropertyDensityArea``: ' + QgsSymbolLayer.Property.DensityArea.__doc__ + '\n' + '* ``PropertyFontFamily``: ' + QgsSymbolLayer.Property.FontFamily.__doc__ + '\n' + '* ``PropertyFontStyle``: ' + QgsSymbolLayer.Property.FontStyle.__doc__ + '\n' + '* ``PropertyDashPatternOffset``: ' + QgsSymbolLayer.Property.DashPatternOffset.__doc__ + '\n' + '* ``PropertyTrimStart``: ' + QgsSymbolLayer.Property.TrimStart.__doc__ + '\n' + '* ``PropertyTrimEnd``: ' + QgsSymbolLayer.Property.TrimEnd.__doc__ + '\n' + '* ``PropertyLineStartWidthValue``: ' + QgsSymbolLayer.Property.LineStartWidthValue.__doc__ + '\n' + '* ``PropertyLineEndWidthValue``: ' + QgsSymbolLayer.Property.LineEndWidthValue.__doc__ + '\n' + '* ``PropertyLineStartColorValue``: ' + QgsSymbolLayer.Property.LineStartColorValue.__doc__ + '\n' + '* ``PropertyLineEndColorValue``: ' + QgsSymbolLayer.Property.LineEndColorValue.__doc__ + '\n' + '* ``PropertyMarkerClipping``: ' + QgsSymbolLayer.Property.MarkerClipping.__doc__ + '\n' + '* ``PropertyRandomOffsetX``: ' + QgsSymbolLayer.Property.RandomOffsetX.__doc__ + '\n' + '* ``PropertyRandomOffsetY``: ' + QgsSymbolLayer.Property.RandomOffsetY.__doc__ + '\n' + '* ``PropertyLineClipping``: ' + QgsSymbolLayer.Property.LineClipping.__doc__
# --
QgsMarkerSymbolLayer.Left = QgsMarkerSymbolLayer.HorizontalAnchorPoint.Left
QgsMarkerSymbolLayer.HCenter = QgsMarkerSymbolLayer.HorizontalAnchorPoint.HCenter
QgsMarkerSymbolLayer.Right = QgsMarkerSymbolLayer.HorizontalAnchorPoint.Right
QgsMarkerSymbolLayer.Top = QgsMarkerSymbolLayer.VerticalAnchorPoint.Top
QgsMarkerSymbolLayer.VCenter = QgsMarkerSymbolLayer.VerticalAnchorPoint.VCenter
QgsMarkerSymbolLayer.Bottom = QgsMarkerSymbolLayer.VerticalAnchorPoint.Bottom
QgsLineSymbolLayer.AllRings = QgsLineSymbolLayer.RenderRingFilter.AllRings
QgsLineSymbolLayer.ExteriorRingOnly = QgsLineSymbolLayer.RenderRingFilter.ExteriorRingOnly
QgsLineSymbolLayer.InteriorRingsOnly = QgsLineSymbolLayer.RenderRingFilter.InteriorRingsOnly
QgsMarkerSymbolLayer._rotatedOffset = staticmethod(QgsMarkerSymbolLayer._rotatedOffset)
try:
    QgsSymbolLayer.__group__ = ['symbology']
except NameError:
    pass
try:
    QgsMarkerSymbolLayer.__group__ = ['symbology']
except NameError:
    pass
try:
    QgsLineSymbolLayer.__group__ = ['symbology']
except NameError:
    pass
try:
    QgsFillSymbolLayer.__group__ = ['symbology']
except NameError:
    pass
