# The following has been generated automatically from src/core/scalebar/qgsscalebarsettings.h
QgsScaleBarSettings.AlignLeft = QgsScaleBarSettings.Alignment.AlignLeft
QgsScaleBarSettings.AlignMiddle = QgsScaleBarSettings.Alignment.AlignMiddle
QgsScaleBarSettings.AlignRight = QgsScaleBarSettings.Alignment.AlignRight
QgsScaleBarSettings.SegmentSizeFixed = QgsScaleBarSettings.SegmentSizeMode.SegmentSizeFixed
QgsScaleBarSettings.SegmentSizeFitWidth = QgsScaleBarSettings.SegmentSizeMode.SegmentSizeFitWidth
QgsScaleBarSettings.LabelAboveSegment = QgsScaleBarSettings.LabelVerticalPlacement.LabelAboveSegment
QgsScaleBarSettings.LabelBelowSegment = QgsScaleBarSettings.LabelVerticalPlacement.LabelBelowSegment
QgsScaleBarSettings.LabelCenteredEdge = QgsScaleBarSettings.LabelHorizontalPlacement.LabelCenteredEdge
QgsScaleBarSettings.LabelCenteredSegment = QgsScaleBarSettings.LabelHorizontalPlacement.LabelCenteredSegment
