# The following has been generated automatically from src/core/validity/qgsvaliditycheckcontext.h
QgsValidityCheckContext.TypeLayoutContext = QgsValidityCheckContext.ContextType.TypeLayoutContext
QgsValidityCheckContext.TypeUserContext = QgsValidityCheckContext.ContextType.TypeUserContext
