FROM fedora:32
MAINTAINER Matthias Kuhn <matthias@opengis.ch>

RUN dnf -y install \
    bison \
    clang \
    clazy \
    exiv2-devel \
    fcgi-devel \
    flex \
    gdal-devel \
    geos-devel \
    gsl-devel \
    libpq-devel \
    libspatialite-devel \
    libzip-devel \
    ninja-build \
    proj-devel \
    protobuf-devel \
    protobuf-lite-devel \
    python3-pyqt5-sip \
    python3-qscintilla-qt5 \
    python3-qt5-devel \
    qca-qt5-devel \
    qscintilla-qt5-devel \
    qt5-qt3d-devel \
    qt5-qtbase-devel \
    qt5-qtlocation-devel \
    qt5-qtserialport-devel \
    qt5-qttools-static \
    qt5-qtwebkit-devel \
    qtkeychain-qt5-devel \
    qwt-qt5-devel \
    spatialindex-devel \
    sqlite-devel \
    unzip

