# The following has been generated automatically from src/core/qgsaggregatecalculator.h
# monkey patching scoped based enum
QgsAggregateCalculator.Count = QgsAggregateCalculator.Aggregate.Count
QgsAggregateCalculator.Count.is_monkey_patched = True
QgsAggregateCalculator.Count.__doc__ = "Count"
QgsAggregateCalculator.CountDistinct = QgsAggregateCalculator.Aggregate.CountDistinct
QgsAggregateCalculator.CountDistinct.is_monkey_patched = True
QgsAggregateCalculator.CountDistinct.__doc__ = "Number of distinct values"
QgsAggregateCalculator.CountMissing = QgsAggregateCalculator.Aggregate.CountMissing
QgsAggregateCalculator.CountMissing.is_monkey_patched = True
QgsAggregateCalculator.CountMissing.__doc__ = "Number of missing (null) values"
QgsAggregateCalculator.Min = QgsAggregateCalculator.Aggregate.Min
QgsAggregateCalculator.Min.is_monkey_patched = True
QgsAggregateCalculator.Min.__doc__ = "Min of values"
QgsAggregateCalculator.Max = QgsAggregateCalculator.Aggregate.Max
QgsAggregateCalculator.Max.is_monkey_patched = True
QgsAggregateCalculator.Max.__doc__ = "Max of values"
QgsAggregateCalculator.Sum = QgsAggregateCalculator.Aggregate.Sum
QgsAggregateCalculator.Sum.is_monkey_patched = True
QgsAggregateCalculator.Sum.__doc__ = "Sum of values"
QgsAggregateCalculator.Mean = QgsAggregateCalculator.Aggregate.Mean
QgsAggregateCalculator.Mean.is_monkey_patched = True
QgsAggregateCalculator.Mean.__doc__ = "Mean of values (numeric fields only)"
QgsAggregateCalculator.Median = QgsAggregateCalculator.Aggregate.Median
QgsAggregateCalculator.Median.is_monkey_patched = True
QgsAggregateCalculator.Median.__doc__ = "Median of values (numeric fields only)"
QgsAggregateCalculator.StDev = QgsAggregateCalculator.Aggregate.StDev
QgsAggregateCalculator.StDev.is_monkey_patched = True
QgsAggregateCalculator.StDev.__doc__ = "Standard deviation of values (numeric fields only)"
QgsAggregateCalculator.StDevSample = QgsAggregateCalculator.Aggregate.StDevSample
QgsAggregateCalculator.StDevSample.is_monkey_patched = True
QgsAggregateCalculator.StDevSample.__doc__ = "Sample standard deviation of values (numeric fields only)"
QgsAggregateCalculator.Range = QgsAggregateCalculator.Aggregate.Range
QgsAggregateCalculator.Range.is_monkey_patched = True
QgsAggregateCalculator.Range.__doc__ = "Range of values (max - min) (numeric and datetime fields only)"
QgsAggregateCalculator.Minority = QgsAggregateCalculator.Aggregate.Minority
QgsAggregateCalculator.Minority.is_monkey_patched = True
QgsAggregateCalculator.Minority.__doc__ = "Minority of values"
QgsAggregateCalculator.Majority = QgsAggregateCalculator.Aggregate.Majority
QgsAggregateCalculator.Majority.is_monkey_patched = True
QgsAggregateCalculator.Majority.__doc__ = "Majority of values"
QgsAggregateCalculator.FirstQuartile = QgsAggregateCalculator.Aggregate.FirstQuartile
QgsAggregateCalculator.FirstQuartile.is_monkey_patched = True
QgsAggregateCalculator.FirstQuartile.__doc__ = "First quartile (numeric fields only)"
QgsAggregateCalculator.ThirdQuartile = QgsAggregateCalculator.Aggregate.ThirdQuartile
QgsAggregateCalculator.ThirdQuartile.is_monkey_patched = True
QgsAggregateCalculator.ThirdQuartile.__doc__ = "Third quartile (numeric fields only)"
QgsAggregateCalculator.InterQuartileRange = QgsAggregateCalculator.Aggregate.InterQuartileRange
QgsAggregateCalculator.InterQuartileRange.is_monkey_patched = True
QgsAggregateCalculator.InterQuartileRange.__doc__ = "Inter quartile range (IQR) (numeric fields only)"
QgsAggregateCalculator.StringMinimumLength = QgsAggregateCalculator.Aggregate.StringMinimumLength
QgsAggregateCalculator.StringMinimumLength.is_monkey_patched = True
QgsAggregateCalculator.StringMinimumLength.__doc__ = "Minimum length of string (string fields only)"
QgsAggregateCalculator.StringMaximumLength = QgsAggregateCalculator.Aggregate.StringMaximumLength
QgsAggregateCalculator.StringMaximumLength.is_monkey_patched = True
QgsAggregateCalculator.StringMaximumLength.__doc__ = "Maximum length of string (string fields only)"
QgsAggregateCalculator.StringConcatenate = QgsAggregateCalculator.Aggregate.StringConcatenate
QgsAggregateCalculator.StringConcatenate.is_monkey_patched = True
QgsAggregateCalculator.StringConcatenate.__doc__ = "Concatenate values with a joining string (string fields only). Specify the delimiter using setDelimiter()."
QgsAggregateCalculator.GeometryCollect = QgsAggregateCalculator.Aggregate.GeometryCollect
QgsAggregateCalculator.GeometryCollect.is_monkey_patched = True
QgsAggregateCalculator.GeometryCollect.__doc__ = "Create a multipart geometry from aggregated geometries"
QgsAggregateCalculator.ArrayAggregate = QgsAggregateCalculator.Aggregate.ArrayAggregate
QgsAggregateCalculator.ArrayAggregate.is_monkey_patched = True
QgsAggregateCalculator.ArrayAggregate.__doc__ = "Create an array of values"
QgsAggregateCalculator.StringConcatenateUnique = QgsAggregateCalculator.Aggregate.StringConcatenateUnique
QgsAggregateCalculator.StringConcatenateUnique.is_monkey_patched = True
QgsAggregateCalculator.StringConcatenateUnique.__doc__ = "Concatenate unique values with a joining string (string fields only). Specify the delimiter using setDelimiter()."
QgsAggregateCalculator.Aggregate.__doc__ = "Available aggregates to calculate. Not all aggregates are available for all field\ntypes.\n\n" + '* ``Count``: ' + QgsAggregateCalculator.Aggregate.Count.__doc__ + '\n' + '* ``CountDistinct``: ' + QgsAggregateCalculator.Aggregate.CountDistinct.__doc__ + '\n' + '* ``CountMissing``: ' + QgsAggregateCalculator.Aggregate.CountMissing.__doc__ + '\n' + '* ``Min``: ' + QgsAggregateCalculator.Aggregate.Min.__doc__ + '\n' + '* ``Max``: ' + QgsAggregateCalculator.Aggregate.Max.__doc__ + '\n' + '* ``Sum``: ' + QgsAggregateCalculator.Aggregate.Sum.__doc__ + '\n' + '* ``Mean``: ' + QgsAggregateCalculator.Aggregate.Mean.__doc__ + '\n' + '* ``Median``: ' + QgsAggregateCalculator.Aggregate.Median.__doc__ + '\n' + '* ``StDev``: ' + QgsAggregateCalculator.Aggregate.StDev.__doc__ + '\n' + '* ``StDevSample``: ' + QgsAggregateCalculator.Aggregate.StDevSample.__doc__ + '\n' + '* ``Range``: ' + QgsAggregateCalculator.Aggregate.Range.__doc__ + '\n' + '* ``Minority``: ' + QgsAggregateCalculator.Aggregate.Minority.__doc__ + '\n' + '* ``Majority``: ' + QgsAggregateCalculator.Aggregate.Majority.__doc__ + '\n' + '* ``FirstQuartile``: ' + QgsAggregateCalculator.Aggregate.FirstQuartile.__doc__ + '\n' + '* ``ThirdQuartile``: ' + QgsAggregateCalculator.Aggregate.ThirdQuartile.__doc__ + '\n' + '* ``InterQuartileRange``: ' + QgsAggregateCalculator.Aggregate.InterQuartileRange.__doc__ + '\n' + '* ``StringMinimumLength``: ' + QgsAggregateCalculator.Aggregate.StringMinimumLength.__doc__ + '\n' + '* ``StringMaximumLength``: ' + QgsAggregateCalculator.Aggregate.StringMaximumLength.__doc__ + '\n' + '* ``StringConcatenate``: ' + QgsAggregateCalculator.Aggregate.StringConcatenate.__doc__ + '\n' + '* ``GeometryCollect``: ' + QgsAggregateCalculator.Aggregate.GeometryCollect.__doc__ + '\n' + '* ``ArrayAggregate``: ' + QgsAggregateCalculator.Aggregate.ArrayAggregate.__doc__ + '\n' + '* ``StringConcatenateUnique``: ' + QgsAggregateCalculator.Aggregate.StringConcatenateUnique.__doc__
# --
