# The following has been generated automatically from src/core/classification/qgsclassificationmethod.h
QgsClassificationMethod.rangesToBreaks = staticmethod(QgsClassificationMethod.rangesToBreaks)
QgsClassificationMethod.create = staticmethod(QgsClassificationMethod.create)
QgsClassificationMethod.makeBreaksSymmetric = staticmethod(QgsClassificationMethod.makeBreaksSymmetric)
