# The following has been generated automatically from src/core/symbology/qgscptcityarchive.h
QgsCptCityArchive.defaultBaseDir = staticmethod(QgsCptCityArchive.defaultBaseDir)
QgsCptCityArchive.findFileName = staticmethod(QgsCptCityArchive.findFileName)
QgsCptCityArchive.copyingInfo = staticmethod(QgsCptCityArchive.copyingInfo)
QgsCptCityArchive.description = staticmethod(QgsCptCityArchive.description)
QgsCptCityArchive.initArchives = staticmethod(QgsCptCityArchive.initArchives)
QgsCptCityArchive.initArchive = staticmethod(QgsCptCityArchive.initArchive)
QgsCptCityArchive.initDefaultArchive = staticmethod(QgsCptCityArchive.initDefaultArchive)
QgsCptCityArchive.clearArchives = staticmethod(QgsCptCityArchive.clearArchives)
QgsCptCityArchive.defaultArchive = staticmethod(QgsCptCityArchive.defaultArchive)
QgsCptCityArchive.archiveRegistry = staticmethod(QgsCptCityArchive.archiveRegistry)
QgsCptCityDataItem.findItem = staticmethod(QgsCptCityDataItem.findItem)
QgsCptCityDirectoryItem.dataItem = staticmethod(QgsCptCityDirectoryItem.dataItem)
