# The following has been generated automatically from src/core/layout/qgslayoutobject.h
# monkey patching scoped based enum
QgsLayoutObject.NoProperty = QgsLayoutObject.DataDefinedProperty.NoProperty
QgsLayoutObject.NoProperty.is_monkey_patched = True
QgsLayoutObject.NoProperty.__doc__ = "No property"
QgsLayoutObject.AllProperties = QgsLayoutObject.DataDefinedProperty.AllProperties
QgsLayoutObject.AllProperties.is_monkey_patched = True
QgsLayoutObject.AllProperties.__doc__ = "All properties for item"
QgsLayoutObject.TestProperty = QgsLayoutObject.DataDefinedProperty.TestProperty
QgsLayoutObject.TestProperty.is_monkey_patched = True
QgsLayoutObject.TestProperty.__doc__ = "Dummy property with no effect on item"
QgsLayoutObject.PresetPaperSize = QgsLayoutObject.DataDefinedProperty.PresetPaperSize
QgsLayoutObject.PresetPaperSize.is_monkey_patched = True
QgsLayoutObject.PresetPaperSize.__doc__ = "Preset paper size for composition"
QgsLayoutObject.PaperWidth = QgsLayoutObject.DataDefinedProperty.PaperWidth
QgsLayoutObject.PaperWidth.is_monkey_patched = True
QgsLayoutObject.PaperWidth.__doc__ = "Paper width (deprecated)"
QgsLayoutObject.PaperHeight = QgsLayoutObject.DataDefinedProperty.PaperHeight
QgsLayoutObject.PaperHeight.is_monkey_patched = True
QgsLayoutObject.PaperHeight.__doc__ = "Paper height (deprecated)"
QgsLayoutObject.NumPages = QgsLayoutObject.DataDefinedProperty.NumPages
QgsLayoutObject.NumPages.is_monkey_patched = True
QgsLayoutObject.NumPages.__doc__ = "Number of pages in composition (deprecated)"
QgsLayoutObject.PaperOrientation = QgsLayoutObject.DataDefinedProperty.PaperOrientation
QgsLayoutObject.PaperOrientation.is_monkey_patched = True
QgsLayoutObject.PaperOrientation.__doc__ = "Paper orientation"
QgsLayoutObject.PageNumber = QgsLayoutObject.DataDefinedProperty.PageNumber
QgsLayoutObject.PageNumber.is_monkey_patched = True
QgsLayoutObject.PageNumber.__doc__ = "Page number for item placement"
QgsLayoutObject.PositionX = QgsLayoutObject.DataDefinedProperty.PositionX
QgsLayoutObject.PositionX.is_monkey_patched = True
QgsLayoutObject.PositionX.__doc__ = "X position on page"
QgsLayoutObject.PositionY = QgsLayoutObject.DataDefinedProperty.PositionY
QgsLayoutObject.PositionY.is_monkey_patched = True
QgsLayoutObject.PositionY.__doc__ = "Y position on page"
QgsLayoutObject.ItemWidth = QgsLayoutObject.DataDefinedProperty.ItemWidth
QgsLayoutObject.ItemWidth.is_monkey_patched = True
QgsLayoutObject.ItemWidth.__doc__ = "Width of item"
QgsLayoutObject.ItemHeight = QgsLayoutObject.DataDefinedProperty.ItemHeight
QgsLayoutObject.ItemHeight.is_monkey_patched = True
QgsLayoutObject.ItemHeight.__doc__ = "Height of item"
QgsLayoutObject.ItemRotation = QgsLayoutObject.DataDefinedProperty.ItemRotation
QgsLayoutObject.ItemRotation.is_monkey_patched = True
QgsLayoutObject.ItemRotation.__doc__ = "Rotation of item"
QgsLayoutObject.Transparency = QgsLayoutObject.DataDefinedProperty.Transparency
QgsLayoutObject.Transparency.is_monkey_patched = True
QgsLayoutObject.Transparency.__doc__ = "Item transparency (deprecated)"
QgsLayoutObject.Opacity = QgsLayoutObject.DataDefinedProperty.Opacity
QgsLayoutObject.Opacity.is_monkey_patched = True
QgsLayoutObject.Opacity.__doc__ = "Item opacity"
QgsLayoutObject.BlendMode = QgsLayoutObject.DataDefinedProperty.BlendMode
QgsLayoutObject.BlendMode.is_monkey_patched = True
QgsLayoutObject.BlendMode.__doc__ = "Item blend mode"
QgsLayoutObject.ExcludeFromExports = QgsLayoutObject.DataDefinedProperty.ExcludeFromExports
QgsLayoutObject.ExcludeFromExports.is_monkey_patched = True
QgsLayoutObject.ExcludeFromExports.__doc__ = "Exclude item from exports"
QgsLayoutObject.FrameColor = QgsLayoutObject.DataDefinedProperty.FrameColor
QgsLayoutObject.FrameColor.is_monkey_patched = True
QgsLayoutObject.FrameColor.__doc__ = "Item frame color"
QgsLayoutObject.BackgroundColor = QgsLayoutObject.DataDefinedProperty.BackgroundColor
QgsLayoutObject.BackgroundColor.is_monkey_patched = True
QgsLayoutObject.BackgroundColor.__doc__ = "Item background color"
QgsLayoutObject.MarginLeft = QgsLayoutObject.DataDefinedProperty.MarginLeft
QgsLayoutObject.MarginLeft.is_monkey_patched = True
QgsLayoutObject.MarginLeft.__doc__ = "Left margin (since QGIS 3.30)"
QgsLayoutObject.MarginTop = QgsLayoutObject.DataDefinedProperty.MarginTop
QgsLayoutObject.MarginTop.is_monkey_patched = True
QgsLayoutObject.MarginTop.__doc__ = "Top margin (since QGIS 3.30)"
QgsLayoutObject.MarginRight = QgsLayoutObject.DataDefinedProperty.MarginRight
QgsLayoutObject.MarginRight.is_monkey_patched = True
QgsLayoutObject.MarginRight.__doc__ = "Right margin (since QGIS 3.30)"
QgsLayoutObject.MarginBottom = QgsLayoutObject.DataDefinedProperty.MarginBottom
QgsLayoutObject.MarginBottom.is_monkey_patched = True
QgsLayoutObject.MarginBottom.__doc__ = "Bottom margin (since QGIS 3.30)"
QgsLayoutObject.MapRotation = QgsLayoutObject.DataDefinedProperty.MapRotation
QgsLayoutObject.MapRotation.is_monkey_patched = True
QgsLayoutObject.MapRotation.__doc__ = "Map rotation"
QgsLayoutObject.MapScale = QgsLayoutObject.DataDefinedProperty.MapScale
QgsLayoutObject.MapScale.is_monkey_patched = True
QgsLayoutObject.MapScale.__doc__ = "Map scale"
QgsLayoutObject.MapXMin = QgsLayoutObject.DataDefinedProperty.MapXMin
QgsLayoutObject.MapXMin.is_monkey_patched = True
QgsLayoutObject.MapXMin.__doc__ = "Map extent x minimum"
QgsLayoutObject.MapYMin = QgsLayoutObject.DataDefinedProperty.MapYMin
QgsLayoutObject.MapYMin.is_monkey_patched = True
QgsLayoutObject.MapYMin.__doc__ = "Map extent y minimum"
QgsLayoutObject.MapXMax = QgsLayoutObject.DataDefinedProperty.MapXMax
QgsLayoutObject.MapXMax.is_monkey_patched = True
QgsLayoutObject.MapXMax.__doc__ = "Map extent x maximum"
QgsLayoutObject.MapYMax = QgsLayoutObject.DataDefinedProperty.MapYMax
QgsLayoutObject.MapYMax.is_monkey_patched = True
QgsLayoutObject.MapYMax.__doc__ = "Map extent y maximum"
QgsLayoutObject.MapAtlasMargin = QgsLayoutObject.DataDefinedProperty.MapAtlasMargin
QgsLayoutObject.MapAtlasMargin.is_monkey_patched = True
QgsLayoutObject.MapAtlasMargin.__doc__ = "Map atlas margin"
QgsLayoutObject.MapLayers = QgsLayoutObject.DataDefinedProperty.MapLayers
QgsLayoutObject.MapLayers.is_monkey_patched = True
QgsLayoutObject.MapLayers.__doc__ = "Map layer set"
QgsLayoutObject.MapStylePreset = QgsLayoutObject.DataDefinedProperty.MapStylePreset
QgsLayoutObject.MapStylePreset.is_monkey_patched = True
QgsLayoutObject.MapStylePreset.__doc__ = "Layer and style map theme"
QgsLayoutObject.MapLabelMargin = QgsLayoutObject.DataDefinedProperty.MapLabelMargin
QgsLayoutObject.MapLabelMargin.is_monkey_patched = True
QgsLayoutObject.MapLabelMargin.__doc__ = "Map label margin"
QgsLayoutObject.MapGridEnabled = QgsLayoutObject.DataDefinedProperty.MapGridEnabled
QgsLayoutObject.MapGridEnabled.is_monkey_patched = True
QgsLayoutObject.MapGridEnabled.__doc__ = "Map grid enabled"
QgsLayoutObject.MapGridIntervalX = QgsLayoutObject.DataDefinedProperty.MapGridIntervalX
QgsLayoutObject.MapGridIntervalX.is_monkey_patched = True
QgsLayoutObject.MapGridIntervalX.__doc__ = "Map grid interval X"
QgsLayoutObject.MapGridIntervalY = QgsLayoutObject.DataDefinedProperty.MapGridIntervalY
QgsLayoutObject.MapGridIntervalY.is_monkey_patched = True
QgsLayoutObject.MapGridIntervalY.__doc__ = "Map grid interval Y"
QgsLayoutObject.MapGridOffsetX = QgsLayoutObject.DataDefinedProperty.MapGridOffsetX
QgsLayoutObject.MapGridOffsetX.is_monkey_patched = True
QgsLayoutObject.MapGridOffsetX.__doc__ = "Map grid offset X"
QgsLayoutObject.MapGridOffsetY = QgsLayoutObject.DataDefinedProperty.MapGridOffsetY
QgsLayoutObject.MapGridOffsetY.is_monkey_patched = True
QgsLayoutObject.MapGridOffsetY.__doc__ = "Map grid offset Y"
QgsLayoutObject.MapGridFrameSize = QgsLayoutObject.DataDefinedProperty.MapGridFrameSize
QgsLayoutObject.MapGridFrameSize.is_monkey_patched = True
QgsLayoutObject.MapGridFrameSize.__doc__ = "Map grid frame size"
QgsLayoutObject.MapGridFrameMargin = QgsLayoutObject.DataDefinedProperty.MapGridFrameMargin
QgsLayoutObject.MapGridFrameMargin.is_monkey_patched = True
QgsLayoutObject.MapGridFrameMargin.__doc__ = "Map grid frame margin"
QgsLayoutObject.MapGridLabelDistance = QgsLayoutObject.DataDefinedProperty.MapGridLabelDistance
QgsLayoutObject.MapGridLabelDistance.is_monkey_patched = True
QgsLayoutObject.MapGridLabelDistance.__doc__ = "Map grid label distance"
QgsLayoutObject.MapGridCrossSize = QgsLayoutObject.DataDefinedProperty.MapGridCrossSize
QgsLayoutObject.MapGridCrossSize.is_monkey_patched = True
QgsLayoutObject.MapGridCrossSize.__doc__ = "Map grid cross size"
QgsLayoutObject.MapGridFrameLineThickness = QgsLayoutObject.DataDefinedProperty.MapGridFrameLineThickness
QgsLayoutObject.MapGridFrameLineThickness.is_monkey_patched = True
QgsLayoutObject.MapGridFrameLineThickness.__doc__ = "Map grid frame line thickness"
QgsLayoutObject.MapGridAnnotationDisplayLeft = QgsLayoutObject.DataDefinedProperty.MapGridAnnotationDisplayLeft
QgsLayoutObject.MapGridAnnotationDisplayLeft.is_monkey_patched = True
QgsLayoutObject.MapGridAnnotationDisplayLeft.__doc__ = "Map annotation display left"
QgsLayoutObject.MapGridAnnotationDisplayRight = QgsLayoutObject.DataDefinedProperty.MapGridAnnotationDisplayRight
QgsLayoutObject.MapGridAnnotationDisplayRight.is_monkey_patched = True
QgsLayoutObject.MapGridAnnotationDisplayRight.__doc__ = "Map annotation display right"
QgsLayoutObject.MapGridAnnotationDisplayTop = QgsLayoutObject.DataDefinedProperty.MapGridAnnotationDisplayTop
QgsLayoutObject.MapGridAnnotationDisplayTop.is_monkey_patched = True
QgsLayoutObject.MapGridAnnotationDisplayTop.__doc__ = "Map annotation display top"
QgsLayoutObject.MapGridAnnotationDisplayBottom = QgsLayoutObject.DataDefinedProperty.MapGridAnnotationDisplayBottom
QgsLayoutObject.MapGridAnnotationDisplayBottom.is_monkey_patched = True
QgsLayoutObject.MapGridAnnotationDisplayBottom.__doc__ = "Map annotation display bottom"
QgsLayoutObject.MapGridFrameDivisionsLeft = QgsLayoutObject.DataDefinedProperty.MapGridFrameDivisionsLeft
QgsLayoutObject.MapGridFrameDivisionsLeft.is_monkey_patched = True
QgsLayoutObject.MapGridFrameDivisionsLeft.__doc__ = "Map frame division display left"
QgsLayoutObject.MapGridFrameDivisionsRight = QgsLayoutObject.DataDefinedProperty.MapGridFrameDivisionsRight
QgsLayoutObject.MapGridFrameDivisionsRight.is_monkey_patched = True
QgsLayoutObject.MapGridFrameDivisionsRight.__doc__ = "Map frame division display right"
QgsLayoutObject.MapGridFrameDivisionsTop = QgsLayoutObject.DataDefinedProperty.MapGridFrameDivisionsTop
QgsLayoutObject.MapGridFrameDivisionsTop.is_monkey_patched = True
QgsLayoutObject.MapGridFrameDivisionsTop.__doc__ = "Map frame division display top"
QgsLayoutObject.MapGridFrameDivisionsBottom = QgsLayoutObject.DataDefinedProperty.MapGridFrameDivisionsBottom
QgsLayoutObject.MapGridFrameDivisionsBottom.is_monkey_patched = True
QgsLayoutObject.MapGridFrameDivisionsBottom.__doc__ = "Map frame division display bottom"
QgsLayoutObject.MapCrs = QgsLayoutObject.DataDefinedProperty.MapCrs
QgsLayoutObject.MapCrs.is_monkey_patched = True
QgsLayoutObject.MapCrs.__doc__ = "Map CRS"
QgsLayoutObject.StartDateTime = QgsLayoutObject.DataDefinedProperty.StartDateTime
QgsLayoutObject.StartDateTime.is_monkey_patched = True
QgsLayoutObject.StartDateTime.__doc__ = "Temporal range's start DateTime"
QgsLayoutObject.EndDateTime = QgsLayoutObject.DataDefinedProperty.EndDateTime
QgsLayoutObject.EndDateTime.is_monkey_patched = True
QgsLayoutObject.EndDateTime.__doc__ = "Temporal range's end DateTime"
QgsLayoutObject.MapZRangeLower = QgsLayoutObject.DataDefinedProperty.MapZRangeLower
QgsLayoutObject.MapZRangeLower.is_monkey_patched = True
QgsLayoutObject.MapZRangeLower.__doc__ = "Map frame Z-range lower value (since QGIS 3.38)"
QgsLayoutObject.MapZRangeUpper = QgsLayoutObject.DataDefinedProperty.MapZRangeUpper
QgsLayoutObject.MapZRangeUpper.is_monkey_patched = True
QgsLayoutObject.MapZRangeUpper.__doc__ = "Map frame Z-range lower value (since QGIS 3.38)"
QgsLayoutObject.PictureSource = QgsLayoutObject.DataDefinedProperty.PictureSource
QgsLayoutObject.PictureSource.is_monkey_patched = True
QgsLayoutObject.PictureSource.__doc__ = "Picture source url"
QgsLayoutObject.PictureSvgBackgroundColor = QgsLayoutObject.DataDefinedProperty.PictureSvgBackgroundColor
QgsLayoutObject.PictureSvgBackgroundColor.is_monkey_patched = True
QgsLayoutObject.PictureSvgBackgroundColor.__doc__ = "SVG background color"
QgsLayoutObject.PictureSvgStrokeColor = QgsLayoutObject.DataDefinedProperty.PictureSvgStrokeColor
QgsLayoutObject.PictureSvgStrokeColor.is_monkey_patched = True
QgsLayoutObject.PictureSvgStrokeColor.__doc__ = "SVG stroke color"
QgsLayoutObject.PictureSvgStrokeWidth = QgsLayoutObject.DataDefinedProperty.PictureSvgStrokeWidth
QgsLayoutObject.PictureSvgStrokeWidth.is_monkey_patched = True
QgsLayoutObject.PictureSvgStrokeWidth.__doc__ = "SVG stroke width"
QgsLayoutObject.SourceUrl = QgsLayoutObject.DataDefinedProperty.SourceUrl
QgsLayoutObject.SourceUrl.is_monkey_patched = True
QgsLayoutObject.SourceUrl.__doc__ = "Html source url"
QgsLayoutObject.LegendTitle = QgsLayoutObject.DataDefinedProperty.LegendTitle
QgsLayoutObject.LegendTitle.is_monkey_patched = True
QgsLayoutObject.LegendTitle.__doc__ = "Legend title"
QgsLayoutObject.LegendColumnCount = QgsLayoutObject.DataDefinedProperty.LegendColumnCount
QgsLayoutObject.LegendColumnCount.is_monkey_patched = True
QgsLayoutObject.LegendColumnCount.__doc__ = "Legend column count"
QgsLayoutObject.ScalebarLeftSegments = QgsLayoutObject.DataDefinedProperty.ScalebarLeftSegments
QgsLayoutObject.ScalebarLeftSegments.is_monkey_patched = True
QgsLayoutObject.ScalebarLeftSegments.__doc__ = "Number of segments on the left of 0 (since QGIS 3.26)"
QgsLayoutObject.ScalebarRightSegments = QgsLayoutObject.DataDefinedProperty.ScalebarRightSegments
QgsLayoutObject.ScalebarRightSegments.is_monkey_patched = True
QgsLayoutObject.ScalebarRightSegments.__doc__ = "Number of segments on the right of 0 (since QGIS 3.26)"
QgsLayoutObject.ScalebarSegmentWidth = QgsLayoutObject.DataDefinedProperty.ScalebarSegmentWidth
QgsLayoutObject.ScalebarSegmentWidth.is_monkey_patched = True
QgsLayoutObject.ScalebarSegmentWidth.__doc__ = "Scalebar width in map units of a single segment (since QGIS 3.26)"
QgsLayoutObject.ScalebarMinimumWidth = QgsLayoutObject.DataDefinedProperty.ScalebarMinimumWidth
QgsLayoutObject.ScalebarMinimumWidth.is_monkey_patched = True
QgsLayoutObject.ScalebarMinimumWidth.__doc__ = "Scalebar segment minimum width (since QGIS 3.26)"
QgsLayoutObject.ScalebarMaximumWidth = QgsLayoutObject.DataDefinedProperty.ScalebarMaximumWidth
QgsLayoutObject.ScalebarMaximumWidth.is_monkey_patched = True
QgsLayoutObject.ScalebarMaximumWidth.__doc__ = "Scalebar segment maximum width (since QGIS 3.26)"
QgsLayoutObject.ScalebarHeight = QgsLayoutObject.DataDefinedProperty.ScalebarHeight
QgsLayoutObject.ScalebarHeight.is_monkey_patched = True
QgsLayoutObject.ScalebarHeight.__doc__ = "Scalebar height (since QGIS 3.26)"
QgsLayoutObject.ScalebarRightSegmentSubdivisions = QgsLayoutObject.DataDefinedProperty.ScalebarRightSegmentSubdivisions
QgsLayoutObject.ScalebarRightSegmentSubdivisions.is_monkey_patched = True
QgsLayoutObject.ScalebarRightSegmentSubdivisions.__doc__ = "Number of subdivisions per segment on right of 0 (since QGIS 3.26)"
QgsLayoutObject.ScalebarSubdivisionHeight = QgsLayoutObject.DataDefinedProperty.ScalebarSubdivisionHeight
QgsLayoutObject.ScalebarSubdivisionHeight.is_monkey_patched = True
QgsLayoutObject.ScalebarSubdivisionHeight.__doc__ = "Scalebar subdivision height (since QGIS 3.26)"
QgsLayoutObject.ScalebarFillColor = QgsLayoutObject.DataDefinedProperty.ScalebarFillColor
QgsLayoutObject.ScalebarFillColor.is_monkey_patched = True
QgsLayoutObject.ScalebarFillColor.__doc__ = "Scalebar fill color (deprecated, use data defined properties on scalebar fill symbol 1 instead)"
QgsLayoutObject.ScalebarFillColor2 = QgsLayoutObject.DataDefinedProperty.ScalebarFillColor2
QgsLayoutObject.ScalebarFillColor2.is_monkey_patched = True
QgsLayoutObject.ScalebarFillColor2.__doc__ = "Scalebar secondary fill color (deprecated, use data defined properties on scalebar fill symbol 2 instead)"
QgsLayoutObject.ScalebarLineColor = QgsLayoutObject.DataDefinedProperty.ScalebarLineColor
QgsLayoutObject.ScalebarLineColor.is_monkey_patched = True
QgsLayoutObject.ScalebarLineColor.__doc__ = "Scalebar line color (deprecated, use data defined properties on scalebar line symbol instead)"
QgsLayoutObject.ScalebarLineWidth = QgsLayoutObject.DataDefinedProperty.ScalebarLineWidth
QgsLayoutObject.ScalebarLineWidth.is_monkey_patched = True
QgsLayoutObject.ScalebarLineWidth.__doc__ = "Scalebar line width (deprecated, use data defined properties on scalebar line symbol instead)"
QgsLayoutObject.AttributeTableSourceLayer = QgsLayoutObject.DataDefinedProperty.AttributeTableSourceLayer
QgsLayoutObject.AttributeTableSourceLayer.is_monkey_patched = True
QgsLayoutObject.AttributeTableSourceLayer.__doc__ = "Attribute table source layer"
QgsLayoutObject.ElevationProfileTolerance = QgsLayoutObject.DataDefinedProperty.ElevationProfileTolerance
QgsLayoutObject.ElevationProfileTolerance.is_monkey_patched = True
QgsLayoutObject.ElevationProfileTolerance.__doc__ = "Tolerance distance for elevation profiles (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileDistanceMajorInterval = QgsLayoutObject.DataDefinedProperty.ElevationProfileDistanceMajorInterval
QgsLayoutObject.ElevationProfileDistanceMajorInterval.is_monkey_patched = True
QgsLayoutObject.ElevationProfileDistanceMajorInterval.__doc__ = "Major grid line interval for elevation profile distance axis (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileDistanceMinorInterval = QgsLayoutObject.DataDefinedProperty.ElevationProfileDistanceMinorInterval
QgsLayoutObject.ElevationProfileDistanceMinorInterval.is_monkey_patched = True
QgsLayoutObject.ElevationProfileDistanceMinorInterval.__doc__ = "Minor grid line interval for elevation profile distance axis (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileDistanceLabelInterval = QgsLayoutObject.DataDefinedProperty.ElevationProfileDistanceLabelInterval
QgsLayoutObject.ElevationProfileDistanceLabelInterval.is_monkey_patched = True
QgsLayoutObject.ElevationProfileDistanceLabelInterval.__doc__ = "Label interval for elevation profile distance axis (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileElevationMajorInterval = QgsLayoutObject.DataDefinedProperty.ElevationProfileElevationMajorInterval
QgsLayoutObject.ElevationProfileElevationMajorInterval.is_monkey_patched = True
QgsLayoutObject.ElevationProfileElevationMajorInterval.__doc__ = "Major grid line interval for elevation profile elevation axis (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileElevationMinorInterval = QgsLayoutObject.DataDefinedProperty.ElevationProfileElevationMinorInterval
QgsLayoutObject.ElevationProfileElevationMinorInterval.is_monkey_patched = True
QgsLayoutObject.ElevationProfileElevationMinorInterval.__doc__ = "Minor grid line interval for elevation profile elevation axis (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileElevationLabelInterval = QgsLayoutObject.DataDefinedProperty.ElevationProfileElevationLabelInterval
QgsLayoutObject.ElevationProfileElevationLabelInterval.is_monkey_patched = True
QgsLayoutObject.ElevationProfileElevationLabelInterval.__doc__ = "Label interval for elevation profile elevation axis (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileMinimumDistance = QgsLayoutObject.DataDefinedProperty.ElevationProfileMinimumDistance
QgsLayoutObject.ElevationProfileMinimumDistance.is_monkey_patched = True
QgsLayoutObject.ElevationProfileMinimumDistance.__doc__ = "Minimum distance value for elevation profile (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileMaximumDistance = QgsLayoutObject.DataDefinedProperty.ElevationProfileMaximumDistance
QgsLayoutObject.ElevationProfileMaximumDistance.is_monkey_patched = True
QgsLayoutObject.ElevationProfileMaximumDistance.__doc__ = "Maximum distance value for elevation profile (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileMinimumElevation = QgsLayoutObject.DataDefinedProperty.ElevationProfileMinimumElevation
QgsLayoutObject.ElevationProfileMinimumElevation.is_monkey_patched = True
QgsLayoutObject.ElevationProfileMinimumElevation.__doc__ = "Minimum elevation value for elevation profile (since QGIS 3.30)"
QgsLayoutObject.ElevationProfileMaximumElevation = QgsLayoutObject.DataDefinedProperty.ElevationProfileMaximumElevation
QgsLayoutObject.ElevationProfileMaximumElevation.is_monkey_patched = True
QgsLayoutObject.ElevationProfileMaximumElevation.__doc__ = "Maximum elevation value for elevation profile (since QGIS 3.30)"
QgsLayoutObject.DataDefinedProperty.__doc__ = "Data defined properties for different item types\n\n" + '* ``NoProperty``: ' + QgsLayoutObject.DataDefinedProperty.NoProperty.__doc__ + '\n' + '* ``AllProperties``: ' + QgsLayoutObject.DataDefinedProperty.AllProperties.__doc__ + '\n' + '* ``TestProperty``: ' + QgsLayoutObject.DataDefinedProperty.TestProperty.__doc__ + '\n' + '* ``PresetPaperSize``: ' + QgsLayoutObject.DataDefinedProperty.PresetPaperSize.__doc__ + '\n' + '* ``PaperWidth``: ' + QgsLayoutObject.DataDefinedProperty.PaperWidth.__doc__ + '\n' + '* ``PaperHeight``: ' + QgsLayoutObject.DataDefinedProperty.PaperHeight.__doc__ + '\n' + '* ``NumPages``: ' + QgsLayoutObject.DataDefinedProperty.NumPages.__doc__ + '\n' + '* ``PaperOrientation``: ' + QgsLayoutObject.DataDefinedProperty.PaperOrientation.__doc__ + '\n' + '* ``PageNumber``: ' + QgsLayoutObject.DataDefinedProperty.PageNumber.__doc__ + '\n' + '* ``PositionX``: ' + QgsLayoutObject.DataDefinedProperty.PositionX.__doc__ + '\n' + '* ``PositionY``: ' + QgsLayoutObject.DataDefinedProperty.PositionY.__doc__ + '\n' + '* ``ItemWidth``: ' + QgsLayoutObject.DataDefinedProperty.ItemWidth.__doc__ + '\n' + '* ``ItemHeight``: ' + QgsLayoutObject.DataDefinedProperty.ItemHeight.__doc__ + '\n' + '* ``ItemRotation``: ' + QgsLayoutObject.DataDefinedProperty.ItemRotation.__doc__ + '\n' + '* ``Transparency``: ' + QgsLayoutObject.DataDefinedProperty.Transparency.__doc__ + '\n' + '* ``Opacity``: ' + QgsLayoutObject.DataDefinedProperty.Opacity.__doc__ + '\n' + '* ``BlendMode``: ' + QgsLayoutObject.DataDefinedProperty.BlendMode.__doc__ + '\n' + '* ``ExcludeFromExports``: ' + QgsLayoutObject.DataDefinedProperty.ExcludeFromExports.__doc__ + '\n' + '* ``FrameColor``: ' + QgsLayoutObject.DataDefinedProperty.FrameColor.__doc__ + '\n' + '* ``BackgroundColor``: ' + QgsLayoutObject.DataDefinedProperty.BackgroundColor.__doc__ + '\n' + '* ``MarginLeft``: ' + QgsLayoutObject.DataDefinedProperty.MarginLeft.__doc__ + '\n' + '* ``MarginTop``: ' + QgsLayoutObject.DataDefinedProperty.MarginTop.__doc__ + '\n' + '* ``MarginRight``: ' + QgsLayoutObject.DataDefinedProperty.MarginRight.__doc__ + '\n' + '* ``MarginBottom``: ' + QgsLayoutObject.DataDefinedProperty.MarginBottom.__doc__ + '\n' + '* ``MapRotation``: ' + QgsLayoutObject.DataDefinedProperty.MapRotation.__doc__ + '\n' + '* ``MapScale``: ' + QgsLayoutObject.DataDefinedProperty.MapScale.__doc__ + '\n' + '* ``MapXMin``: ' + QgsLayoutObject.DataDefinedProperty.MapXMin.__doc__ + '\n' + '* ``MapYMin``: ' + QgsLayoutObject.DataDefinedProperty.MapYMin.__doc__ + '\n' + '* ``MapXMax``: ' + QgsLayoutObject.DataDefinedProperty.MapXMax.__doc__ + '\n' + '* ``MapYMax``: ' + QgsLayoutObject.DataDefinedProperty.MapYMax.__doc__ + '\n' + '* ``MapAtlasMargin``: ' + QgsLayoutObject.DataDefinedProperty.MapAtlasMargin.__doc__ + '\n' + '* ``MapLayers``: ' + QgsLayoutObject.DataDefinedProperty.MapLayers.__doc__ + '\n' + '* ``MapStylePreset``: ' + QgsLayoutObject.DataDefinedProperty.MapStylePreset.__doc__ + '\n' + '* ``MapLabelMargin``: ' + QgsLayoutObject.DataDefinedProperty.MapLabelMargin.__doc__ + '\n' + '* ``MapGridEnabled``: ' + QgsLayoutObject.DataDefinedProperty.MapGridEnabled.__doc__ + '\n' + '* ``MapGridIntervalX``: ' + QgsLayoutObject.DataDefinedProperty.MapGridIntervalX.__doc__ + '\n' + '* ``MapGridIntervalY``: ' + QgsLayoutObject.DataDefinedProperty.MapGridIntervalY.__doc__ + '\n' + '* ``MapGridOffsetX``: ' + QgsLayoutObject.DataDefinedProperty.MapGridOffsetX.__doc__ + '\n' + '* ``MapGridOffsetY``: ' + QgsLayoutObject.DataDefinedProperty.MapGridOffsetY.__doc__ + '\n' + '* ``MapGridFrameSize``: ' + QgsLayoutObject.DataDefinedProperty.MapGridFrameSize.__doc__ + '\n' + '* ``MapGridFrameMargin``: ' + QgsLayoutObject.DataDefinedProperty.MapGridFrameMargin.__doc__ + '\n' + '* ``MapGridLabelDistance``: ' + QgsLayoutObject.DataDefinedProperty.MapGridLabelDistance.__doc__ + '\n' + '* ``MapGridCrossSize``: ' + QgsLayoutObject.DataDefinedProperty.MapGridCrossSize.__doc__ + '\n' + '* ``MapGridFrameLineThickness``: ' + QgsLayoutObject.DataDefinedProperty.MapGridFrameLineThickness.__doc__ + '\n' + '* ``MapGridAnnotationDisplayLeft``: ' + QgsLayoutObject.DataDefinedProperty.MapGridAnnotationDisplayLeft.__doc__ + '\n' + '* ``MapGridAnnotationDisplayRight``: ' + QgsLayoutObject.DataDefinedProperty.MapGridAnnotationDisplayRight.__doc__ + '\n' + '* ``MapGridAnnotationDisplayTop``: ' + QgsLayoutObject.DataDefinedProperty.MapGridAnnotationDisplayTop.__doc__ + '\n' + '* ``MapGridAnnotationDisplayBottom``: ' + QgsLayoutObject.DataDefinedProperty.MapGridAnnotationDisplayBottom.__doc__ + '\n' + '* ``MapGridFrameDivisionsLeft``: ' + QgsLayoutObject.DataDefinedProperty.MapGridFrameDivisionsLeft.__doc__ + '\n' + '* ``MapGridFrameDivisionsRight``: ' + QgsLayoutObject.DataDefinedProperty.MapGridFrameDivisionsRight.__doc__ + '\n' + '* ``MapGridFrameDivisionsTop``: ' + QgsLayoutObject.DataDefinedProperty.MapGridFrameDivisionsTop.__doc__ + '\n' + '* ``MapGridFrameDivisionsBottom``: ' + QgsLayoutObject.DataDefinedProperty.MapGridFrameDivisionsBottom.__doc__ + '\n' + '* ``MapCrs``: ' + QgsLayoutObject.DataDefinedProperty.MapCrs.__doc__ + '\n' + '* ``StartDateTime``: ' + QgsLayoutObject.DataDefinedProperty.StartDateTime.__doc__ + '\n' + '* ``EndDateTime``: ' + QgsLayoutObject.DataDefinedProperty.EndDateTime.__doc__ + '\n' + '* ``MapZRangeLower``: ' + QgsLayoutObject.DataDefinedProperty.MapZRangeLower.__doc__ + '\n' + '* ``MapZRangeUpper``: ' + QgsLayoutObject.DataDefinedProperty.MapZRangeUpper.__doc__ + '\n' + '* ``PictureSource``: ' + QgsLayoutObject.DataDefinedProperty.PictureSource.__doc__ + '\n' + '* ``PictureSvgBackgroundColor``: ' + QgsLayoutObject.DataDefinedProperty.PictureSvgBackgroundColor.__doc__ + '\n' + '* ``PictureSvgStrokeColor``: ' + QgsLayoutObject.DataDefinedProperty.PictureSvgStrokeColor.__doc__ + '\n' + '* ``PictureSvgStrokeWidth``: ' + QgsLayoutObject.DataDefinedProperty.PictureSvgStrokeWidth.__doc__ + '\n' + '* ``SourceUrl``: ' + QgsLayoutObject.DataDefinedProperty.SourceUrl.__doc__ + '\n' + '* ``LegendTitle``: ' + QgsLayoutObject.DataDefinedProperty.LegendTitle.__doc__ + '\n' + '* ``LegendColumnCount``: ' + QgsLayoutObject.DataDefinedProperty.LegendColumnCount.__doc__ + '\n' + '* ``ScalebarLeftSegments``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarLeftSegments.__doc__ + '\n' + '* ``ScalebarRightSegments``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarRightSegments.__doc__ + '\n' + '* ``ScalebarSegmentWidth``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarSegmentWidth.__doc__ + '\n' + '* ``ScalebarMinimumWidth``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarMinimumWidth.__doc__ + '\n' + '* ``ScalebarMaximumWidth``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarMaximumWidth.__doc__ + '\n' + '* ``ScalebarHeight``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarHeight.__doc__ + '\n' + '* ``ScalebarRightSegmentSubdivisions``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarRightSegmentSubdivisions.__doc__ + '\n' + '* ``ScalebarSubdivisionHeight``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarSubdivisionHeight.__doc__ + '\n' + '* ``ScalebarFillColor``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarFillColor.__doc__ + '\n' + '* ``ScalebarFillColor2``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarFillColor2.__doc__ + '\n' + '* ``ScalebarLineColor``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarLineColor.__doc__ + '\n' + '* ``ScalebarLineWidth``: ' + QgsLayoutObject.DataDefinedProperty.ScalebarLineWidth.__doc__ + '\n' + '* ``AttributeTableSourceLayer``: ' + QgsLayoutObject.DataDefinedProperty.AttributeTableSourceLayer.__doc__ + '\n' + '* ``ElevationProfileTolerance``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileTolerance.__doc__ + '\n' + '* ``ElevationProfileDistanceMajorInterval``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileDistanceMajorInterval.__doc__ + '\n' + '* ``ElevationProfileDistanceMinorInterval``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileDistanceMinorInterval.__doc__ + '\n' + '* ``ElevationProfileDistanceLabelInterval``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileDistanceLabelInterval.__doc__ + '\n' + '* ``ElevationProfileElevationMajorInterval``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileElevationMajorInterval.__doc__ + '\n' + '* ``ElevationProfileElevationMinorInterval``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileElevationMinorInterval.__doc__ + '\n' + '* ``ElevationProfileElevationLabelInterval``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileElevationLabelInterval.__doc__ + '\n' + '* ``ElevationProfileMinimumDistance``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileMinimumDistance.__doc__ + '\n' + '* ``ElevationProfileMaximumDistance``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileMaximumDistance.__doc__ + '\n' + '* ``ElevationProfileMinimumElevation``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileMinimumElevation.__doc__ + '\n' + '* ``ElevationProfileMaximumElevation``: ' + QgsLayoutObject.DataDefinedProperty.ElevationProfileMaximumElevation.__doc__
# --
