# The following has been generated automatically from src/core/labeling/qgspallabeling.h
# monkey patching scoped based enum
QgsPalLayerSettings.Size = QgsPalLayerSettings.Property.Size
QgsPalLayerSettings.Size.is_monkey_patched = True
QgsPalLayerSettings.Size.__doc__ = "Label size"
QgsPalLayerSettings.Bold = QgsPalLayerSettings.Property.Bold
QgsPalLayerSettings.Bold.is_monkey_patched = True
QgsPalLayerSettings.Bold.__doc__ = "Use bold style"
QgsPalLayerSettings.Italic = QgsPalLayerSettings.Property.Italic
QgsPalLayerSettings.Italic.is_monkey_patched = True
QgsPalLayerSettings.Italic.__doc__ = "Use italic style"
QgsPalLayerSettings.Underline = QgsPalLayerSettings.Property.Underline
QgsPalLayerSettings.Underline.is_monkey_patched = True
QgsPalLayerSettings.Underline.__doc__ = "Use underline"
QgsPalLayerSettings.Color = QgsPalLayerSettings.Property.Color
QgsPalLayerSettings.Color.is_monkey_patched = True
QgsPalLayerSettings.Color.__doc__ = "Text color"
QgsPalLayerSettings.Strikeout = QgsPalLayerSettings.Property.Strikeout
QgsPalLayerSettings.Strikeout.is_monkey_patched = True
QgsPalLayerSettings.Strikeout.__doc__ = "Use strikeout"
QgsPalLayerSettings.Family = QgsPalLayerSettings.Property.Family
QgsPalLayerSettings.Family.is_monkey_patched = True
QgsPalLayerSettings.Family.__doc__ = "Font family"
QgsPalLayerSettings.FontStyle = QgsPalLayerSettings.Property.FontStyle
QgsPalLayerSettings.FontStyle.is_monkey_patched = True
QgsPalLayerSettings.FontStyle.__doc__ = "Font style name"
QgsPalLayerSettings.FontSizeUnit = QgsPalLayerSettings.Property.FontSizeUnit
QgsPalLayerSettings.FontSizeUnit.is_monkey_patched = True
QgsPalLayerSettings.FontSizeUnit.__doc__ = "Font size units"
QgsPalLayerSettings.FontTransp = QgsPalLayerSettings.Property.FontTransp
QgsPalLayerSettings.FontTransp.is_monkey_patched = True
QgsPalLayerSettings.FontTransp.__doc__ = "Text transparency (deprecated)"
QgsPalLayerSettings.FontOpacity = QgsPalLayerSettings.Property.FontOpacity
QgsPalLayerSettings.FontOpacity.is_monkey_patched = True
QgsPalLayerSettings.FontOpacity.__doc__ = "Text opacity"
QgsPalLayerSettings.FontCase = QgsPalLayerSettings.Property.FontCase
QgsPalLayerSettings.FontCase.is_monkey_patched = True
QgsPalLayerSettings.FontCase.__doc__ = "Label text case"
QgsPalLayerSettings.FontLetterSpacing = QgsPalLayerSettings.Property.FontLetterSpacing
QgsPalLayerSettings.FontLetterSpacing.is_monkey_patched = True
QgsPalLayerSettings.FontLetterSpacing.__doc__ = "Letter spacing"
QgsPalLayerSettings.FontWordSpacing = QgsPalLayerSettings.Property.FontWordSpacing
QgsPalLayerSettings.FontWordSpacing.is_monkey_patched = True
QgsPalLayerSettings.FontWordSpacing.__doc__ = "Word spacing"
QgsPalLayerSettings.FontBlendMode = QgsPalLayerSettings.Property.FontBlendMode
QgsPalLayerSettings.FontBlendMode.is_monkey_patched = True
QgsPalLayerSettings.FontBlendMode.__doc__ = "Text blend mode"
QgsPalLayerSettings.FontStretchFactor = QgsPalLayerSettings.Property.FontStretchFactor
QgsPalLayerSettings.FontStretchFactor.is_monkey_patched = True
QgsPalLayerSettings.FontStretchFactor.__doc__ = "Font stretch factor, since QGIS 3.24"
QgsPalLayerSettings.MultiLineWrapChar = QgsPalLayerSettings.Property.MultiLineWrapChar
QgsPalLayerSettings.MultiLineWrapChar.is_monkey_patched = True
QgsPalLayerSettings.MultiLineWrapChar.__doc__ = ""
QgsPalLayerSettings.AutoWrapLength = QgsPalLayerSettings.Property.AutoWrapLength
QgsPalLayerSettings.AutoWrapLength.is_monkey_patched = True
QgsPalLayerSettings.AutoWrapLength.__doc__ = ""
QgsPalLayerSettings.MultiLineHeight = QgsPalLayerSettings.Property.MultiLineHeight
QgsPalLayerSettings.MultiLineHeight.is_monkey_patched = True
QgsPalLayerSettings.MultiLineHeight.__doc__ = ""
QgsPalLayerSettings.MultiLineAlignment = QgsPalLayerSettings.Property.MultiLineAlignment
QgsPalLayerSettings.MultiLineAlignment.is_monkey_patched = True
QgsPalLayerSettings.MultiLineAlignment.__doc__ = ""
QgsPalLayerSettings.TextOrientation = QgsPalLayerSettings.Property.TextOrientation
QgsPalLayerSettings.TextOrientation.is_monkey_patched = True
QgsPalLayerSettings.TextOrientation.__doc__ = ""
QgsPalLayerSettings.TabStopDistance = QgsPalLayerSettings.Property.TabStopDistance
QgsPalLayerSettings.TabStopDistance.is_monkey_patched = True
QgsPalLayerSettings.TabStopDistance.__doc__ = "Tab stop distance, since QGIS 3.38"
QgsPalLayerSettings.DirSymbDraw = QgsPalLayerSettings.Property.DirSymbDraw
QgsPalLayerSettings.DirSymbDraw.is_monkey_patched = True
QgsPalLayerSettings.DirSymbDraw.__doc__ = ""
QgsPalLayerSettings.DirSymbLeft = QgsPalLayerSettings.Property.DirSymbLeft
QgsPalLayerSettings.DirSymbLeft.is_monkey_patched = True
QgsPalLayerSettings.DirSymbLeft.__doc__ = ""
QgsPalLayerSettings.DirSymbRight = QgsPalLayerSettings.Property.DirSymbRight
QgsPalLayerSettings.DirSymbRight.is_monkey_patched = True
QgsPalLayerSettings.DirSymbRight.__doc__ = ""
QgsPalLayerSettings.DirSymbPlacement = QgsPalLayerSettings.Property.DirSymbPlacement
QgsPalLayerSettings.DirSymbPlacement.is_monkey_patched = True
QgsPalLayerSettings.DirSymbPlacement.__doc__ = ""
QgsPalLayerSettings.DirSymbReverse = QgsPalLayerSettings.Property.DirSymbReverse
QgsPalLayerSettings.DirSymbReverse.is_monkey_patched = True
QgsPalLayerSettings.DirSymbReverse.__doc__ = ""
QgsPalLayerSettings.NumFormat = QgsPalLayerSettings.Property.NumFormat
QgsPalLayerSettings.NumFormat.is_monkey_patched = True
QgsPalLayerSettings.NumFormat.__doc__ = ""
QgsPalLayerSettings.NumDecimals = QgsPalLayerSettings.Property.NumDecimals
QgsPalLayerSettings.NumDecimals.is_monkey_patched = True
QgsPalLayerSettings.NumDecimals.__doc__ = ""
QgsPalLayerSettings.NumPlusSign = QgsPalLayerSettings.Property.NumPlusSign
QgsPalLayerSettings.NumPlusSign.is_monkey_patched = True
QgsPalLayerSettings.NumPlusSign.__doc__ = ""
QgsPalLayerSettings.BufferDraw = QgsPalLayerSettings.Property.BufferDraw
QgsPalLayerSettings.BufferDraw.is_monkey_patched = True
QgsPalLayerSettings.BufferDraw.__doc__ = ""
QgsPalLayerSettings.BufferSize = QgsPalLayerSettings.Property.BufferSize
QgsPalLayerSettings.BufferSize.is_monkey_patched = True
QgsPalLayerSettings.BufferSize.__doc__ = ""
QgsPalLayerSettings.BufferUnit = QgsPalLayerSettings.Property.BufferUnit
QgsPalLayerSettings.BufferUnit.is_monkey_patched = True
QgsPalLayerSettings.BufferUnit.__doc__ = ""
QgsPalLayerSettings.BufferColor = QgsPalLayerSettings.Property.BufferColor
QgsPalLayerSettings.BufferColor.is_monkey_patched = True
QgsPalLayerSettings.BufferColor.__doc__ = ""
QgsPalLayerSettings.BufferTransp = QgsPalLayerSettings.Property.BufferTransp
QgsPalLayerSettings.BufferTransp.is_monkey_patched = True
QgsPalLayerSettings.BufferTransp.__doc__ = "Buffer transparency (deprecated)"
QgsPalLayerSettings.BufferOpacity = QgsPalLayerSettings.Property.BufferOpacity
QgsPalLayerSettings.BufferOpacity.is_monkey_patched = True
QgsPalLayerSettings.BufferOpacity.__doc__ = "Buffer opacity"
QgsPalLayerSettings.BufferJoinStyle = QgsPalLayerSettings.Property.BufferJoinStyle
QgsPalLayerSettings.BufferJoinStyle.is_monkey_patched = True
QgsPalLayerSettings.BufferJoinStyle.__doc__ = ""
QgsPalLayerSettings.BufferBlendMode = QgsPalLayerSettings.Property.BufferBlendMode
QgsPalLayerSettings.BufferBlendMode.is_monkey_patched = True
QgsPalLayerSettings.BufferBlendMode.__doc__ = ""
QgsPalLayerSettings.MaskEnabled = QgsPalLayerSettings.Property.MaskEnabled
QgsPalLayerSettings.MaskEnabled.is_monkey_patched = True
QgsPalLayerSettings.MaskEnabled.__doc__ = "Whether the mask is enabled"
QgsPalLayerSettings.MaskBufferSize = QgsPalLayerSettings.Property.MaskBufferSize
QgsPalLayerSettings.MaskBufferSize.is_monkey_patched = True
QgsPalLayerSettings.MaskBufferSize.__doc__ = "Mask buffer size"
QgsPalLayerSettings.MaskBufferUnit = QgsPalLayerSettings.Property.MaskBufferUnit
QgsPalLayerSettings.MaskBufferUnit.is_monkey_patched = True
QgsPalLayerSettings.MaskBufferUnit.__doc__ = "Mask buffer size unit"
QgsPalLayerSettings.MaskOpacity = QgsPalLayerSettings.Property.MaskOpacity
QgsPalLayerSettings.MaskOpacity.is_monkey_patched = True
QgsPalLayerSettings.MaskOpacity.__doc__ = "Mask opacity"
QgsPalLayerSettings.MaskJoinStyle = QgsPalLayerSettings.Property.MaskJoinStyle
QgsPalLayerSettings.MaskJoinStyle.is_monkey_patched = True
QgsPalLayerSettings.MaskJoinStyle.__doc__ = "Mask join style"
QgsPalLayerSettings.ShapeDraw = QgsPalLayerSettings.Property.ShapeDraw
QgsPalLayerSettings.ShapeDraw.is_monkey_patched = True
QgsPalLayerSettings.ShapeDraw.__doc__ = ""
QgsPalLayerSettings.ShapeKind = QgsPalLayerSettings.Property.ShapeKind
QgsPalLayerSettings.ShapeKind.is_monkey_patched = True
QgsPalLayerSettings.ShapeKind.__doc__ = ""
QgsPalLayerSettings.ShapeSVGFile = QgsPalLayerSettings.Property.ShapeSVGFile
QgsPalLayerSettings.ShapeSVGFile.is_monkey_patched = True
QgsPalLayerSettings.ShapeSVGFile.__doc__ = ""
QgsPalLayerSettings.ShapeSizeType = QgsPalLayerSettings.Property.ShapeSizeType
QgsPalLayerSettings.ShapeSizeType.is_monkey_patched = True
QgsPalLayerSettings.ShapeSizeType.__doc__ = ""
QgsPalLayerSettings.ShapeSizeX = QgsPalLayerSettings.Property.ShapeSizeX
QgsPalLayerSettings.ShapeSizeX.is_monkey_patched = True
QgsPalLayerSettings.ShapeSizeX.__doc__ = ""
QgsPalLayerSettings.ShapeSizeY = QgsPalLayerSettings.Property.ShapeSizeY
QgsPalLayerSettings.ShapeSizeY.is_monkey_patched = True
QgsPalLayerSettings.ShapeSizeY.__doc__ = ""
QgsPalLayerSettings.ShapeSizeUnits = QgsPalLayerSettings.Property.ShapeSizeUnits
QgsPalLayerSettings.ShapeSizeUnits.is_monkey_patched = True
QgsPalLayerSettings.ShapeSizeUnits.__doc__ = ""
QgsPalLayerSettings.ShapeRotationType = QgsPalLayerSettings.Property.ShapeRotationType
QgsPalLayerSettings.ShapeRotationType.is_monkey_patched = True
QgsPalLayerSettings.ShapeRotationType.__doc__ = ""
QgsPalLayerSettings.ShapeRotation = QgsPalLayerSettings.Property.ShapeRotation
QgsPalLayerSettings.ShapeRotation.is_monkey_patched = True
QgsPalLayerSettings.ShapeRotation.__doc__ = ""
QgsPalLayerSettings.ShapeOffset = QgsPalLayerSettings.Property.ShapeOffset
QgsPalLayerSettings.ShapeOffset.is_monkey_patched = True
QgsPalLayerSettings.ShapeOffset.__doc__ = ""
QgsPalLayerSettings.ShapeOffsetUnits = QgsPalLayerSettings.Property.ShapeOffsetUnits
QgsPalLayerSettings.ShapeOffsetUnits.is_monkey_patched = True
QgsPalLayerSettings.ShapeOffsetUnits.__doc__ = ""
QgsPalLayerSettings.ShapeRadii = QgsPalLayerSettings.Property.ShapeRadii
QgsPalLayerSettings.ShapeRadii.is_monkey_patched = True
QgsPalLayerSettings.ShapeRadii.__doc__ = ""
QgsPalLayerSettings.ShapeRadiiUnits = QgsPalLayerSettings.Property.ShapeRadiiUnits
QgsPalLayerSettings.ShapeRadiiUnits.is_monkey_patched = True
QgsPalLayerSettings.ShapeRadiiUnits.__doc__ = ""
QgsPalLayerSettings.ShapeTransparency = QgsPalLayerSettings.Property.ShapeTransparency
QgsPalLayerSettings.ShapeTransparency.is_monkey_patched = True
QgsPalLayerSettings.ShapeTransparency.__doc__ = "Shape transparency (deprecated)"
QgsPalLayerSettings.ShapeOpacity = QgsPalLayerSettings.Property.ShapeOpacity
QgsPalLayerSettings.ShapeOpacity.is_monkey_patched = True
QgsPalLayerSettings.ShapeOpacity.__doc__ = "Shape opacity"
QgsPalLayerSettings.ShapeBlendMode = QgsPalLayerSettings.Property.ShapeBlendMode
QgsPalLayerSettings.ShapeBlendMode.is_monkey_patched = True
QgsPalLayerSettings.ShapeBlendMode.__doc__ = ""
QgsPalLayerSettings.ShapeFillColor = QgsPalLayerSettings.Property.ShapeFillColor
QgsPalLayerSettings.ShapeFillColor.is_monkey_patched = True
QgsPalLayerSettings.ShapeFillColor.__doc__ = ""
QgsPalLayerSettings.ShapeStrokeColor = QgsPalLayerSettings.Property.ShapeStrokeColor
QgsPalLayerSettings.ShapeStrokeColor.is_monkey_patched = True
QgsPalLayerSettings.ShapeStrokeColor.__doc__ = ""
QgsPalLayerSettings.ShapeStrokeWidth = QgsPalLayerSettings.Property.ShapeStrokeWidth
QgsPalLayerSettings.ShapeStrokeWidth.is_monkey_patched = True
QgsPalLayerSettings.ShapeStrokeWidth.__doc__ = ""
QgsPalLayerSettings.ShapeStrokeWidthUnits = QgsPalLayerSettings.Property.ShapeStrokeWidthUnits
QgsPalLayerSettings.ShapeStrokeWidthUnits.is_monkey_patched = True
QgsPalLayerSettings.ShapeStrokeWidthUnits.__doc__ = ""
QgsPalLayerSettings.ShapeJoinStyle = QgsPalLayerSettings.Property.ShapeJoinStyle
QgsPalLayerSettings.ShapeJoinStyle.is_monkey_patched = True
QgsPalLayerSettings.ShapeJoinStyle.__doc__ = ""
QgsPalLayerSettings.ShadowDraw = QgsPalLayerSettings.Property.ShadowDraw
QgsPalLayerSettings.ShadowDraw.is_monkey_patched = True
QgsPalLayerSettings.ShadowDraw.__doc__ = ""
QgsPalLayerSettings.ShadowUnder = QgsPalLayerSettings.Property.ShadowUnder
QgsPalLayerSettings.ShadowUnder.is_monkey_patched = True
QgsPalLayerSettings.ShadowUnder.__doc__ = ""
QgsPalLayerSettings.ShadowOffsetAngle = QgsPalLayerSettings.Property.ShadowOffsetAngle
QgsPalLayerSettings.ShadowOffsetAngle.is_monkey_patched = True
QgsPalLayerSettings.ShadowOffsetAngle.__doc__ = ""
QgsPalLayerSettings.ShadowOffsetDist = QgsPalLayerSettings.Property.ShadowOffsetDist
QgsPalLayerSettings.ShadowOffsetDist.is_monkey_patched = True
QgsPalLayerSettings.ShadowOffsetDist.__doc__ = ""
QgsPalLayerSettings.ShadowOffsetUnits = QgsPalLayerSettings.Property.ShadowOffsetUnits
QgsPalLayerSettings.ShadowOffsetUnits.is_monkey_patched = True
QgsPalLayerSettings.ShadowOffsetUnits.__doc__ = ""
QgsPalLayerSettings.ShadowRadius = QgsPalLayerSettings.Property.ShadowRadius
QgsPalLayerSettings.ShadowRadius.is_monkey_patched = True
QgsPalLayerSettings.ShadowRadius.__doc__ = ""
QgsPalLayerSettings.ShadowRadiusUnits = QgsPalLayerSettings.Property.ShadowRadiusUnits
QgsPalLayerSettings.ShadowRadiusUnits.is_monkey_patched = True
QgsPalLayerSettings.ShadowRadiusUnits.__doc__ = ""
QgsPalLayerSettings.ShadowTransparency = QgsPalLayerSettings.Property.ShadowTransparency
QgsPalLayerSettings.ShadowTransparency.is_monkey_patched = True
QgsPalLayerSettings.ShadowTransparency.__doc__ = "Shadow transparency (deprecated)"
QgsPalLayerSettings.ShadowOpacity = QgsPalLayerSettings.Property.ShadowOpacity
QgsPalLayerSettings.ShadowOpacity.is_monkey_patched = True
QgsPalLayerSettings.ShadowOpacity.__doc__ = "Shadow opacity"
QgsPalLayerSettings.ShadowScale = QgsPalLayerSettings.Property.ShadowScale
QgsPalLayerSettings.ShadowScale.is_monkey_patched = True
QgsPalLayerSettings.ShadowScale.__doc__ = ""
QgsPalLayerSettings.ShadowColor = QgsPalLayerSettings.Property.ShadowColor
QgsPalLayerSettings.ShadowColor.is_monkey_patched = True
QgsPalLayerSettings.ShadowColor.__doc__ = ""
QgsPalLayerSettings.ShadowBlendMode = QgsPalLayerSettings.Property.ShadowBlendMode
QgsPalLayerSettings.ShadowBlendMode.is_monkey_patched = True
QgsPalLayerSettings.ShadowBlendMode.__doc__ = ""
QgsPalLayerSettings.CentroidWhole = QgsPalLayerSettings.Property.CentroidWhole
QgsPalLayerSettings.CentroidWhole.is_monkey_patched = True
QgsPalLayerSettings.CentroidWhole.__doc__ = ""
QgsPalLayerSettings.OffsetQuad = QgsPalLayerSettings.Property.OffsetQuad
QgsPalLayerSettings.OffsetQuad.is_monkey_patched = True
QgsPalLayerSettings.OffsetQuad.__doc__ = ""
QgsPalLayerSettings.OffsetXY = QgsPalLayerSettings.Property.OffsetXY
QgsPalLayerSettings.OffsetXY.is_monkey_patched = True
QgsPalLayerSettings.OffsetXY.__doc__ = ""
QgsPalLayerSettings.OffsetUnits = QgsPalLayerSettings.Property.OffsetUnits
QgsPalLayerSettings.OffsetUnits.is_monkey_patched = True
QgsPalLayerSettings.OffsetUnits.__doc__ = ""
QgsPalLayerSettings.LabelDistance = QgsPalLayerSettings.Property.LabelDistance
QgsPalLayerSettings.LabelDistance.is_monkey_patched = True
QgsPalLayerSettings.LabelDistance.__doc__ = ""
QgsPalLayerSettings.MaximumDistance = QgsPalLayerSettings.Property.MaximumDistance
QgsPalLayerSettings.MaximumDistance.is_monkey_patched = True
QgsPalLayerSettings.MaximumDistance.__doc__ = "Maximum distance of label from feature"
QgsPalLayerSettings.DistanceUnits = QgsPalLayerSettings.Property.DistanceUnits
QgsPalLayerSettings.DistanceUnits.is_monkey_patched = True
QgsPalLayerSettings.DistanceUnits.__doc__ = ""
QgsPalLayerSettings.OffsetRotation = QgsPalLayerSettings.Property.OffsetRotation
QgsPalLayerSettings.OffsetRotation.is_monkey_patched = True
QgsPalLayerSettings.OffsetRotation.__doc__ = ""
QgsPalLayerSettings.CurvedCharAngleInOut = QgsPalLayerSettings.Property.CurvedCharAngleInOut
QgsPalLayerSettings.CurvedCharAngleInOut.is_monkey_patched = True
QgsPalLayerSettings.CurvedCharAngleInOut.__doc__ = ""
QgsPalLayerSettings.PositionX = QgsPalLayerSettings.Property.PositionX
QgsPalLayerSettings.PositionX.is_monkey_patched = True
QgsPalLayerSettings.PositionX.__doc__ = "X-coordinate data defined label position"
QgsPalLayerSettings.PositionY = QgsPalLayerSettings.Property.PositionY
QgsPalLayerSettings.PositionY.is_monkey_patched = True
QgsPalLayerSettings.PositionY.__doc__ = "Y-coordinate data defined label position"
QgsPalLayerSettings.PositionPoint = QgsPalLayerSettings.Property.PositionPoint
QgsPalLayerSettings.PositionPoint.is_monkey_patched = True
QgsPalLayerSettings.PositionPoint.__doc__ = "Point-coordinate data defined label position"
QgsPalLayerSettings.Hali = QgsPalLayerSettings.Property.Hali
QgsPalLayerSettings.Hali.is_monkey_patched = True
QgsPalLayerSettings.Hali.__doc__ = "Horizontal alignment for data defined label position (Left, Center, Right)"
QgsPalLayerSettings.Vali = QgsPalLayerSettings.Property.Vali
QgsPalLayerSettings.Vali.is_monkey_patched = True
QgsPalLayerSettings.Vali.__doc__ = "Vertical alignment for data defined label position (Bottom, Base, Half, Cap, Top)"
QgsPalLayerSettings.Rotation = QgsPalLayerSettings.Property.Rotation
QgsPalLayerSettings.Rotation.is_monkey_patched = True
QgsPalLayerSettings.Rotation.__doc__ = "Label rotation (deprecated, for old project compatibility only)"
QgsPalLayerSettings.LabelRotation = QgsPalLayerSettings.Property.LabelRotation
QgsPalLayerSettings.LabelRotation.is_monkey_patched = True
QgsPalLayerSettings.LabelRotation.__doc__ = "Label rotation"
QgsPalLayerSettings.RepeatDistance = QgsPalLayerSettings.Property.RepeatDistance
QgsPalLayerSettings.RepeatDistance.is_monkey_patched = True
QgsPalLayerSettings.RepeatDistance.__doc__ = ""
QgsPalLayerSettings.RepeatDistanceUnit = QgsPalLayerSettings.Property.RepeatDistanceUnit
QgsPalLayerSettings.RepeatDistanceUnit.is_monkey_patched = True
QgsPalLayerSettings.RepeatDistanceUnit.__doc__ = ""
QgsPalLayerSettings.Priority = QgsPalLayerSettings.Property.Priority
QgsPalLayerSettings.Priority.is_monkey_patched = True
QgsPalLayerSettings.Priority.__doc__ = ""
QgsPalLayerSettings.PredefinedPositionOrder = QgsPalLayerSettings.Property.PredefinedPositionOrder
QgsPalLayerSettings.PredefinedPositionOrder.is_monkey_patched = True
QgsPalLayerSettings.PredefinedPositionOrder.__doc__ = ""
QgsPalLayerSettings.LinePlacementOptions = QgsPalLayerSettings.Property.LinePlacementOptions
QgsPalLayerSettings.LinePlacementOptions.is_monkey_patched = True
QgsPalLayerSettings.LinePlacementOptions.__doc__ = "Line placement flags"
QgsPalLayerSettings.OverrunDistance = QgsPalLayerSettings.Property.OverrunDistance
QgsPalLayerSettings.OverrunDistance.is_monkey_patched = True
QgsPalLayerSettings.OverrunDistance.__doc__ = "Distance which labels can extend past either end of linear features"
QgsPalLayerSettings.LabelAllParts = QgsPalLayerSettings.Property.LabelAllParts
QgsPalLayerSettings.LabelAllParts.is_monkey_patched = True
QgsPalLayerSettings.LabelAllParts.__doc__ = "Whether all parts of multi-part features should be labeled"
QgsPalLayerSettings.PolygonLabelOutside = QgsPalLayerSettings.Property.PolygonLabelOutside
QgsPalLayerSettings.PolygonLabelOutside.is_monkey_patched = True
QgsPalLayerSettings.PolygonLabelOutside.__doc__ = "Whether labels outside a polygon feature are permitted, or should be forced (since QGIS 3.14)"
QgsPalLayerSettings.LineAnchorPercent = QgsPalLayerSettings.Property.LineAnchorPercent
QgsPalLayerSettings.LineAnchorPercent.is_monkey_patched = True
QgsPalLayerSettings.LineAnchorPercent.__doc__ = "Portion along line at which labels should be anchored (since QGIS 3.16)"
QgsPalLayerSettings.LineAnchorClipping = QgsPalLayerSettings.Property.LineAnchorClipping
QgsPalLayerSettings.LineAnchorClipping.is_monkey_patched = True
QgsPalLayerSettings.LineAnchorClipping.__doc__ = "Clipping mode for line anchor calculation (since QGIS 3.20)"
QgsPalLayerSettings.LineAnchorType = QgsPalLayerSettings.Property.LineAnchorType
QgsPalLayerSettings.LineAnchorType.is_monkey_patched = True
QgsPalLayerSettings.LineAnchorType.__doc__ = "Line anchor type (since QGIS 3.26)"
QgsPalLayerSettings.LineAnchorTextPoint = QgsPalLayerSettings.Property.LineAnchorTextPoint
QgsPalLayerSettings.LineAnchorTextPoint.is_monkey_patched = True
QgsPalLayerSettings.LineAnchorTextPoint.__doc__ = "Line anchor text point (since QGIS 3.26)"
QgsPalLayerSettings.ScaleVisibility = QgsPalLayerSettings.Property.ScaleVisibility
QgsPalLayerSettings.ScaleVisibility.is_monkey_patched = True
QgsPalLayerSettings.ScaleVisibility.__doc__ = ""
QgsPalLayerSettings.MinScale = QgsPalLayerSettings.Property.MinScale
QgsPalLayerSettings.MinScale.is_monkey_patched = True
QgsPalLayerSettings.MinScale.__doc__ = "Min scale (deprecated, for old project compatibility only)"
QgsPalLayerSettings.MinimumScale = QgsPalLayerSettings.Property.MinimumScale
QgsPalLayerSettings.MinimumScale.is_monkey_patched = True
QgsPalLayerSettings.MinimumScale.__doc__ = "Minimum map scale (ie most \"zoomed out\")"
QgsPalLayerSettings.MaxScale = QgsPalLayerSettings.Property.MaxScale
QgsPalLayerSettings.MaxScale.is_monkey_patched = True
QgsPalLayerSettings.MaxScale.__doc__ = "Max scale (deprecated, for old project compatibility only)"
QgsPalLayerSettings.MaximumScale = QgsPalLayerSettings.Property.MaximumScale
QgsPalLayerSettings.MaximumScale.is_monkey_patched = True
QgsPalLayerSettings.MaximumScale.__doc__ = "Maximum map scale (ie most \"zoomed in\")"
QgsPalLayerSettings.FontLimitPixel = QgsPalLayerSettings.Property.FontLimitPixel
QgsPalLayerSettings.FontLimitPixel.is_monkey_patched = True
QgsPalLayerSettings.FontLimitPixel.__doc__ = ""
QgsPalLayerSettings.FontMinPixel = QgsPalLayerSettings.Property.FontMinPixel
QgsPalLayerSettings.FontMinPixel.is_monkey_patched = True
QgsPalLayerSettings.FontMinPixel.__doc__ = ""
QgsPalLayerSettings.FontMaxPixel = QgsPalLayerSettings.Property.FontMaxPixel
QgsPalLayerSettings.FontMaxPixel.is_monkey_patched = True
QgsPalLayerSettings.FontMaxPixel.__doc__ = ""
QgsPalLayerSettings.IsObstacle = QgsPalLayerSettings.Property.IsObstacle
QgsPalLayerSettings.IsObstacle.is_monkey_patched = True
QgsPalLayerSettings.IsObstacle.__doc__ = ""
QgsPalLayerSettings.ObstacleFactor = QgsPalLayerSettings.Property.ObstacleFactor
QgsPalLayerSettings.ObstacleFactor.is_monkey_patched = True
QgsPalLayerSettings.ObstacleFactor.__doc__ = ""
QgsPalLayerSettings.ZIndex = QgsPalLayerSettings.Property.ZIndex
QgsPalLayerSettings.ZIndex.is_monkey_patched = True
QgsPalLayerSettings.ZIndex.__doc__ = ""
QgsPalLayerSettings.CalloutDraw = QgsPalLayerSettings.Property.CalloutDraw
QgsPalLayerSettings.CalloutDraw.is_monkey_patched = True
QgsPalLayerSettings.CalloutDraw.__doc__ = "Show callout"
QgsPalLayerSettings.AllowDegradedPlacement = QgsPalLayerSettings.Property.AllowDegradedPlacement
QgsPalLayerSettings.AllowDegradedPlacement.is_monkey_patched = True
QgsPalLayerSettings.AllowDegradedPlacement.__doc__ = "Allow degraded label placements (since QGIS 3.26)"
QgsPalLayerSettings.OverlapHandling = QgsPalLayerSettings.Property.OverlapHandling
QgsPalLayerSettings.OverlapHandling.is_monkey_patched = True
QgsPalLayerSettings.OverlapHandling.__doc__ = "Overlap handling technique (since QGIS 3.26)"
QgsPalLayerSettings.Show = QgsPalLayerSettings.Property.Show
QgsPalLayerSettings.Show.is_monkey_patched = True
QgsPalLayerSettings.Show.__doc__ = ""
QgsPalLayerSettings.AlwaysShow = QgsPalLayerSettings.Property.AlwaysShow
QgsPalLayerSettings.AlwaysShow.is_monkey_patched = True
QgsPalLayerSettings.AlwaysShow.__doc__ = ""
QgsPalLayerSettings.Property.__doc__ = "Data definable properties.\n\n" + '* ``Size``: ' + QgsPalLayerSettings.Property.Size.__doc__ + '\n' + '* ``Bold``: ' + QgsPalLayerSettings.Property.Bold.__doc__ + '\n' + '* ``Italic``: ' + QgsPalLayerSettings.Property.Italic.__doc__ + '\n' + '* ``Underline``: ' + QgsPalLayerSettings.Property.Underline.__doc__ + '\n' + '* ``Color``: ' + QgsPalLayerSettings.Property.Color.__doc__ + '\n' + '* ``Strikeout``: ' + QgsPalLayerSettings.Property.Strikeout.__doc__ + '\n' + '* ``Family``: ' + QgsPalLayerSettings.Property.Family.__doc__ + '\n' + '* ``FontStyle``: ' + QgsPalLayerSettings.Property.FontStyle.__doc__ + '\n' + '* ``FontSizeUnit``: ' + QgsPalLayerSettings.Property.FontSizeUnit.__doc__ + '\n' + '* ``FontTransp``: ' + QgsPalLayerSettings.Property.FontTransp.__doc__ + '\n' + '* ``FontOpacity``: ' + QgsPalLayerSettings.Property.FontOpacity.__doc__ + '\n' + '* ``FontCase``: ' + QgsPalLayerSettings.Property.FontCase.__doc__ + '\n' + '* ``FontLetterSpacing``: ' + QgsPalLayerSettings.Property.FontLetterSpacing.__doc__ + '\n' + '* ``FontWordSpacing``: ' + QgsPalLayerSettings.Property.FontWordSpacing.__doc__ + '\n' + '* ``FontBlendMode``: ' + QgsPalLayerSettings.Property.FontBlendMode.__doc__ + '\n' + '* ``FontStretchFactor``: ' + QgsPalLayerSettings.Property.FontStretchFactor.__doc__ + '\n' + '* ``MultiLineWrapChar``: ' + QgsPalLayerSettings.Property.MultiLineWrapChar.__doc__ + '\n' + '* ``AutoWrapLength``: ' + QgsPalLayerSettings.Property.AutoWrapLength.__doc__ + '\n' + '* ``MultiLineHeight``: ' + QgsPalLayerSettings.Property.MultiLineHeight.__doc__ + '\n' + '* ``MultiLineAlignment``: ' + QgsPalLayerSettings.Property.MultiLineAlignment.__doc__ + '\n' + '* ``TextOrientation``: ' + QgsPalLayerSettings.Property.TextOrientation.__doc__ + '\n' + '* ``TabStopDistance``: ' + QgsPalLayerSettings.Property.TabStopDistance.__doc__ + '\n' + '* ``DirSymbDraw``: ' + QgsPalLayerSettings.Property.DirSymbDraw.__doc__ + '\n' + '* ``DirSymbLeft``: ' + QgsPalLayerSettings.Property.DirSymbLeft.__doc__ + '\n' + '* ``DirSymbRight``: ' + QgsPalLayerSettings.Property.DirSymbRight.__doc__ + '\n' + '* ``DirSymbPlacement``: ' + QgsPalLayerSettings.Property.DirSymbPlacement.__doc__ + '\n' + '* ``DirSymbReverse``: ' + QgsPalLayerSettings.Property.DirSymbReverse.__doc__ + '\n' + '* ``NumFormat``: ' + QgsPalLayerSettings.Property.NumFormat.__doc__ + '\n' + '* ``NumDecimals``: ' + QgsPalLayerSettings.Property.NumDecimals.__doc__ + '\n' + '* ``NumPlusSign``: ' + QgsPalLayerSettings.Property.NumPlusSign.__doc__ + '\n' + '* ``BufferDraw``: ' + QgsPalLayerSettings.Property.BufferDraw.__doc__ + '\n' + '* ``BufferSize``: ' + QgsPalLayerSettings.Property.BufferSize.__doc__ + '\n' + '* ``BufferUnit``: ' + QgsPalLayerSettings.Property.BufferUnit.__doc__ + '\n' + '* ``BufferColor``: ' + QgsPalLayerSettings.Property.BufferColor.__doc__ + '\n' + '* ``BufferTransp``: ' + QgsPalLayerSettings.Property.BufferTransp.__doc__ + '\n' + '* ``BufferOpacity``: ' + QgsPalLayerSettings.Property.BufferOpacity.__doc__ + '\n' + '* ``BufferJoinStyle``: ' + QgsPalLayerSettings.Property.BufferJoinStyle.__doc__ + '\n' + '* ``BufferBlendMode``: ' + QgsPalLayerSettings.Property.BufferBlendMode.__doc__ + '\n' + '* ``MaskEnabled``: ' + QgsPalLayerSettings.Property.MaskEnabled.__doc__ + '\n' + '* ``MaskBufferSize``: ' + QgsPalLayerSettings.Property.MaskBufferSize.__doc__ + '\n' + '* ``MaskBufferUnit``: ' + QgsPalLayerSettings.Property.MaskBufferUnit.__doc__ + '\n' + '* ``MaskOpacity``: ' + QgsPalLayerSettings.Property.MaskOpacity.__doc__ + '\n' + '* ``MaskJoinStyle``: ' + QgsPalLayerSettings.Property.MaskJoinStyle.__doc__ + '\n' + '* ``ShapeDraw``: ' + QgsPalLayerSettings.Property.ShapeDraw.__doc__ + '\n' + '* ``ShapeKind``: ' + QgsPalLayerSettings.Property.ShapeKind.__doc__ + '\n' + '* ``ShapeSVGFile``: ' + QgsPalLayerSettings.Property.ShapeSVGFile.__doc__ + '\n' + '* ``ShapeSizeType``: ' + QgsPalLayerSettings.Property.ShapeSizeType.__doc__ + '\n' + '* ``ShapeSizeX``: ' + QgsPalLayerSettings.Property.ShapeSizeX.__doc__ + '\n' + '* ``ShapeSizeY``: ' + QgsPalLayerSettings.Property.ShapeSizeY.__doc__ + '\n' + '* ``ShapeSizeUnits``: ' + QgsPalLayerSettings.Property.ShapeSizeUnits.__doc__ + '\n' + '* ``ShapeRotationType``: ' + QgsPalLayerSettings.Property.ShapeRotationType.__doc__ + '\n' + '* ``ShapeRotation``: ' + QgsPalLayerSettings.Property.ShapeRotation.__doc__ + '\n' + '* ``ShapeOffset``: ' + QgsPalLayerSettings.Property.ShapeOffset.__doc__ + '\n' + '* ``ShapeOffsetUnits``: ' + QgsPalLayerSettings.Property.ShapeOffsetUnits.__doc__ + '\n' + '* ``ShapeRadii``: ' + QgsPalLayerSettings.Property.ShapeRadii.__doc__ + '\n' + '* ``ShapeRadiiUnits``: ' + QgsPalLayerSettings.Property.ShapeRadiiUnits.__doc__ + '\n' + '* ``ShapeTransparency``: ' + QgsPalLayerSettings.Property.ShapeTransparency.__doc__ + '\n' + '* ``ShapeOpacity``: ' + QgsPalLayerSettings.Property.ShapeOpacity.__doc__ + '\n' + '* ``ShapeBlendMode``: ' + QgsPalLayerSettings.Property.ShapeBlendMode.__doc__ + '\n' + '* ``ShapeFillColor``: ' + QgsPalLayerSettings.Property.ShapeFillColor.__doc__ + '\n' + '* ``ShapeStrokeColor``: ' + QgsPalLayerSettings.Property.ShapeStrokeColor.__doc__ + '\n' + '* ``ShapeStrokeWidth``: ' + QgsPalLayerSettings.Property.ShapeStrokeWidth.__doc__ + '\n' + '* ``ShapeStrokeWidthUnits``: ' + QgsPalLayerSettings.Property.ShapeStrokeWidthUnits.__doc__ + '\n' + '* ``ShapeJoinStyle``: ' + QgsPalLayerSettings.Property.ShapeJoinStyle.__doc__ + '\n' + '* ``ShadowDraw``: ' + QgsPalLayerSettings.Property.ShadowDraw.__doc__ + '\n' + '* ``ShadowUnder``: ' + QgsPalLayerSettings.Property.ShadowUnder.__doc__ + '\n' + '* ``ShadowOffsetAngle``: ' + QgsPalLayerSettings.Property.ShadowOffsetAngle.__doc__ + '\n' + '* ``ShadowOffsetDist``: ' + QgsPalLayerSettings.Property.ShadowOffsetDist.__doc__ + '\n' + '* ``ShadowOffsetUnits``: ' + QgsPalLayerSettings.Property.ShadowOffsetUnits.__doc__ + '\n' + '* ``ShadowRadius``: ' + QgsPalLayerSettings.Property.ShadowRadius.__doc__ + '\n' + '* ``ShadowRadiusUnits``: ' + QgsPalLayerSettings.Property.ShadowRadiusUnits.__doc__ + '\n' + '* ``ShadowTransparency``: ' + QgsPalLayerSettings.Property.ShadowTransparency.__doc__ + '\n' + '* ``ShadowOpacity``: ' + QgsPalLayerSettings.Property.ShadowOpacity.__doc__ + '\n' + '* ``ShadowScale``: ' + QgsPalLayerSettings.Property.ShadowScale.__doc__ + '\n' + '* ``ShadowColor``: ' + QgsPalLayerSettings.Property.ShadowColor.__doc__ + '\n' + '* ``ShadowBlendMode``: ' + QgsPalLayerSettings.Property.ShadowBlendMode.__doc__ + '\n' + '* ``CentroidWhole``: ' + QgsPalLayerSettings.Property.CentroidWhole.__doc__ + '\n' + '* ``OffsetQuad``: ' + QgsPalLayerSettings.Property.OffsetQuad.__doc__ + '\n' + '* ``OffsetXY``: ' + QgsPalLayerSettings.Property.OffsetXY.__doc__ + '\n' + '* ``OffsetUnits``: ' + QgsPalLayerSettings.Property.OffsetUnits.__doc__ + '\n' + '* ``LabelDistance``: ' + QgsPalLayerSettings.Property.LabelDistance.__doc__ + '\n' + '* ``MaximumDistance``: ' + QgsPalLayerSettings.Property.MaximumDistance.__doc__ + '\n' + '* ``DistanceUnits``: ' + QgsPalLayerSettings.Property.DistanceUnits.__doc__ + '\n' + '* ``OffsetRotation``: ' + QgsPalLayerSettings.Property.OffsetRotation.__doc__ + '\n' + '* ``CurvedCharAngleInOut``: ' + QgsPalLayerSettings.Property.CurvedCharAngleInOut.__doc__ + '\n' + '* ``PositionX``: ' + QgsPalLayerSettings.Property.PositionX.__doc__ + '\n' + '* ``PositionY``: ' + QgsPalLayerSettings.Property.PositionY.__doc__ + '\n' + '* ``PositionPoint``: ' + QgsPalLayerSettings.Property.PositionPoint.__doc__ + '\n' + '* ``Hali``: ' + QgsPalLayerSettings.Property.Hali.__doc__ + '\n' + '* ``Vali``: ' + QgsPalLayerSettings.Property.Vali.__doc__ + '\n' + '* ``Rotation``: ' + QgsPalLayerSettings.Property.Rotation.__doc__ + '\n' + '* ``LabelRotation``: ' + QgsPalLayerSettings.Property.LabelRotation.__doc__ + '\n' + '* ``RepeatDistance``: ' + QgsPalLayerSettings.Property.RepeatDistance.__doc__ + '\n' + '* ``RepeatDistanceUnit``: ' + QgsPalLayerSettings.Property.RepeatDistanceUnit.__doc__ + '\n' + '* ``Priority``: ' + QgsPalLayerSettings.Property.Priority.__doc__ + '\n' + '* ``PredefinedPositionOrder``: ' + QgsPalLayerSettings.Property.PredefinedPositionOrder.__doc__ + '\n' + '* ``LinePlacementOptions``: ' + QgsPalLayerSettings.Property.LinePlacementOptions.__doc__ + '\n' + '* ``OverrunDistance``: ' + QgsPalLayerSettings.Property.OverrunDistance.__doc__ + '\n' + '* ``LabelAllParts``: ' + QgsPalLayerSettings.Property.LabelAllParts.__doc__ + '\n' + '* ``PolygonLabelOutside``: ' + QgsPalLayerSettings.Property.PolygonLabelOutside.__doc__ + '\n' + '* ``LineAnchorPercent``: ' + QgsPalLayerSettings.Property.LineAnchorPercent.__doc__ + '\n' + '* ``LineAnchorClipping``: ' + QgsPalLayerSettings.Property.LineAnchorClipping.__doc__ + '\n' + '* ``LineAnchorType``: ' + QgsPalLayerSettings.Property.LineAnchorType.__doc__ + '\n' + '* ``LineAnchorTextPoint``: ' + QgsPalLayerSettings.Property.LineAnchorTextPoint.__doc__ + '\n' + '* ``ScaleVisibility``: ' + QgsPalLayerSettings.Property.ScaleVisibility.__doc__ + '\n' + '* ``MinScale``: ' + QgsPalLayerSettings.Property.MinScale.__doc__ + '\n' + '* ``MinimumScale``: ' + QgsPalLayerSettings.Property.MinimumScale.__doc__ + '\n' + '* ``MaxScale``: ' + QgsPalLayerSettings.Property.MaxScale.__doc__ + '\n' + '* ``MaximumScale``: ' + QgsPalLayerSettings.Property.MaximumScale.__doc__ + '\n' + '* ``FontLimitPixel``: ' + QgsPalLayerSettings.Property.FontLimitPixel.__doc__ + '\n' + '* ``FontMinPixel``: ' + QgsPalLayerSettings.Property.FontMinPixel.__doc__ + '\n' + '* ``FontMaxPixel``: ' + QgsPalLayerSettings.Property.FontMaxPixel.__doc__ + '\n' + '* ``IsObstacle``: ' + QgsPalLayerSettings.Property.IsObstacle.__doc__ + '\n' + '* ``ObstacleFactor``: ' + QgsPalLayerSettings.Property.ObstacleFactor.__doc__ + '\n' + '* ``ZIndex``: ' + QgsPalLayerSettings.Property.ZIndex.__doc__ + '\n' + '* ``CalloutDraw``: ' + QgsPalLayerSettings.Property.CalloutDraw.__doc__ + '\n' + '* ``AllowDegradedPlacement``: ' + QgsPalLayerSettings.Property.AllowDegradedPlacement.__doc__ + '\n' + '* ``OverlapHandling``: ' + QgsPalLayerSettings.Property.OverlapHandling.__doc__ + '\n' + '* ``Show``: ' + QgsPalLayerSettings.Property.Show.__doc__ + '\n' + '* ``AlwaysShow``: ' + QgsPalLayerSettings.Property.AlwaysShow.__doc__
# --
QgsPalLayerSettings.__attribute_docs__ = {'drawLabels': 'Whether to draw labels for this layer. For some layers it may be desirable\nto register their features as obstacles for other labels without requiring\nlabels to be drawn for the layer itself. In this case drawLabels can be set\nto ``False`` and obstacle set to ``True``, which will result in the layer acting\nas an obstacle but having no labels of its own.', 'fieldName': 'Name of field (or an expression) to use for label text.\nIf fieldName is an expression, then isExpression should be set to ``True``.\n\n.. seealso:: :py:func:`isExpression`', 'isExpression': "``True`` if this label is made from a expression string, e.g., FieldName || 'mm'\n\n.. seealso:: :py:func:`fieldName`", 'previewBkgrdColor': '\n.. deprecated:: QGIS 3.10.\n   Use :py:func:`QgsTextFormat.previewBackgroundColor()` instead.', 'substitutions': 'Substitution collection for automatic text substitution with labels', 'useSubstitutions': 'True if substitutions should be applied', 'wrapChar': 'Wrapping character string. If set, any occurrences of this string in the calculated\nlabel text will be replaced with new line characters.', 'autoWrapLength': 'If non-zero, indicates that label text should be automatically wrapped to (ideally) the specified\nnumber of characters. If zero, auto wrapping is disabled.\n\n.. seealso:: :py:func:`useMaxLineLengthForAutoWrap`\n\n.. versionadded:: 3.4', 'useMaxLineLengthForAutoWrap': 'If ``True``, indicates that when auto wrapping label text the autoWrapLength length indicates the maximum\nideal length of text lines. If ``False``, then autoWrapLength indicates the ideal minimum length of text\nlines.\n\nIf autoWrapLength is 0 then this value has no effect.\n\n.. seealso:: :py:func:`autoWrapLength`\n\n.. versionadded:: 3.4', 'multilineAlign': 'Horizontal alignment of multi-line labels.', 'formatNumbers': 'Set to ``True`` to format numeric label text as numbers (e.g. inserting thousand separators\nand fixed number of decimal places).\n\n.. seealso:: :py:func:`decimals`\n\n.. seealso:: :py:func:`plusSign`', 'decimals': 'Number of decimal places to show for numeric labels. formatNumbers must be ``True`` for this\nsetting to have an effect.\n\n.. seealso:: :py:func:`formatNumbers`', 'plusSign': "Whether '+' signs should be prepended to positive numeric labels. formatNumbers must be ``True`` for this\nsetting to have an effect.\n\n.. seealso:: :py:func:`formatNumbers`", 'placement': 'Label placement mode', 'centroidWhole': '``True`` if feature centroid should be calculated from the whole feature, or\n``False`` if only the visible part of the feature should be considered.', 'centroidInside': '``True`` if centroid positioned labels must be placed inside their corresponding\nfeature polygon, or ``False`` if centroids which fall outside the polygon\nare permitted.', 'fitInPolygonOnly': '``True`` if only labels which completely fit within a polygon are allowed.', 'dist': 'Distance from feature to the label. Units are specified via distUnits.\n\n.. seealso:: :py:func:`distUnits`\n\n.. seealso:: :py:func:`distMapUnitScale`', 'distUnits': 'Units the distance from feature to the label.\n\n.. seealso:: :py:func:`dist`\n\n.. seealso:: :py:func:`distMapUnitScale`', 'distMapUnitScale': 'Map unit scale for label feature distance.\n\n.. seealso:: :py:func:`dist`\n\n.. seealso:: :py:func:`distUnits`', 'offsetType': 'Offset type for layer (only applies in certain placement modes)', 'repeatDistance': 'Distance for repeating labels for a single feature.\n\n.. seealso:: :py:func:`repeatDistanceUnit`\n\n.. seealso:: :py:func:`repeatDistanceMapUnitScale`', 'repeatDistanceUnit': 'Units for repeating labels for a single feature.\n\n.. seealso:: :py:func:`repeatDistance`\n\n.. seealso:: :py:func:`repeatDistanceMapUnitScale`', 'repeatDistanceMapUnitScale': 'Map unit scale for repeating labels for a single feature.\n\n.. seealso:: :py:func:`repeatDistance`\n\n.. seealso:: :py:func:`repeatDistanceUnit`', 'xOffset': 'Horizontal offset of label. Units are specified via offsetUnits.\n\n.. seealso:: :py:func:`yOffset`\n\n.. seealso:: :py:func:`offsetUnits`\n\n.. seealso:: :py:func:`labelOffsetMapUnitScale`', 'yOffset': 'Vertical offset of label. Units are specified via offsetUnits.\n\n.. seealso:: :py:func:`xOffset`\n\n.. seealso:: :py:func:`offsetUnits`\n\n.. seealso:: :py:func:`labelOffsetMapUnitScale`', 'offsetUnits': 'Units for offsets of label.\n\n.. seealso:: :py:func:`xOffset`\n\n.. seealso:: :py:func:`yOffset`\n\n.. seealso:: :py:func:`labelOffsetMapUnitScale`', 'labelOffsetMapUnitScale': 'Map unit scale for label offset.\n\n.. seealso:: :py:func:`xOffset`\n\n.. seealso:: :py:func:`yOffset`\n\n.. seealso:: :py:func:`offsetUnits`', 'angleOffset': 'Label rotation, in degrees clockwise', 'preserveRotation': 'True if label rotation should be preserved during label pin/unpin operations.', 'maxCurvedCharAngleIn': 'Maximum angle between inside curved label characters (valid range 20.0 to 60.0).\n\n.. seealso:: :py:func:`maxCurvedCharAngleOut`', 'maxCurvedCharAngleOut': 'Maximum angle between outside curved label characters (valid range -20.0 to -95.0)\n\n.. seealso:: :py:func:`maxCurvedCharAngleIn`', 'priority': 'Label priority. Valid ranges are from 0 to 10, where 0 = lowest priority\nand 10 = highest priority.', 'scaleVisibility': 'Set to ``True`` to limit label visibility to a range of scales.\n\n.. seealso:: :py:func:`maximumScale`\n\n.. seealso:: :py:func:`minimumScale`', 'maximumScale': 'The maximum map scale (i.e. most "zoomed in" scale) at which the labels will be visible.\nThe scale value indicates the scale denominator, e.g. 1000.0 for a 1:1000 map.\nA scale of 0 indicates no maximum scale visibility.\n\nThis setting is only considered if scaleVisibility is ``True``.\n\n.. seealso:: :py:func:`minimumScale`\n\n.. seealso:: :py:func:`scaleVisibility`', 'minimumScale': 'The minimum map scale (i.e. most "zoomed out" scale) at which the labels will be visible.\nThe scale value indicates the scale denominator, e.g. 1000.0 for a 1:1000 map.\nA scale of 0 indicates no minimum scale visibility.\n\nThis setting is only considered if scaleVisibility is ``True``.\n\n.. seealso:: :py:func:`maximumScale`\n\n.. seealso:: :py:func:`scaleVisibility`', 'fontLimitPixelSize': '``True`` if label sizes should be limited by pixel size.\n\n.. seealso:: :py:func:`fontMinPixelSize`\n\n.. seealso:: :py:func:`fontMaxPixelSize`', 'fontMinPixelSize': 'Minimum pixel size for showing rendered map unit labels (1 - 1000).\n\n.. seealso:: :py:func:`fontLimitPixelSize`\n\n.. seealso:: :py:func:`fontMaxPixelSize`', 'fontMaxPixelSize': 'Maximum pixel size for showing rendered map unit labels (1 - 10000).\n\n.. seealso:: :py:func:`fontLimitPixelSize`\n\n.. seealso:: :py:func:`fontMinPixelSize`', 'upsidedownLabels': 'Controls whether upside down labels are displayed and how they are handled.', 'labelPerPart': '``True`` if every part of a multi-part feature should be labeled. If ``False``,\nonly the largest part will be labeled.', 'zIndex': 'Z-Index of label, where labels with a higher z-index are rendered on top of labels with a lower z-index', 'geometryGenerator': 'The geometry generator expression. Null if disabled.', 'geometryGeneratorType': 'The type of the result geometry of the geometry generator.', 'geometryGeneratorEnabled': 'Defines if the geometry generator is enabled or not. If disabled, the standard geometry will be taken.', 'layerType': 'Geometry type of layers associated with these settings.\n\n.. versionadded:: 3.10'}
