# The following has been generated automatically from src/core/proj/qgsprojutils.h
QgsProjUtils.projVersionMajor = staticmethod(QgsProjUtils.projVersionMajor)
QgsProjUtils.projVersionMinor = staticmethod(QgsProjUtils.projVersionMinor)
QgsProjUtils.epsgRegistryVersion = staticmethod(QgsProjUtils.epsgRegistryVersion)
QgsProjUtils.epsgRegistryDate = staticmethod(QgsProjUtils.epsgRegistryDate)
QgsProjUtils.esriDatabaseVersion = staticmethod(QgsProjUtils.esriDatabaseVersion)
QgsProjUtils.esriDatabaseDate = staticmethod(QgsProjUtils.esriDatabaseDate)
QgsProjUtils.ignfDatabaseVersion = staticmethod(QgsProjUtils.ignfDatabaseVersion)
QgsProjUtils.ignfDatabaseDate = staticmethod(QgsProjUtils.ignfDatabaseDate)
QgsProjUtils.searchPaths = staticmethod(QgsProjUtils.searchPaths)
