# The following has been generated automatically from src/core/symbology/qgspointdisplacementrenderer.h
QgsPointDisplacementRenderer.create = staticmethod(QgsPointDisplacementRenderer.create)
QgsPointDisplacementRenderer.convertFromRenderer = staticmethod(QgsPointDisplacementRenderer.convertFromRenderer)
