# The following has been generated automatically from src/core/qgspropertytransformer.h
QgsPropertyTransformer.create = staticmethod(QgsPropertyTransformer.create)
QgsPropertyTransformer.fromExpression = staticmethod(QgsPropertyTransformer.fromExpression)
QgsGenericNumericTransformer.fromExpression = staticmethod(QgsGenericNumericTransformer.fromExpression)
QgsSizeScaleTransformer.fromExpression = staticmethod(QgsSizeScaleTransformer.fromExpression)
