# The following has been generated automatically from src/core/processing/qgsprocessingparameterdxflayers.h
QgsProcessingParameterDxfLayers.typeName = staticmethod(QgsProcessingParameterDxfLayers.typeName)
QgsProcessingParameterDxfLayers.parameterAsLayers = staticmethod(QgsProcessingParameterDxfLayers.parameterAsLayers)
QgsProcessingParameterDxfLayers.variantMapAsLayer = staticmethod(QgsProcessingParameterDxfLayers.variantMapAsLayer)
QgsProcessingParameterDxfLayers.layerAsVariantMap = staticmethod(QgsProcessingParameterDxfLayers.layerAsVariantMap)
