# The following has been generated automatically from src/core/qgsstatisticalsummary.h
# monkey patching scoped based enum
QgsStatisticalSummary.Count = QgsStatisticalSummary.Statistic.Count
QgsStatisticalSummary.Count.is_monkey_patched = True
QgsStatisticalSummary.Count.__doc__ = "Count"
QgsStatisticalSummary.CountMissing = QgsStatisticalSummary.Statistic.CountMissing
QgsStatisticalSummary.CountMissing.is_monkey_patched = True
QgsStatisticalSummary.CountMissing.__doc__ = "Number of missing (null) values"
QgsStatisticalSummary.Sum = QgsStatisticalSummary.Statistic.Sum
QgsStatisticalSummary.Sum.is_monkey_patched = True
QgsStatisticalSummary.Sum.__doc__ = "Sum of values"
QgsStatisticalSummary.Mean = QgsStatisticalSummary.Statistic.Mean
QgsStatisticalSummary.Mean.is_monkey_patched = True
QgsStatisticalSummary.Mean.__doc__ = "Mean of values"
QgsStatisticalSummary.Median = QgsStatisticalSummary.Statistic.Median
QgsStatisticalSummary.Median.is_monkey_patched = True
QgsStatisticalSummary.Median.__doc__ = "Median of values"
QgsStatisticalSummary.StDev = QgsStatisticalSummary.Statistic.StDev
QgsStatisticalSummary.StDev.is_monkey_patched = True
QgsStatisticalSummary.StDev.__doc__ = "Standard deviation of values"
QgsStatisticalSummary.StDevSample = QgsStatisticalSummary.Statistic.StDevSample
QgsStatisticalSummary.StDevSample.is_monkey_patched = True
QgsStatisticalSummary.StDevSample.__doc__ = "Sample standard deviation of values"
QgsStatisticalSummary.Min = QgsStatisticalSummary.Statistic.Min
QgsStatisticalSummary.Min.is_monkey_patched = True
QgsStatisticalSummary.Min.__doc__ = "Min of values"
QgsStatisticalSummary.Max = QgsStatisticalSummary.Statistic.Max
QgsStatisticalSummary.Max.is_monkey_patched = True
QgsStatisticalSummary.Max.__doc__ = "Max of values"
QgsStatisticalSummary.Range = QgsStatisticalSummary.Statistic.Range
QgsStatisticalSummary.Range.is_monkey_patched = True
QgsStatisticalSummary.Range.__doc__ = "Range of values (max - min)"
QgsStatisticalSummary.Minority = QgsStatisticalSummary.Statistic.Minority
QgsStatisticalSummary.Minority.is_monkey_patched = True
QgsStatisticalSummary.Minority.__doc__ = "Minority of values"
QgsStatisticalSummary.Majority = QgsStatisticalSummary.Statistic.Majority
QgsStatisticalSummary.Majority.is_monkey_patched = True
QgsStatisticalSummary.Majority.__doc__ = "Majority of values"
QgsStatisticalSummary.Variety = QgsStatisticalSummary.Statistic.Variety
QgsStatisticalSummary.Variety.is_monkey_patched = True
QgsStatisticalSummary.Variety.__doc__ = "Variety (count of distinct) values"
QgsStatisticalSummary.FirstQuartile = QgsStatisticalSummary.Statistic.FirstQuartile
QgsStatisticalSummary.FirstQuartile.is_monkey_patched = True
QgsStatisticalSummary.FirstQuartile.__doc__ = "First quartile"
QgsStatisticalSummary.ThirdQuartile = QgsStatisticalSummary.Statistic.ThirdQuartile
QgsStatisticalSummary.ThirdQuartile.is_monkey_patched = True
QgsStatisticalSummary.ThirdQuartile.__doc__ = "Third quartile"
QgsStatisticalSummary.InterQuartileRange = QgsStatisticalSummary.Statistic.InterQuartileRange
QgsStatisticalSummary.InterQuartileRange.is_monkey_patched = True
QgsStatisticalSummary.InterQuartileRange.__doc__ = "Inter quartile range (IQR)"
QgsStatisticalSummary.First = QgsStatisticalSummary.Statistic.First
QgsStatisticalSummary.First.is_monkey_patched = True
QgsStatisticalSummary.First.__doc__ = "First value (since QGIS 3.6)"
QgsStatisticalSummary.Last = QgsStatisticalSummary.Statistic.Last
QgsStatisticalSummary.Last.is_monkey_patched = True
QgsStatisticalSummary.Last.__doc__ = "Last value (since QGIS 3.6)"
QgsStatisticalSummary.All = QgsStatisticalSummary.Statistic.All
QgsStatisticalSummary.All.is_monkey_patched = True
QgsStatisticalSummary.All.__doc__ = "All statistics"
QgsStatisticalSummary.Statistic.__doc__ = "Enumeration of flags that specify statistics to be calculated\n\n" + '* ``Count``: ' + QgsStatisticalSummary.Statistic.Count.__doc__ + '\n' + '* ``CountMissing``: ' + QgsStatisticalSummary.Statistic.CountMissing.__doc__ + '\n' + '* ``Sum``: ' + QgsStatisticalSummary.Statistic.Sum.__doc__ + '\n' + '* ``Mean``: ' + QgsStatisticalSummary.Statistic.Mean.__doc__ + '\n' + '* ``Median``: ' + QgsStatisticalSummary.Statistic.Median.__doc__ + '\n' + '* ``StDev``: ' + QgsStatisticalSummary.Statistic.StDev.__doc__ + '\n' + '* ``StDevSample``: ' + QgsStatisticalSummary.Statistic.StDevSample.__doc__ + '\n' + '* ``Min``: ' + QgsStatisticalSummary.Statistic.Min.__doc__ + '\n' + '* ``Max``: ' + QgsStatisticalSummary.Statistic.Max.__doc__ + '\n' + '* ``Range``: ' + QgsStatisticalSummary.Statistic.Range.__doc__ + '\n' + '* ``Minority``: ' + QgsStatisticalSummary.Statistic.Minority.__doc__ + '\n' + '* ``Majority``: ' + QgsStatisticalSummary.Statistic.Majority.__doc__ + '\n' + '* ``Variety``: ' + QgsStatisticalSummary.Statistic.Variety.__doc__ + '\n' + '* ``FirstQuartile``: ' + QgsStatisticalSummary.Statistic.FirstQuartile.__doc__ + '\n' + '* ``ThirdQuartile``: ' + QgsStatisticalSummary.Statistic.ThirdQuartile.__doc__ + '\n' + '* ``InterQuartileRange``: ' + QgsStatisticalSummary.Statistic.InterQuartileRange.__doc__ + '\n' + '* ``First``: ' + QgsStatisticalSummary.Statistic.First.__doc__ + '\n' + '* ``Last``: ' + QgsStatisticalSummary.Statistic.Last.__doc__ + '\n' + '* ``All``: ' + QgsStatisticalSummary.Statistic.All.__doc__
# --
