# The following has been generated automatically from src/analysis/vector/qgszonalstatistics.h
# monkey patching scoped based enum
QgsZonalStatistics.Count = QgsZonalStatistics.Statistic.Count
QgsZonalStatistics.Count.is_monkey_patched = True
QgsZonalStatistics.Count.__doc__ = "Pixel count"
QgsZonalStatistics.Sum = QgsZonalStatistics.Statistic.Sum
QgsZonalStatistics.Sum.is_monkey_patched = True
QgsZonalStatistics.Sum.__doc__ = "Sum of pixel values"
QgsZonalStatistics.Mean = QgsZonalStatistics.Statistic.Mean
QgsZonalStatistics.Mean.is_monkey_patched = True
QgsZonalStatistics.Mean.__doc__ = "Mean of pixel values"
QgsZonalStatistics.Median = QgsZonalStatistics.Statistic.Median
QgsZonalStatistics.Median.is_monkey_patched = True
QgsZonalStatistics.Median.__doc__ = "Median of pixel values"
QgsZonalStatistics.StDev = QgsZonalStatistics.Statistic.StDev
QgsZonalStatistics.StDev.is_monkey_patched = True
QgsZonalStatistics.StDev.__doc__ = "Standard deviation of pixel values"
QgsZonalStatistics.Min = QgsZonalStatistics.Statistic.Min
QgsZonalStatistics.Min.is_monkey_patched = True
QgsZonalStatistics.Min.__doc__ = "Min of pixel values"
QgsZonalStatistics.Max = QgsZonalStatistics.Statistic.Max
QgsZonalStatistics.Max.is_monkey_patched = True
QgsZonalStatistics.Max.__doc__ = "Max of pixel values"
QgsZonalStatistics.Range = QgsZonalStatistics.Statistic.Range
QgsZonalStatistics.Range.is_monkey_patched = True
QgsZonalStatistics.Range.__doc__ = "Range of pixel values (max - min)"
QgsZonalStatistics.Minority = QgsZonalStatistics.Statistic.Minority
QgsZonalStatistics.Minority.is_monkey_patched = True
QgsZonalStatistics.Minority.__doc__ = "Minority of pixel values"
QgsZonalStatistics.Majority = QgsZonalStatistics.Statistic.Majority
QgsZonalStatistics.Majority.is_monkey_patched = True
QgsZonalStatistics.Majority.__doc__ = "Majority of pixel values"
QgsZonalStatistics.Variety = QgsZonalStatistics.Statistic.Variety
QgsZonalStatistics.Variety.is_monkey_patched = True
QgsZonalStatistics.Variety.__doc__ = "Variety (count of distinct) pixel values"
QgsZonalStatistics.Variance = QgsZonalStatistics.Statistic.Variance
QgsZonalStatistics.Variance.is_monkey_patched = True
QgsZonalStatistics.Variance.__doc__ = "Variance of pixel values"
QgsZonalStatistics.All = QgsZonalStatistics.Statistic.All
QgsZonalStatistics.All.is_monkey_patched = True
QgsZonalStatistics.All.__doc__ = ""
QgsZonalStatistics.Default = QgsZonalStatistics.Statistic.Default
QgsZonalStatistics.Default.is_monkey_patched = True
QgsZonalStatistics.Default.__doc__ = ""
QgsZonalStatistics.Statistic.__doc__ = "Enumeration of flags that specify statistics to be calculated\n\n" + '* ``Count``: ' + QgsZonalStatistics.Statistic.Count.__doc__ + '\n' + '* ``Sum``: ' + QgsZonalStatistics.Statistic.Sum.__doc__ + '\n' + '* ``Mean``: ' + QgsZonalStatistics.Statistic.Mean.__doc__ + '\n' + '* ``Median``: ' + QgsZonalStatistics.Statistic.Median.__doc__ + '\n' + '* ``StDev``: ' + QgsZonalStatistics.Statistic.StDev.__doc__ + '\n' + '* ``Min``: ' + QgsZonalStatistics.Statistic.Min.__doc__ + '\n' + '* ``Max``: ' + QgsZonalStatistics.Statistic.Max.__doc__ + '\n' + '* ``Range``: ' + QgsZonalStatistics.Statistic.Range.__doc__ + '\n' + '* ``Minority``: ' + QgsZonalStatistics.Statistic.Minority.__doc__ + '\n' + '* ``Majority``: ' + QgsZonalStatistics.Statistic.Majority.__doc__ + '\n' + '* ``Variety``: ' + QgsZonalStatistics.Statistic.Variety.__doc__ + '\n' + '* ``Variance``: ' + QgsZonalStatistics.Statistic.Variance.__doc__ + '\n' + '* ``All``: ' + QgsZonalStatistics.Statistic.All.__doc__ + '\n' + '* ``Default``: ' + QgsZonalStatistics.Statistic.Default.__doc__
# --
