"""QGIS Unit tests for post-processing layers generated by Processing.

.. note:: This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
"""

import unittest
from tempfile import TemporaryDirectory

from qgis.analysis import QgsNativeAlgorithms
from qgis.core import (
    QgsApplication,
    QgsFillSymbol,
    QgsLayerTreeGroup,
    QgsLineSymbol,
    QgsMarkerSymbol,
    QgsProcessingContext,
    QgsProcessingResultsHandler,
    QgsProject,
    QgsRasterLayer,
    QgsRasterSingleColorRenderer,
    QgsSettings,
    QgsSingleSymbolRenderer,
    QgsVectorLayer,
)
from qgis.PyQt.QtGui import QColor
from qgis.testing import QgisTestCase, start_app
from utilities import unitTestDataPath

start_app()
TEST_DATA_DIR = unitTestDataPath()


def create_polygon_layer():
    layer = QgsVectorLayer(
        "Polygon?field=fldtxt:string&field=fldint:integer", "addfeat", "memory"
    )
    assert layer.featureCount() == 0
    return layer


def create_line_layer():
    layer = QgsVectorLayer(
        "LineString?field=fldtxt:string&field=fldint:integer", "addfeat", "memory"
    )
    assert layer.featureCount() == 0
    return layer


def create_point_layer():
    layer = QgsVectorLayer(
        "Point?field=fldtxt:string&field=fldint:integer", "addfeat", "memory"
    )
    assert layer.featureCount() == 0
    return layer


class TestProcessingPostProcessing(QgisTestCase):
    @classmethod
    def setUpClass(cls):
        """Run before all tests"""
        super().setUpClass()
        QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())

    def test_default_style(self):
        alg = QgsApplication.processingRegistry().createAlgorithmById("native:buffer")

        layer = create_polygon_layer()
        with TemporaryDirectory() as tmpdir:
            # create a simple qml we can use for testing
            symbol = QgsFillSymbol.createSimple({"color": "#123456"})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer.setRenderer(renderer)

            layer.saveNamedStyle(tmpdir + "/polys1.qml")
            layer.renderer().symbol().setColor(QColor("#7890ab"))
            layer.saveNamedStyle(tmpdir + "/polys2.qml")

            registry = QgsApplication.processingRegistry().defaultStyleRegistry()
            registry.setDefaultStyleForOutput(
                "native:buffer", "OUTPUT", tmpdir + "/polys1.qml"
            )

            # a pretend output layer:
            layer2 = create_polygon_layer()
            symbol = QgsFillSymbol.createSimple({"color": "#ff0000"})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer2.setRenderer(renderer)
            self.assertEqual(layer2.renderer().symbol().color().name(), "#ff0000")

            QgsApplication.processingRegistry().layerPostProcessor().postProcessLayer(
                layer2, "OUTPUT", alg
            )

            self.assertEqual(layer2.renderer().symbol().color().name(), "#123456")

            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_POLYGON_STYLE", tmpdir + "/polys2.qml"
            )
            # specific layer style from defaultStyleRegistry should take precedence:
            layer3 = create_polygon_layer()
            QgsApplication.processingRegistry().layerPostProcessor().postProcessLayer(
                layer3, "OUTPUT", alg
            )
            self.assertEqual(layer3.renderer().symbol().color().name(), "#123456")

            # if no specific style for output, generic setting should apply
            registry.setDefaultStyleForOutput("native:buffer", "OUTPUT", None)
            layer4 = create_polygon_layer()
            QgsApplication.processingRegistry().layerPostProcessor().postProcessLayer(
                layer4, "OUTPUT", alg
            )
            self.assertEqual(layer4.renderer().symbol().color().name(), "#7890ab")

    def test_polygon_style(self):
        alg = QgsApplication.processingRegistry().createAlgorithmById("native:buffer")

        layer = create_polygon_layer()
        with TemporaryDirectory() as tmpdir:
            # create a simple qml we can use for testing
            symbol = QgsFillSymbol.createSimple({"color": "#123456"})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer.setRenderer(renderer)

            layer.saveNamedStyle(tmpdir + "/polys1.qml")
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_POLYGON_STYLE", tmpdir + "/polys1.qml"
            )
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_LINE_STYLE", tmpdir + "/lines1.qml"
            )
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_POINT_STYLE", tmpdir + "/points1.qml"
            )

            # a pretend output layer:
            layer2 = create_polygon_layer()
            symbol = QgsFillSymbol.createSimple({"color": "#ff0000"})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer2.setRenderer(renderer)
            self.assertEqual(layer2.renderer().symbol().color().name(), "#ff0000")

            QgsApplication.processingRegistry().layerPostProcessor().postProcessLayer(
                layer2, "OUTPUT", alg
            )

            self.assertEqual(layer2.renderer().symbol().color().name(), "#123456")

    def test_line_style(self):
        alg = QgsApplication.processingRegistry().createAlgorithmById("native:buffer")

        layer = create_line_layer()
        with TemporaryDirectory() as tmpdir:
            # create a simple qml we can use for testing
            symbol = QgsLineSymbol.createSimple({"color": "#123456"})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer.setRenderer(renderer)

            layer.saveNamedStyle(tmpdir + "/lines1.qml")
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_POLYGON_STYLE", tmpdir + "/polys1.qml"
            )
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_LINE_STYLE", tmpdir + "/lines1.qml"
            )
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_POINT_STYLE", tmpdir + "/points1.qml"
            )

            # a pretend output layer:
            layer2 = create_line_layer()
            symbol = QgsLineSymbol.createSimple({"color": "#ff0000"})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer2.setRenderer(renderer)
            self.assertEqual(layer2.renderer().symbol().color().name(), "#ff0000")

            QgsApplication.processingRegistry().layerPostProcessor().postProcessLayer(
                layer2, "OUTPUT", alg
            )

            self.assertEqual(layer2.renderer().symbol().color().name(), "#123456")

    def test_point_style(self):
        alg = QgsApplication.processingRegistry().createAlgorithmById("native:buffer")

        layer = create_point_layer()
        with TemporaryDirectory() as tmpdir:
            # create a simple qml we can use for testing
            symbol = QgsMarkerSymbol.createSimple({"color": "#123456"})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer.setRenderer(renderer)

            layer.saveNamedStyle(tmpdir + "/points1.qml")
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_POLYGON_STYLE", tmpdir + "/polys1.qml"
            )
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_LINE_STYLE", tmpdir + "/lines1.qml"
            )
            QgsSettings().setValue(
                "Processing/Configuration/VECTOR_POINT_STYLE", tmpdir + "/points1.qml"
            )

            # a pretend output layer:
            layer2 = create_point_layer()
            symbol = QgsMarkerSymbol.createSimple({"color": "#ff0000"})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer2.setRenderer(renderer)
            self.assertEqual(layer2.renderer().symbol().color().name(), "#ff0000")

            QgsApplication.processingRegistry().layerPostProcessor().postProcessLayer(
                layer2, "OUTPUT", alg
            )

            self.assertEqual(layer2.renderer().symbol().color().name(), "#123456")

    def test_raster_style(self):
        alg = QgsApplication.processingRegistry().createAlgorithmById("native:buffer")

        rl1 = QgsRasterLayer(TEST_DATA_DIR + "/raster_layer.tiff")
        self.assertTrue(rl1.isValid())

        with TemporaryDirectory() as tmpdir:
            # create a simple qml we can use for testing
            renderer = QgsRasterSingleColorRenderer(
                rl1.dataProvider(), 1, QColor("#123456")
            )
            rl1.setRenderer(renderer)

            rl1.saveNamedStyle(tmpdir + "/raster1.qml")
            QgsSettings().setValue(
                "Processing/Configuration/RASTER_STYLE", tmpdir + "/raster1.qml"
            )

            # a pretend output layer:
            rl2 = QgsRasterLayer(TEST_DATA_DIR + "/raster_layer.tiff")
            self.assertTrue(rl2.isValid())
            self.assertNotIsInstance(rl2.renderer(), QgsRasterSingleColorRenderer)

            QgsApplication.processingRegistry().layerPostProcessor().postProcessLayer(
                rl2, "OUTPUT", alg
            )

            self.assertIsInstance(rl2.renderer(), QgsRasterSingleColorRenderer)
            self.assertEqual(rl2.renderer().color().name(), "#123456")

    def test_layer_tree_result_group(self):
        project1 = QgsProject()
        project2 = QgsProject()

        context = QgsProcessingContext()
        context.setProject(project1)

        # no processing setting for result group
        QgsSettings().setValue("Processing/Configuration/RESULTS_GROUP_NAME", None)

        # no layer destination group
        layer_details = QgsProcessingContext.LayerDetails(
            "name", project2, "output_name"
        )
        self.assertIsNone(
            QgsProcessingResultsHandler.layerTreeResultsGroup(layer_details, context)
        )
        # no group should be created
        self.assertFalse(project1.layerTreeRoot().children())
        self.assertFalse(project2.layerTreeRoot().children())

        layer_details = QgsProcessingContext.LayerDetails(
            "name", project2, "output_name"
        )
        layer_details.groupName = "new group"
        new_group = QgsProcessingResultsHandler.layerTreeResultsGroup(
            layer_details, context
        )
        self.assertIsInstance(new_group, QgsLayerTreeGroup)
        self.assertEqual(new_group.name(), "new group")

        # group should be created in project2, as that was specified in the LayerDetails
        self.assertFalse(project1.layerTreeRoot().children())
        self.assertEqual(project2.layerTreeRoot().children(), [new_group])

        # no project, so should use project from context
        layer_details = QgsProcessingContext.LayerDetails("name", None, "output_name")
        layer_details.groupName = "new group2"
        new_group2 = QgsProcessingResultsHandler.layerTreeResultsGroup(
            layer_details, context
        )
        self.assertIsInstance(new_group2, QgsLayerTreeGroup)
        self.assertEqual(new_group2.name(), "new group2")
        # group should be created in project1, as that's specified in the context
        self.assertEqual(project1.layerTreeRoot().children(), [new_group2])
        self.assertEqual(project2.layerTreeRoot().children(), [new_group])

        # with processing setting for result group
        QgsSettings().setValue(
            "Processing/Configuration/RESULTS_GROUP_NAME", "parent group"
        )

        layer_details = QgsProcessingContext.LayerDetails(
            "name", project2, "output_name"
        )
        parent_group1 = QgsProcessingResultsHandler.layerTreeResultsGroup(
            layer_details, context
        )
        self.assertIsInstance(parent_group1, QgsLayerTreeGroup)
        self.assertEqual(parent_group1.name(), "parent group")
        self.assertCountEqual(
            project2.layerTreeRoot().children(), [new_group, parent_group1]
        )
        self.assertFalse(parent_group1.children())
        # same group should be used again if it already exists
        layer_details = QgsProcessingContext.LayerDetails(
            "name", project2, "output_name"
        )
        self.assertEqual(
            QgsProcessingResultsHandler.layerTreeResultsGroup(layer_details, context),
            parent_group1,
        )

        # group in LayerDetails, should be a sub group of the parent group from Processing settings
        layer_details = QgsProcessingContext.LayerDetails(
            "name", project2, "output_name"
        )
        layer_details.groupName = "child group"
        child_group = QgsProcessingResultsHandler.layerTreeResultsGroup(
            layer_details, context
        )
        self.assertIsInstance(child_group, QgsLayerTreeGroup)
        self.assertEqual(child_group.name(), "child group")
        self.assertCountEqual(
            project2.layerTreeRoot().children(), [new_group, parent_group1]
        )
        self.assertEqual(parent_group1.children(), [child_group])
        # same group should be used again if it already exists
        self.assertEqual(
            QgsProcessingResultsHandler.layerTreeResultsGroup(layer_details, context),
            child_group,
        )


if __name__ == "__main__":
    unittest.main()
