# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qgsplugininstallerbase.ui'
#
# Created: Thu Mar 12 17:09:35 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_QgsPluginInstallerDialogBase(object):
    def setupUi(self, QgsPluginInstallerDialogBase):
        QgsPluginInstallerDialogBase.setObjectName("QgsPluginInstallerDialogBase")
        QgsPluginInstallerDialogBase.resize(799, 382)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/installer/qgis-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QgsPluginInstallerDialogBase.setWindowIcon(icon)
        self.gridlayout = QtGui.QGridLayout(QgsPluginInstallerDialogBase)
        self.gridlayout.setObjectName("gridlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label_3 = QtGui.QLabel(QgsPluginInstallerDialogBase)
        self.label_3.setObjectName("label_3")
        self.hboxlayout.addWidget(self.label_3)
        self.buttonClose = QtGui.QPushButton(QgsPluginInstallerDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonClose.sizePolicy().hasHeightForWidth())
        self.buttonClose.setSizePolicy(sizePolicy)
        self.buttonClose.setObjectName("buttonClose")
        self.hboxlayout.addWidget(self.buttonClose)
        self.gridlayout.addLayout(self.hboxlayout, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(QgsPluginInstallerDialogBase)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.vboxlayout = QtGui.QVBoxLayout(self.tab)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName("label_5")
        self.hboxlayout1.addWidget(self.label_5)
        self.lineFilter = QtGui.QLineEdit(self.tab)
        self.lineFilter.setEnabled(True)
        self.lineFilter.setObjectName("lineFilter")
        self.hboxlayout1.addWidget(self.lineFilter)
        self.comboFilter1 = QtGui.QComboBox(self.tab)
        self.comboFilter1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFilter1.sizePolicy().hasHeightForWidth())
        self.comboFilter1.setSizePolicy(sizePolicy)
        self.comboFilter1.setObjectName("comboFilter1")
        self.comboFilter1.addItem(QtCore.QString())
        self.hboxlayout1.addWidget(self.comboFilter1)
        self.comboFilter2 = QtGui.QComboBox(self.tab)
        self.comboFilter2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboFilter2.sizePolicy().hasHeightForWidth())
        self.comboFilter2.setSizePolicy(sizePolicy)
        self.comboFilter2.setObjectName("comboFilter2")
        self.hboxlayout1.addWidget(self.comboFilter2)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.treePlugins = QtGui.QTreeWidget(self.tab)
        self.treePlugins.setAlternatingRowColors(True)
        self.treePlugins.setRootIsDecorated(False)
        self.treePlugins.setItemsExpandable(False)
        self.treePlugins.setAllColumnsShowFocus(True)
        self.treePlugins.setObjectName("treePlugins")
        self.vboxlayout.addWidget(self.treePlugins)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem)
        self.buttonInstall = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonInstall.sizePolicy().hasHeightForWidth())
        self.buttonInstall.setSizePolicy(sizePolicy)
        self.buttonInstall.setMinimumSize(QtCore.QSize(160, 0))
        self.buttonInstall.setObjectName("buttonInstall")
        self.hboxlayout2.addWidget(self.buttonInstall)
        self.buttonUninstall = QtGui.QPushButton(self.tab)
        self.buttonUninstall.setEnabled(True)
        self.buttonUninstall.setObjectName("buttonUninstall")
        self.hboxlayout2.addWidget(self.buttonUninstall)
        self.vboxlayout.addLayout(self.hboxlayout2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridlayout1 = QtGui.QGridLayout(self.tab_2)
        self.gridlayout1.setObjectName("gridlayout1")
        self.treeRepositories = QtGui.QTreeWidget(self.tab_2)
        self.treeRepositories.setRootIsDecorated(False)
        self.treeRepositories.setItemsExpandable(False)
        self.treeRepositories.setObjectName("treeRepositories")
        self.gridlayout1.addWidget(self.treeRepositories, 0, 0, 1, 7)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem1, 1, 1, 1, 1)
        self.buttonFetchRepositories = QtGui.QPushButton(self.tab_2)
        self.buttonFetchRepositories.setEnabled(True)
        self.buttonFetchRepositories.setObjectName("buttonFetchRepositories")
        self.gridlayout1.addWidget(self.buttonFetchRepositories, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2, 1, 3, 1, 1)
        self.buttonAddRep = QtGui.QPushButton(self.tab_2)
        self.buttonAddRep.setObjectName("buttonAddRep")
        self.gridlayout1.addWidget(self.buttonAddRep, 1, 4, 1, 1)
        self.buttonEditRep = QtGui.QPushButton(self.tab_2)
        self.buttonEditRep.setObjectName("buttonEditRep")
        self.gridlayout1.addWidget(self.buttonEditRep, 1, 5, 1, 1)
        self.buttonDeleteRep = QtGui.QPushButton(self.tab_2)
        self.buttonDeleteRep.setObjectName("buttonDeleteRep")
        self.gridlayout1.addWidget(self.buttonDeleteRep, 1, 6, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkUpdates = QtGui.QGroupBox(self.tab_3)
        self.checkUpdates.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkUpdates.sizePolicy().hasHeightForWidth())
        self.checkUpdates.setSizePolicy(sizePolicy)
        self.checkUpdates.setCheckable(True)
        self.checkUpdates.setChecked(False)
        self.checkUpdates.setObjectName("checkUpdates")
        self.gridLayout = QtGui.QGridLayout(self.checkUpdates)
        self.gridLayout.setObjectName("gridLayout")
        self.comboInterval = QtGui.QComboBox(self.checkUpdates)
        self.comboInterval.setObjectName("comboInterval")
        self.comboInterval.addItem(QtCore.QString())
        self.comboInterval.addItem(QtCore.QString())
        self.comboInterval.addItem(QtCore.QString())
        self.comboInterval.addItem(QtCore.QString())
        self.comboInterval.addItem(QtCore.QString())
        self.comboInterval.addItem(QtCore.QString())
        self.gridLayout.addWidget(self.comboInterval, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.checkUpdates)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.checkUpdates)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioPluginType0 = QtGui.QRadioButton(self.groupBox_2)
        self.radioPluginType0.setEnabled(False)
        self.radioPluginType0.setChecked(True)
        self.radioPluginType0.setObjectName("radioPluginType0")
        self.gridLayout_2.addWidget(self.radioPluginType0, 0, 0, 1, 1)
        self.radioPluginType1 = QtGui.QRadioButton(self.groupBox_2)
        self.radioPluginType1.setEnabled(False)
        self.radioPluginType1.setChecked(False)
        self.radioPluginType1.setObjectName("radioPluginType1")
        self.gridLayout_2.addWidget(self.radioPluginType1, 1, 0, 1, 1)
        self.radioPluginType2 = QtGui.QRadioButton(self.groupBox_2)
        self.radioPluginType2.setEnabled(False)
        self.radioPluginType2.setObjectName("radioPluginType2")
        self.gridLayout_2.addWidget(self.radioPluginType2, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 75))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridlayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(QgsPluginInstallerDialogBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonClose, QtCore.SIGNAL("released()"), QgsPluginInstallerDialogBase.close)
        QtCore.QMetaObject.connectSlotsByName(QgsPluginInstallerDialogBase)
        QgsPluginInstallerDialogBase.setTabOrder(self.tabWidget, self.lineFilter)
        QgsPluginInstallerDialogBase.setTabOrder(self.lineFilter, self.comboFilter1)
        QgsPluginInstallerDialogBase.setTabOrder(self.comboFilter1, self.comboFilter2)
        QgsPluginInstallerDialogBase.setTabOrder(self.comboFilter2, self.treePlugins)
        QgsPluginInstallerDialogBase.setTabOrder(self.treePlugins, self.buttonInstall)
        QgsPluginInstallerDialogBase.setTabOrder(self.buttonInstall, self.buttonUninstall)
        QgsPluginInstallerDialogBase.setTabOrder(self.buttonUninstall, self.buttonClose)
        QgsPluginInstallerDialogBase.setTabOrder(self.buttonClose, self.treeRepositories)
        QgsPluginInstallerDialogBase.setTabOrder(self.treeRepositories, self.buttonFetchRepositories)
        QgsPluginInstallerDialogBase.setTabOrder(self.buttonFetchRepositories, self.buttonAddRep)
        QgsPluginInstallerDialogBase.setTabOrder(self.buttonAddRep, self.buttonEditRep)
        QgsPluginInstallerDialogBase.setTabOrder(self.buttonEditRep, self.buttonDeleteRep)
        QgsPluginInstallerDialogBase.setTabOrder(self.buttonDeleteRep, self.checkUpdates)
        QgsPluginInstallerDialogBase.setTabOrder(self.checkUpdates, self.comboInterval)
        QgsPluginInstallerDialogBase.setTabOrder(self.comboInterval, self.radioPluginType0)
        QgsPluginInstallerDialogBase.setTabOrder(self.radioPluginType0, self.radioPluginType1)
        QgsPluginInstallerDialogBase.setTabOrder(self.radioPluginType1, self.radioPluginType2)

    def retranslateUi(self, QgsPluginInstallerDialogBase):
        QgsPluginInstallerDialogBase.setWindowTitle(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "QGIS Python Plugin Installer", None, QtGui.QApplication.UnicodeUTF8))
        QgsPluginInstallerDialogBase.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "QGIS Python Plugin Installer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "The plugins will be installed to ~/.qgis/python/plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonClose.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Close the Installer window", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonClose.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Close the Installer window", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonClose.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.lineFilter.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Display only plugins containing this word in their metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.lineFilter.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Display only plugins containing this word in their metadata", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFilter1.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Display only plugins from given repository", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFilter1.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Display only plugins from given repository", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFilter1.setItemText(0, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "all repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFilter2.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Display only plugins with matching status", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFilter2.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Display only plugins with matching status", None, QtGui.QApplication.UnicodeUTF8))
        self.treePlugins.setSortingEnabled(True)
        self.treePlugins.headerItem().setText(0, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.treePlugins.headerItem().setText(1, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treePlugins.headerItem().setText(2, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.treePlugins.headerItem().setText(3, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.treePlugins.headerItem().setText(4, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.treePlugins.headerItem().setText(5, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Repository", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInstall.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Install, reinstall or upgrade the selected plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInstall.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Install, reinstall or upgrade the selected plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInstall.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Install/upgrade plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUninstall.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Uninstall the selected plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUninstall.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Uninstall the selected plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonUninstall.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Uninstall plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "List of available and installed plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRepositories.headerItem().setText(0, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRepositories.headerItem().setText(1, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeRepositories.headerItem().setText(2, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "URL", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFetchRepositories.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Add third party plugin repositories to the list", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFetchRepositories.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Add third party plugin repositories to the list", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonFetchRepositories.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Add 3rd party repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddRep.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Add a new plugin repository", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddRep.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Add a new plugin repository", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAddRep.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Add...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEditRep.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Edit the selected repository", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEditRep.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Edit the selected repository", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEditRep.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Edit...", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeleteRep.setToolTip(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Remove the selected repository", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeleteRep.setWhatsThis(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Remove the selected repository", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDeleteRep.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "List of plugin repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.checkUpdates.setTitle(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Check for updates on startup", None, QtGui.QApplication.UnicodeUTF8))
        self.comboInterval.setItemText(0, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "every time QGIS starts", None, QtGui.QApplication.UnicodeUTF8))
        self.comboInterval.setItemText(1, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "once a day", None, QtGui.QApplication.UnicodeUTF8))
        self.comboInterval.setItemText(2, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "every 3 days", None, QtGui.QApplication.UnicodeUTF8))
        self.comboInterval.setItemText(3, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "every week", None, QtGui.QApplication.UnicodeUTF8))
        self.comboInterval.setItemText(4, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "every 2 weeks", None, QtGui.QApplication.UnicodeUTF8))
        self.comboInterval.setItemText(5, QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "every month", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Note:</span> If this function is enabled, Quantum GIS will inform you whenever a new plugin or plugin update is available. Otherwise, fetching repositories will be performed during opening of the Plugin Installer window.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Allowed plugins", None, QtGui.QApplication.UnicodeUTF8))
        self.radioPluginType0.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Only show plugins from the official repository", None, QtGui.QApplication.UnicodeUTF8))
        self.radioPluginType1.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Show all plugins except those marked as experimental", None, QtGui.QApplication.UnicodeUTF8))
        self.radioPluginType2.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Show all plugins, even those marked as experimental", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Note:</span> Experimental plugins are generally unsuitable for production use. These plugins are in early stages of development, and should be considered \'incomplete\' or \'proof of concept\' tools. QGIS does not recommend installing these plugins unless you intend to use them for testing purposes.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("QgsPluginInstallerDialogBase", "Configuration of the plugin installer", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
