/***************************************************************************
    qgsvaluemapwidgetwrapper.cpp
     --------------------------------------
    Date                 : 5.1.2014
    Copyright            : (C) 2014 Matthias Kuhn
    Email                : matthias at opengis dot ch
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#include "qgsvaluemapwidgetwrapper.h"
#include "moc_qgsvaluemapwidgetwrapper.cpp"
#include "qgsvaluemapconfigdlg.h"
#include "qgsvaluemapfieldformatter.h"
#include "qgsapplication.h"

#include <QSettings>

QgsValueMapWidgetWrapper::QgsValueMapWidgetWrapper( QgsVectorLayer *layer, int fieldIdx, QWidget *editor, QWidget *parent )
  : QgsEditorWidgetWrapper( layer, fieldIdx, editor, parent )

{
}


QVariant QgsValueMapWidgetWrapper::value() const
{
  QVariant v;

  if ( mComboBox )
  {
    v = mComboBox->currentData();
  }

  if ( v == QgsValueMapFieldFormatter::NULL_VALUE )
    v = QgsVariantUtils::createNullVariant( field().type() );

  return v;
}

void QgsValueMapWidgetWrapper::showIndeterminateState()
{
  if ( mComboBox )
  {
    whileBlocking( mComboBox )->setCurrentIndex( -1 );
  }
}

QWidget *QgsValueMapWidgetWrapper::createWidget( QWidget *parent )
{
  QComboBox *combo = new QComboBox( parent );
  combo->setMinimumContentsLength( 1 );
  combo->setSizeAdjustPolicy( QComboBox::SizeAdjustPolicy::AdjustToMinimumContentsLengthWithIcon );
  return combo;
}

void QgsValueMapWidgetWrapper::initWidget( QWidget *editor )
{
  mComboBox = qobject_cast<QComboBox *>( editor );

  if ( mComboBox )
  {
    QgsValueMapConfigDlg::populateComboBox( mComboBox, config(), false );
    mComboBox->view()->setVerticalScrollBarPolicy( Qt::ScrollBarAsNeeded );
    connect( mComboBox, static_cast<void ( QComboBox::* )( int )>( &QComboBox::currentIndexChanged ), this, static_cast<void ( QgsEditorWidgetWrapper::* )()>( &QgsEditorWidgetWrapper::emitValueChanged ) );
  }
}

bool QgsValueMapWidgetWrapper::valid() const
{
  return mComboBox;
}

void QgsValueMapWidgetWrapper::updateValues( const QVariant &value, const QVariantList & )
{
  QString v;
  bool valueIsNull = QgsVariantUtils::isNull( value );
  if ( valueIsNull )
    v = QgsValueMapFieldFormatter::NULL_VALUE;
  else
    v = value.toString();

  if ( mComboBox )
  {
    bool allowNull = config( QStringLiteral( "AllowNull" ) ).toBool();
    if ( mComboBox->findData( v ) == -1 )
    {
      // v != "" is to check for the autogenerated null value, which should be represented as '()' instead of '(Null)'.
      if ( allowNull && v != "" )
          mComboBox->addItem( QgsApplication::nullRepresentation().prepend( '(' ).append( ')' ), QgsValueMapFieldFormatter::NULL_VALUE );
      if( !valueIsNull && !( !allowNull && v == "" ) )
      {
        mComboBox->addItem( QString( v ).prepend( '(' ).append( ')' ), v );
      }
    }
    //Set the comboboxes current index to that of the item which was just added or which was already in the combobox.
    //The check is to avoid setting the index to -1 in case of the autogenerated null value and allow null unchecked.
    if ( mComboBox->findData( v ) != -1 )
      mComboBox->setCurrentIndex( mComboBox->findData( v ) );
  }
}
