/***************************************************************************
  qgslabelingresults.h
  -------------------
   begin                : February 2021
   copyright            : (C) Nyall Dawson
   email                : nyall dot dawson at gmail dot com
 ***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef QGSLABELINGRESULTS_H
#define QGSLABELINGRESULTS_H

#include <memory>

#include "qgis_core.h"
#include "qgis_sip.h"
#include "qgscalloutposition.h"
#include "qgslabelposition.h"
#include "qgsmapsettings.h"

#include <QTransform>

class QgsMapSettings;
class QgsLabelSearchTree;

#ifndef SIP_RUN
namespace pal
{
  class LabelPosition;
}
#endif

/**
 * \ingroup core
 * \brief Stores computed placement from labeling engine.
 */
class CORE_EXPORT QgsLabelingResults
{
  public:
    /**
     * Constructor for QgsLabelingResults.
     * \param enableSearchTree set to FALSE to disable the search tree. This can be used to speed up labeling in cases where spatial querying of labels is not required (since QGIS 4.4)
     */
    QgsLabelingResults( bool enableSearchTree = true );
    ~QgsLabelingResults();

    QgsLabelingResults( const QgsLabelingResults & ) = delete;
    QgsLabelingResults &operator=( const QgsLabelingResults &rh ) = delete;

    /**
     * Returns TRUE if the results were constructed with search tree enabled.
     *
     * If the search tree is not available, then spatial querying based methods like labelsAtPosition() will not be available.
     *
     * \since QGIS 4.4
     */
    bool hasSearchTree() const;

#ifndef SIP_RUN
    /**
     * Inserts label position. Does not take ownership of labelPos
     * \returns TRUE in case of success
     * \note not available in Python bindings
     *
     * \since QGIS 4.4
     */
    bool insertLabel(
      pal::LabelPosition *labelPos,
      QgsFeatureId featureId,
      const QString &layerName,
      const QString &labeltext,
      const QFont &labelfont,
      bool diagram = false,
      bool pinned = false,
      const QString &providerId = QString(),
      bool isUnplaced = false,
      long long linkedId = 0
    );
#endif

    /**
     * Inserts a rendered callout position.
     *
     * \returns TRUE in case of success
     * \note not available in Python bindings
     * \since QGIS 4.4
     */
    bool insertCallout( const QgsCalloutPosition &position ) SIP_SKIP;

    /**
     * Returns a list of all labels generated by the labeling run.
     *
     * \since QGIS 3.20
     */
    QList< QgsLabelPosition > allLabels() const;

    /**
     * Returns the details of any labels placed at the specified point (in map coordinates).
     *
     * \note Only available when hasSearchTree() is TRUE.
     */
    QList<QgsLabelPosition> labelsAtPosition( const QgsPointXY &p ) const;

    /**
     * Returns the details of any labels placed within the specified rectangle (in map coordinates).
     *
     * \note Only available when hasSearchTree() is TRUE.
     */
    QList<QgsLabelPosition> labelsWithinRect( const QgsRectangle &r ) const;

    /**
     * Returns a list of all label positions sharing the same group ID (i.e. positions for individual characters in a curved label).
     *
     * \note Only available when hasSearchTree() is TRUE.
     *
     * \since QGIS 3.26
     */
    QList<QgsLabelPosition> groupedLabelPositions( long long groupId ) const;

    /**
     * Returns a list of callouts with origins or destinations inside the given \a rectangle.
     *
     * The \a rectangle is specified in map coordinates.
     *
     * \note Only available when hasSearchTree() is TRUE.
     *
     * \since QGIS 3.20
     */
    QList<QgsCalloutPosition> calloutsWithinRectangle( const QgsRectangle &rectangle ) const;

    /**
     * Sets the map \a settings associated with the labeling run.
     * \since QGIS 3.4.8
     */
    void setMapSettings( const QgsMapSettings &settings );

  private:
#ifdef SIP_RUN
    QgsLabelingResults( const QgsLabelingResults & );
#endif

    std::unique_ptr< QgsLabelSearchTree > mLabelSearchTree;
    // used only when mLabelSearchTree is nullptr
    QList< QgsLabelPosition > mAllLabels;

    QgsMapSettings mMapSettings;
    QTransform mTransform;
    long long mNextFeatureId = 1;
    QHash< long long, QList< QgsLabelPosition * > > mLinkedLabelHash;

    std::vector< std::unique_ptr< QgsLabelPosition > > mOwnedPositions;
    std::vector< std::unique_ptr< QgsCalloutPosition > > mOwnedCalloutPositions;
};

#endif // QGSLABELINGRESULTS_H
