/***************************************************************************
                          qgslabelsearchtree.h
            Node for raster calculator tree
                          --------------------
    begin                : 2010-11-02
    copyright            : (C) 2010 by Marco Hugentobler
    email                : marco dot hugentobler at sourcepole dot ch
***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef QGSLABELSEARCHTREE_H
#define QGSLABELSEARCHTREE_H

#include "qgis_core.h"
#include "qgis_sip.h"
#include "qgscalloutposition.h"
#include "qgsgenericspatialindex.h"
#include "qgslabelposition.h"
#include "qgsmapsettings.h"

#include <QList>
#include <QVector>

class QgsPointXY;

#ifndef SIP_RUN
namespace pal
{
  class LabelPosition;
}
#endif

// TODO QGIS 5.0 - this should be private, not exposed to SIP

/**
 * \ingroup core
 * \brief Queries the labeling structure at a given point.
 *
 * This class is a small wrapper around the pal RTree class.
 */
class CORE_EXPORT QgsLabelSearchTree
{
  public:
    QgsLabelSearchTree();
    ~QgsLabelSearchTree();

    QgsLabelSearchTree( const QgsLabelSearchTree &rh ) = delete;
    QgsLabelSearchTree &operator=( const QgsLabelSearchTree &rh ) = delete;

    /**
     * Removes and deletes all the entries.
     * \deprecated QGIS 3.40. Has no effect since QGIS 3.12.
     */
    Q_DECL_DEPRECATED void clear() SIP_DEPRECATED;

    /**
     * Returns label position(s) at a given point. QgsLabelSearchTree keeps ownership, don't delete the LabelPositions
     * \note not available in Python bindings
     */
    void label( const QgsPointXY &p, QList<QgsLabelPosition *> &posList ) const SIP_SKIP;

    /**
     * Returns a list of all labels generated by the labeling run.
     *
     * \deprecated QGIS 4.4. The QgsLabelSearchTree class will be removed from Python bindings in QGIS 5.0, use the methods from QgsLabelingResults instead.
     */
    Q_DECL_DEPRECATED QList< QgsLabelPosition > allLabels() const SIP_DEPRECATED;

    /**
     * Returns label position(s) in given rectangle. QgsLabelSearchTree keeps ownership, don't delete the LabelPositions
     * \note not available in Python bindings
     */
    void labelsInRect( const QgsRectangle &r, QList<QgsLabelPosition *> &posList ) const SIP_SKIP;

    /**
     * Returns the list of callouts with origins or destinations inside the given \a rectangle.
     *
     * The \a rectangle is specified in map coordinates.
     *
     * QgsLabelSearchTree keeps ownership, don't delete the returned objects.
     *
     * \since QGIS 3.20
     */
    QList<const QgsCalloutPosition *> calloutsInRectangle( const QgsRectangle &rectangle ) const;

    /**
     * Sets the map \a settings associated with the labeling run.
     * \deprecated QGIS 4.4. The QgsLabelSearchTree class will be removed from Python bindings in QGIS 5.0, use the methods from QgsLabelingResults instead.
     */
    Q_DECL_DEPRECATED void setMapSettings( const QgsMapSettings &settings ) SIP_DEPRECATED;

  private:
    QgsGenericSpatialIndex< QgsLabelPosition > mSpatialIndex;
    QgsGenericSpatialIndex< QgsCalloutPosition > mCalloutIndex;

#ifdef SIP_RUN
    QgsLabelSearchTree( const QgsLabelSearchTree &rh );
    QgsLabelSearchTree &operator=( const QgsLabelSearchTree & );
#endif

    friend class QgsLabelingResults;
};

#endif // QGSLABELTREE_H
