######################################################################
# Automatically generated by qmake (2.00a) Sat Jan 7 08:34:57 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += . /usr/local/mysql/include/mysql ../../src ../..
LIBS += -lmysqlclient -L/usr/local/mysql/lib/mysql
CONFIG += qt
# Input
SOURCES += testmysql.cpp #qgsmysqlprovider.cpp
