/***************************************************************************
                         qgsprocessingdefaultstyleregistry.h
                         ------------------------
    begin                : Septeber 2026
    copyright            : (C) 2026 by Nyall Dawson
    email                : nyall dot dawson at gmail dot com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef QGSPROCESSINGDEFAULTSTYLEREGISTRY_H
#define QGSPROCESSINGDEFAULTSTYLEREGISTRY_H

#include "qgis.h"
#include "qgis_core.h"

#include <QObject>

/**
 * \class QgsProcessingDefaultStyleRegistry
 * \ingroup core
 * \brief A registry for default styles to apply to layers generated by Processing.
 *
 * QgsProcessingDefaultStyleRegistry is not usually directly created, but rather accessed through
 * QgsApplication::processingRegistry()->defaultStyleRegistry().
 *
 * \since QGIS 4.4
 */
class CORE_EXPORT QgsProcessingDefaultStyleRegistry : public QObject
{
    Q_OBJECT

  public:
    /**
     * Constructor for QgsProcessingDefaultStyleRegistry.
     *
     * QgsProcessingDefaultStyleRegistry is not usually directly created, but rather accessed through
     * QgsApplication::processingRegistry()->defaultStyleRegistry().
     */
    QgsProcessingDefaultStyleRegistry( QObject *parent = nullptr );
};


#endif // QGSPROCESSINGDEFAULTSTYLEREGISTRY_H
