# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins
# Target is a library:  

TEMPLATE = lib 
CONFIG += debug \
          warn_on \
          qt \
          thread 
SOURCES += qgistestplugin.cpp 
HEADERS += qgisplugin.h \
           qgistestplugin.h 
