#!/bin/sh

NAME=`sed -e 's/.*:\([^:]*\)@.*/\1/' CVS/Root`

RAND=`md5sum ChangeLog | awk '{print $1}'`

TMPFILE=/tmp/qgis-commit-${RAND}.tmp

MAJOR_VERSION=`sed -n -e 's/MAJOR_VERSION=//p' configure.in`
MINOR_VERSION=`sed -n -e 's/MINOR_VERSION=//p' configure.in`
MICRO_VERSION=`sed -n -e 's/MICRO_VERSION=//p' configure.in`
EXTRA_VERSION=`sed -n -e 's/EXTRA_VERSION=//p' configure.in`

#
# Change Extra Version
#

NEXTRA_VERSION=`expr ${EXTRA_VERSION} + 1`
sed -e "/EXTRA_VERSION=/s/${EXTRA_VERSION}/${NEXTRA_VERSION}/" configure.in > configure.in.tmp
mv configure.in.tmp configure.in

#
# Get Changes
#
echo "************************************************************" > ${TMPFILE}
echo "Please write above that line of stars! Rest will be removed." >> ${TMPFILE}

cvs diff 2> /dev/null | sed -e "/^?/d" -e "/^Index: /d" >> ${TMPFILE}

${EDITOR} ${TMPFILE}

#
# Add to ChangeLog
#

CLINES=`wc -l ChangeLog | awk '{print $1}'`
DIFFLINES=`expr $CLINES - 4`
DATE=`date +%F`
MSG=`sed -e '/\*\{20\}/,$d' ${TMPFILE}`

head -n 5 ChangeLog > ChangeLog.tmp
echo "${DATE} [${NAME}] ${MAJOR_VERSION}.${MINOR_VERSION}.${MICRO_VERSION}devel${NEXTRA_VERSION}" >> ChangeLog.tmp
echo "${MSG}" >> ChangeLog.tmp
tail -n $DIFFLINES ChangeLog >> ChangeLog.tmp
mv ChangeLog.tmp ChangeLog

#
# Commit
#

cvs commit -m "${MSG}"

rm ${TMPFILE}
