STDSUBDIRS = core ui legend raster composer widgets helpviewer
#providers plugins

WINSUBDIRS = gui

all: stdsubdirs winsubdirs

install: all
	$(MAKE) -C gui -f Makefile.win install

include ../Makefile.win.rules
