# The following has been generated automatically from src/gui/qgsattributeformwidget.h
QgsAttributeFormWidget.DefaultMode = QgsAttributeFormWidget.Mode.DefaultMode
QgsAttributeFormWidget.MultiEditMode = QgsAttributeFormWidget.Mode.MultiEditMode
QgsAttributeFormWidget.SearchMode = QgsAttributeFormWidget.Mode.SearchMode
QgsAttributeFormWidget.AggregateSearchMode = QgsAttributeFormWidget.Mode.AggregateSearchMode
