# The following has been generated automatically from src/gui/qgscoordinatereferencesystemmodel.h
QgsCoordinateReferenceSystemModel.RoleNodeType = QgsCoordinateReferenceSystemModel.Roles.RoleNodeType
QgsCoordinateReferenceSystemModel.RoleName = QgsCoordinateReferenceSystemModel.Roles.RoleName
QgsCoordinateReferenceSystemModel.RoleAuthId = QgsCoordinateReferenceSystemModel.Roles.RoleAuthId
QgsCoordinateReferenceSystemModel.RoleDeprecated = QgsCoordinateReferenceSystemModel.Roles.RoleDeprecated
QgsCoordinateReferenceSystemModel.RoleType = QgsCoordinateReferenceSystemModel.Roles.RoleType
QgsCoordinateReferenceSystemModel.RoleGroupId = QgsCoordinateReferenceSystemModel.Roles.RoleGroupId
QgsCoordinateReferenceSystemModel.RoleWkt = QgsCoordinateReferenceSystemModel.Roles.RoleWkt
QgsCoordinateReferenceSystemModel.RoleProj = QgsCoordinateReferenceSystemModel.Roles.RoleProj
QgsCoordinateReferenceSystemProxyModel.FilterHorizontal = QgsCoordinateReferenceSystemProxyModel.Filter.FilterHorizontal
QgsCoordinateReferenceSystemProxyModel.FilterVertical = QgsCoordinateReferenceSystemProxyModel.Filter.FilterVertical
QgsCoordinateReferenceSystemProxyModel.FilterCompound = QgsCoordinateReferenceSystemProxyModel.Filter.FilterCompound
QgsCoordinateReferenceSystemProxyModel.Filters = lambda flags=0: QgsCoordinateReferenceSystemProxyModel.Filter(flags)
QgsCoordinateReferenceSystemProxyModel.Filters.baseClass = QgsCoordinateReferenceSystemProxyModel
Filters = QgsCoordinateReferenceSystemProxyModel  # dirty hack since SIP seems to introduce the flags in module
