# The following has been generated automatically from src/gui/qgsexternalresourcewidget.h
QgsExternalResourceWidget.NoContent = QgsExternalResourceWidget.DocumentViewerContent.NoContent
QgsExternalResourceWidget.Image = QgsExternalResourceWidget.DocumentViewerContent.Image
QgsExternalResourceWidget.Web = QgsExternalResourceWidget.DocumentViewerContent.Web
QgsExternalResourceWidget.Audio = QgsExternalResourceWidget.DocumentViewerContent.Audio
QgsExternalResourceWidget.Video = QgsExternalResourceWidget.DocumentViewerContent.Video
