# The following has been generated automatically from src/gui/qgsexternalstoragefilewidget.h
QgsExternalStorageFileWidget.createFileWidgetScope = staticmethod(QgsExternalStorageFileWidget.createFileWidgetScope)
