# The following has been generated automatically from src/gui/qgsfilecontentsourcelineedit.h
QgsPictureSourceLineEditBase.Svg = QgsPictureSourceLineEditBase.Format.Svg
QgsPictureSourceLineEditBase.Image = QgsPictureSourceLineEditBase.Format.Image
QgsPictureSourceLineEditBase.AnimatedImage = QgsPictureSourceLineEditBase.Format.AnimatedImage
