# The following has been generated automatically from src/gui/qgsmapcanvasannotationitem.h
QgsMapCanvasAnnotationItem.NoAction = QgsMapCanvasAnnotationItem.MouseMoveAction.NoAction
QgsMapCanvasAnnotationItem.MoveMapPosition = QgsMapCanvasAnnotationItem.MouseMoveAction.MoveMapPosition
QgsMapCanvasAnnotationItem.MoveFramePosition = QgsMapCanvasAnnotationItem.MouseMoveAction.MoveFramePosition
QgsMapCanvasAnnotationItem.ResizeFrameUp = QgsMapCanvasAnnotationItem.MouseMoveAction.ResizeFrameUp
QgsMapCanvasAnnotationItem.ResizeFrameDown = QgsMapCanvasAnnotationItem.MouseMoveAction.ResizeFrameDown
QgsMapCanvasAnnotationItem.ResizeFrameLeft = QgsMapCanvasAnnotationItem.MouseMoveAction.ResizeFrameLeft
QgsMapCanvasAnnotationItem.ResizeFrameRight = QgsMapCanvasAnnotationItem.MouseMoveAction.ResizeFrameRight
QgsMapCanvasAnnotationItem.ResizeFrameLeftUp = QgsMapCanvasAnnotationItem.MouseMoveAction.ResizeFrameLeftUp
QgsMapCanvasAnnotationItem.ResizeFrameRightUp = QgsMapCanvasAnnotationItem.MouseMoveAction.ResizeFrameRightUp
QgsMapCanvasAnnotationItem.ResizeFrameLeftDown = QgsMapCanvasAnnotationItem.MouseMoveAction.ResizeFrameLeftDown
QgsMapCanvasAnnotationItem.ResizeFrameRightDown = QgsMapCanvasAnnotationItem.MouseMoveAction.ResizeFrameRightDown
