# The following has been generated automatically from src/gui/qgsprevieweffect.h
QgsPreviewEffect.PreviewGrayscale = QgsPreviewEffect.PreviewMode.PreviewGrayscale
QgsPreviewEffect.PreviewMono = QgsPreviewEffect.PreviewMode.PreviewMono
QgsPreviewEffect.PreviewProtanope = QgsPreviewEffect.PreviewMode.PreviewProtanope
QgsPreviewEffect.PreviewDeuteranope = QgsPreviewEffect.PreviewMode.PreviewDeuteranope
QgsPreviewEffect.PreviewTritanope = QgsPreviewEffect.PreviewMode.PreviewTritanope
