# The following has been generated automatically from src/gui/processing/qgsprocessingtoolboxmodel.h
QgsProcessingToolboxModelNode.NodeProvider = QgsProcessingToolboxModelNode.NodeType.NodeProvider
QgsProcessingToolboxModelNode.NodeGroup = QgsProcessingToolboxModelNode.NodeType.NodeGroup
QgsProcessingToolboxModelNode.NodeAlgorithm = QgsProcessingToolboxModelNode.NodeType.NodeAlgorithm
QgsProcessingToolboxModelNode.NodeRecent = QgsProcessingToolboxModelNode.NodeType.NodeRecent
QgsProcessingToolboxModel.RoleNodeType = QgsProcessingToolboxModel.Roles.RoleNodeType
QgsProcessingToolboxModel.RoleAlgorithmFlags = QgsProcessingToolboxModel.Roles.RoleAlgorithmFlags
QgsProcessingToolboxModel.RoleAlgorithmId = QgsProcessingToolboxModel.Roles.RoleAlgorithmId
QgsProcessingToolboxModel.RoleAlgorithmName = QgsProcessingToolboxModel.Roles.RoleAlgorithmName
QgsProcessingToolboxModel.RoleAlgorithmShortDescription = QgsProcessingToolboxModel.Roles.RoleAlgorithmShortDescription
QgsProcessingToolboxModel.RoleAlgorithmTags = QgsProcessingToolboxModel.Roles.RoleAlgorithmTags
QgsProcessingToolboxModel.RoleProviderFlags = QgsProcessingToolboxModel.Roles.RoleProviderFlags
QgsProcessingToolboxProxyModel.FilterToolbox = QgsProcessingToolboxProxyModel.Filter.FilterToolbox
QgsProcessingToolboxProxyModel.FilterModeler = QgsProcessingToolboxProxyModel.Filter.FilterModeler
QgsProcessingToolboxProxyModel.FilterInPlace = QgsProcessingToolboxProxyModel.Filter.FilterInPlace
QgsProcessingToolboxProxyModel.FilterShowKnownIssues = QgsProcessingToolboxProxyModel.Filter.FilterShowKnownIssues
QgsProcessingToolboxProxyModel.Filters = lambda flags=0: QgsProcessingToolboxProxyModel.Filter(flags)
QgsProcessingToolboxProxyModel.Filters.baseClass = QgsProcessingToolboxProxyModel
Filters = QgsProcessingToolboxProxyModel  # dirty hack since SIP seems to introduce the flags in module
