# The following has been generated automatically from src/gui/qgsrasterlayersaveasdialog.h
QgsRasterLayerSaveAsDialog.RawDataMode = QgsRasterLayerSaveAsDialog.Mode.RawDataMode
QgsRasterLayerSaveAsDialog.RenderedImageMode = QgsRasterLayerSaveAsDialog.Mode.RenderedImageMode
QgsRasterLayerSaveAsDialog.OriginalCrs = QgsRasterLayerSaveAsDialog.CrsState.OriginalCrs
QgsRasterLayerSaveAsDialog.CurrentCrs = QgsRasterLayerSaveAsDialog.CrsState.CurrentCrs
QgsRasterLayerSaveAsDialog.UserCrs = QgsRasterLayerSaveAsDialog.CrsState.UserCrs
QgsRasterLayerSaveAsDialog.OriginalResolution = QgsRasterLayerSaveAsDialog.ResolutionState.OriginalResolution
QgsRasterLayerSaveAsDialog.UserResolution = QgsRasterLayerSaveAsDialog.ResolutionState.UserResolution
