# The following has been generated automatically from src/gui/proj/qgsrecentcoordinatereferencesystemsmodel.h
QgsRecentCoordinateReferenceSystemsModel.RoleNodeType = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleNodeType
QgsRecentCoordinateReferenceSystemsModel.RoleName = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleName
QgsRecentCoordinateReferenceSystemsModel.RoleAuthId = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleAuthId
QgsRecentCoordinateReferenceSystemsModel.RoleDeprecated = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleDeprecated
QgsRecentCoordinateReferenceSystemsModel.RoleType = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleType
QgsRecentCoordinateReferenceSystemsModel.RoleGroupId = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleGroupId
QgsRecentCoordinateReferenceSystemsModel.RoleWkt = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleWkt
QgsRecentCoordinateReferenceSystemsModel.RoleProj = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleProj
QgsRecentCoordinateReferenceSystemsProxyModel.FilterHorizontal = QgsRecentCoordinateReferenceSystemsProxyModel.Filter.FilterHorizontal
QgsRecentCoordinateReferenceSystemsProxyModel.FilterVertical = QgsRecentCoordinateReferenceSystemsProxyModel.Filter.FilterVertical
QgsRecentCoordinateReferenceSystemsProxyModel.FilterCompound = QgsRecentCoordinateReferenceSystemsProxyModel.Filter.FilterCompound
QgsRecentCoordinateReferenceSystemsProxyModel.Filters = lambda flags=0: QgsRecentCoordinateReferenceSystemsProxyModel.Filter(flags)
QgsRecentCoordinateReferenceSystemsProxyModel.Filters.baseClass = QgsRecentCoordinateReferenceSystemsProxyModel
Filters = QgsRecentCoordinateReferenceSystemsProxyModel  # dirty hack since SIP seems to introduce the flags in module
