# The following has been generated automatically from src/gui/proj/qgsrecentcoordinatereferencesystemsmodel.h
QgsRecentCoordinateReferenceSystemsModel.RoleNodeType = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleNodeType
QgsRecentCoordinateReferenceSystemsModel.RoleName = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleName
QgsRecentCoordinateReferenceSystemsModel.RoleAuthId = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleAuthId
QgsRecentCoordinateReferenceSystemsModel.RoleDeprecated = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleDeprecated
QgsRecentCoordinateReferenceSystemsModel.RoleType = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleType
QgsRecentCoordinateReferenceSystemsModel.RoleGroupId = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleGroupId
QgsRecentCoordinateReferenceSystemsModel.RoleWkt = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleWkt
QgsRecentCoordinateReferenceSystemsModel.RoleProj = QgsRecentCoordinateReferenceSystemsModel.Roles.RoleProj
